// Code generated by hertz generator.

package permission

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	http_base "github.com/masonsxu/cloudwego-microservice-demo/gateway/biz/model/http_base"
	permission "github.com/masonsxu/cloudwego-microservice-demo/gateway/biz/model/permission"
)

// CreateRoleDefinition .
// @router /api/v1/permission/roles [POST]
func CreateRoleDefinition(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.RoleDefinitionCreateRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.RoleDefinitionCreateResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UpdateRoleDefinition .
// @router /api/v1/permission/roles/:roleDefinitionID [PUT]
func UpdateRoleDefinition(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.RoleDefinitionUpdateRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.RoleDefinitionUpdateResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// DeleteRoleDefinition .
// @router /api/v1/permission/roles/:roleID [DELETE]
func DeleteRoleDefinition(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.RoleDefinitionDeleteRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetRoleDefinition .
// @router /api/v1/permission/roles/:roleID [GET]
func GetRoleDefinition(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.RoleDefinitionGetRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.RoleDefinitionGetResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ListRoleDefinitions .
// @router /api/v1/permission/roles [GET]
func ListRoleDefinitions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.RoleDefinitionQueryRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.RoleDefinitionListResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetLastUserRoleAssignment .
// @router /api/v1/permission/users/:userID/roles/latest [GET]
func GetLastUserRoleAssignment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.GetLastUserRoleAssignmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.GetLastUserRoleAssignmentResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ListUserRoleAssignments .
// @router /api/v1/permission/user-roles [GET]
func ListUserRoleAssignments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.UserRoleQueryRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.UserRoleListResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetUsersByRole .
// @router /api/v1/permission/roles/:roleID/users [GET]
func GetUsersByRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.GetUsersByRoleRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.GetUsersByRoleResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// BatchBindUsersToRole .
// @router /api/v1/permission/roles/:roleID/users/batch-bind [POST]
func BatchBindUsersToRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.BatchBindUsersToRoleRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.BatchBindUsersToRoleResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UploadMenu .
// @router /api/v1/permission/menu/upload [POST]
func UploadMenu(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.UploadMenuRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetMenuTree .
// @router /api/v1/permission/menu/tree [GET]
func GetMenuTree(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.GetMenuTreeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.GetMenuTreeResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ConfigureRoleMenus .
// @router /api/v1/permission/roles/:roleID/menus [POST]
func ConfigureRoleMenus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.ConfigureRoleMenusRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.ConfigureRoleMenusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetRoleMenuTree .
// @router /api/v1/permission/roles/:roleID/menu-tree [GET]
func GetRoleMenuTree(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.GetRoleMenuTreeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.GetRoleMenuTreeResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetUserMenuTree .
// @router /api/v1/permission/users/:userID/menu-tree [GET]
func GetUserMenuTree(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.GetUserMenuTreeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.GetUserMenuTreeResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetRoleMenuPermissions .
// @router /api/v1/permission/roles/:roleID/menu-permissions [GET]
func GetRoleMenuPermissions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.GetRoleMenuPermissionsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.GetRoleMenuPermissionsResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// HasMenuPermission .
// @router /api/v1/permission/roles/:roleID/check-menu-permission [POST]
func HasMenuPermission(ctx context.Context, c *app.RequestContext) {
	var err error
	var req permission.HasMenuPermissionRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(permission.HasMenuPermissionResponseDTO)

	c.JSON(consts.StatusOK, resp)
}
