// Code generated by Kitex v0.16.1. DO NOT EDIT.

package rpc_base

import (
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/kitex_gen/core"

	"github.com/cloudwego/prutal"
)

// PageRequest defines pagination and query options.
type PageRequest struct {
	Page         *int32                `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Limit        *int32                `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Search       *string               `protobuf:"bytes,3,opt,name=search" json:"search,omitempty"`
	Filter       *core.StringMapValue  `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	Sort         *string               `protobuf:"bytes,5,opt,name=sort" json:"sort,omitempty"`
	Fields       *core.StringListValue `protobuf:"bytes,6,opt,name=fields" json:"fields,omitempty"`
	IncludeTotal *bool                 `protobuf:"varint,7,opt,name=includeTotal" json:"includeTotal,omitempty"`
	FetchAll     *bool                 `protobuf:"varint,8,opt,name=fetchAll" json:"fetchAll,omitempty"`
}

func (x *PageRequest) Reset() { *x = PageRequest{} }

func (x *PageRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PageRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PageRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *PageRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *PageRequest) GetFilter() *core.StringMapValue {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *PageRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *PageRequest) GetFields() *core.StringListValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PageRequest) GetIncludeTotal() bool {
	if x != nil && x.IncludeTotal != nil {
		return *x.IncludeTotal
	}
	return false
}

func (x *PageRequest) GetFetchAll() bool {
	if x != nil && x.FetchAll != nil {
		return *x.FetchAll
	}
	return false
}

// PageResponse defines pagination metadata.
type PageResponse struct {
	Total      *int32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Page       *int32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	Limit      *int32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	TotalPages *int32 `protobuf:"varint,4,opt,name=totalPages" json:"totalPages,omitempty"`
	HasNext    *bool  `protobuf:"varint,5,opt,name=hasNext" json:"hasNext,omitempty"`
	HasPrev    *bool  `protobuf:"varint,6,opt,name=hasPrev" json:"hasPrev,omitempty"`
}

func (x *PageResponse) Reset() { *x = PageResponse{} }

func (x *PageResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PageResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PageResponse) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *PageResponse) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *PageResponse) GetTotalPages() int32 {
	if x != nil && x.TotalPages != nil {
		return *x.TotalPages
	}
	return 0
}

func (x *PageResponse) GetHasNext() bool {
	if x != nil && x.HasNext != nil {
		return *x.HasNext
	}
	return false
}

func (x *PageResponse) GetHasPrev() bool {
	if x != nil && x.HasPrev != nil {
		return *x.HasPrev
	}
	return false
}
