version: "2"

run:
    modules-download-mode: readonly

output:
    formats:
        text:
            path: stdout

linters:
    default: standard
    enable:
        - gocyclo
        - nestif
        - prealloc
        - revive
        - staticcheck
        - lll
        - wsl_v5
        - unconvert
        - misspell

    settings:
        lll:
            line-length: 120
            tab-width: 1

        revive:
            rules:
                - name: line-length-limit
                  arguments: [120]

        wsl_v5:
            allow-first-in-block: true
            allow-whole-block: false
            branch-max-lines: 2

    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        paths:
            - .git
            - .vscode
            - .idea
            - bin
            - scripts
            - testdata
            - kitex_gen
            - build
            - third_party
            - builtin
            - examples
        rules:
            - linters:
                  - errcheck
                  - gocyclo
                  - ineffassign
                  - revive
                  - staticcheck
                  - unused
              path: kitex_gen

            - linters:
                  - funlen
                  - gocyclo
                  - gosec
              path: _test\.go

            - linters:
                  - revive
              text: exported.*should have comment
              source: ^// Code generated by .* DO NOT EDIT\.$

            - linters:
                  - lll
              source: "^//go:generate "

issues:
    max-issues-per-linter: 0
    max-same-issues: 0

formatters:
    enable:
        - gci
        - goimports
        - gofumpt
        - golines
        - swaggo

    settings:
        golines:
            max-len: 120

        gci:
            sections:
                - standard
                - default
                - prefix(github.com/masonsxu/cloudwego-microservice-demo/)
            custom-order: true

        goimports:
            local-prefixes:
                - github.com/masonsxu/cloudwego-microservice-demo/

    exclusions:
        paths:
            - .git
            - .vscode
            - .idea
            - bin
            - scripts
            - testdata
            - kitex_gen
            - build
            - third_party
            - builtin
            - examples
