// Code generated by hertz generator.

package main

import (
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/masonsxu/cloudwego-microservice-demo/gateway/internal/wire"
)

// 保留空实现以满足生成代码引用 app 包
var _ app.HandlerFunc

func main() {
	// 统一初始化所有依赖（只初始化一次）
	// Wire 自动管理依赖图和生命周期
	container, cleanup, err := wire.InitializeApp()
	if err != nil {
		log.Fatalf("failed to init app: %v", err)
	}
	defer cleanup()

	// 初始化中间件和 Handler 依赖
	container.HandlerRegistry.Initialize()

	// 注册路由并启动服务器
	h := container.HandlerRegistry.Server()
	register(h)
	h.Spin()
}
