// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/adaptor"
	handler "github.com/masonsxu/cloudwego-microservice-demo/gateway/biz/handler"
	_ "github.com/masonsxu/cloudwego-microservice-demo/gateway/docs"
	httpSwagger "github.com/swaggo/http-swagger"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// Swagger API 文档
	r.GET("/swagger/*any", adaptor.HertzHandler(httpSwagger.WrapHandler))
}
