// Code generated by Kitex v0.16.1. DO NOT EDIT.

package identity_srv

import (
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/kitex_gen/core"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 审计操作类型。
type AuditAction int32

const (
	AuditAction_AUDIT_ACTION_UNSPECIFIED     AuditAction = 0
	AuditAction_AUDIT_ACTION_CREATE          AuditAction = 1
	AuditAction_AUDIT_ACTION_UPDATE          AuditAction = 2
	AuditAction_AUDIT_ACTION_DELETE          AuditAction = 3
	AuditAction_AUDIT_ACTION_LOGIN           AuditAction = 4
	AuditAction_AUDIT_ACTION_LOGOUT          AuditAction = 5
	AuditAction_AUDIT_ACTION_PASSWORD_CHANGE AuditAction = 6
)

// Enum value maps for AuditAction.
var AuditAction_name = map[int32]string{
	0: "AUDIT_ACTION_UNSPECIFIED",
	1: "AUDIT_ACTION_CREATE",
	2: "AUDIT_ACTION_UPDATE",
	3: "AUDIT_ACTION_DELETE",
	4: "AUDIT_ACTION_LOGIN",
	5: "AUDIT_ACTION_LOGOUT",
	6: "AUDIT_ACTION_PASSWORD_CHANGE",
}

var AuditAction_value = map[string]int32{
	"AUDIT_ACTION_UNSPECIFIED":     0,
	"AUDIT_ACTION_CREATE":          1,
	"AUDIT_ACTION_UPDATE":          2,
	"AUDIT_ACTION_DELETE":          3,
	"AUDIT_ACTION_LOGIN":           4,
	"AUDIT_ACTION_LOGOUT":          5,
	"AUDIT_ACTION_PASSWORD_CHANGE": 6,
}

func (x AuditAction) String() string {
	s, ok := AuditAction_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 权限级别。
type PermissionLevel int32

const (
	PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED PermissionLevel = 0
	PermissionLevel_PERMISSION_LEVEL_READ        PermissionLevel = 1
	PermissionLevel_PERMISSION_LEVEL_WRITE       PermissionLevel = 2
	PermissionLevel_PERMISSION_LEVEL_FULL        PermissionLevel = 3
)

// Enum value maps for PermissionLevel.
var PermissionLevel_name = map[int32]string{
	0: "PERMISSION_LEVEL_UNSPECIFIED",
	1: "PERMISSION_LEVEL_READ",
	2: "PERMISSION_LEVEL_WRITE",
	3: "PERMISSION_LEVEL_FULL",
}

var PermissionLevel_value = map[string]int32{
	"PERMISSION_LEVEL_UNSPECIFIED": 0,
	"PERMISSION_LEVEL_READ":        1,
	"PERMISSION_LEVEL_WRITE":       2,
	"PERMISSION_LEVEL_FULL":        3,
}

func (x PermissionLevel) String() string {
	s, ok := PermissionLevel_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 数据范围。
type DataScope int32

const (
	DataScope_DATA_SCOPE_UNSPECIFIED DataScope = 0
	DataScope_DATA_SCOPE_SELF        DataScope = 1
	DataScope_DATA_SCOPE_DEPT        DataScope = 2
	DataScope_DATA_SCOPE_ORG         DataScope = 3
)

// Enum value maps for DataScope.
var DataScope_name = map[int32]string{
	0: "DATA_SCOPE_UNSPECIFIED",
	1: "DATA_SCOPE_SELF",
	2: "DATA_SCOPE_DEPT",
	3: "DATA_SCOPE_ORG",
}

var DataScope_value = map[string]int32{
	"DATA_SCOPE_UNSPECIFIED": 0,
	"DATA_SCOPE_SELF":        1,
	"DATA_SCOPE_DEPT":        2,
	"DATA_SCOPE_ORG":         3,
}

func (x DataScope) String() string {
	s, ok := DataScope_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 组织 Logo 资源状态。
type OrganizationLogoStatus int32

const (
	OrganizationLogoStatus_ORGANIZATION_LOGO_STATUS_UNSPECIFIED OrganizationLogoStatus = 0
	OrganizationLogoStatus_ORGANIZATION_LOGO_STATUS_BOUND       OrganizationLogoStatus = 1
	OrganizationLogoStatus_ORGANIZATION_LOGO_STATUS_DELETED     OrganizationLogoStatus = 2
)

// Enum value maps for OrganizationLogoStatus.
var OrganizationLogoStatus_name = map[int32]string{
	0: "ORGANIZATION_LOGO_STATUS_UNSPECIFIED",
	1: "ORGANIZATION_LOGO_STATUS_BOUND",
	2: "ORGANIZATION_LOGO_STATUS_DELETED",
}

var OrganizationLogoStatus_value = map[string]int32{
	"ORGANIZATION_LOGO_STATUS_UNSPECIFIED": 0,
	"ORGANIZATION_LOGO_STATUS_BOUND":       1,
	"ORGANIZATION_LOGO_STATUS_DELETED":     2,
}

func (x OrganizationLogoStatus) String() string {
	s, ok := OrganizationLogoStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 审计日志。
type AuditLog struct {
	Id             *string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RequestID      *string      `protobuf:"bytes,2,opt,name=requestID" json:"requestID,omitempty"`
	TraceID        *string      `protobuf:"bytes,3,opt,name=traceID" json:"traceID,omitempty"`
	UserID         *string      `protobuf:"bytes,4,opt,name=userID" json:"userID,omitempty"`
	Username       *string      `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
	OrganizationID *string      `protobuf:"bytes,6,opt,name=organizationID" json:"organizationID,omitempty"`
	Action         *AuditAction `protobuf:"varint,7,opt,name=action" json:"action,omitempty"`
	Resource       *string      `protobuf:"bytes,8,opt,name=resource" json:"resource,omitempty"`
	ResourceID     *string      `protobuf:"bytes,9,opt,name=resourceID" json:"resourceID,omitempty"`
	StatusCode     *int32       `protobuf:"varint,10,opt,name=statusCode" json:"statusCode,omitempty"`
	Success        *bool        `protobuf:"varint,11,opt,name=success" json:"success,omitempty"`
	ClientIP       *string      `protobuf:"bytes,12,opt,name=clientIP" json:"clientIP,omitempty"`
	UserAgent      *string      `protobuf:"bytes,13,opt,name=userAgent" json:"userAgent,omitempty"`
	RequestBody    *string      `protobuf:"bytes,14,opt,name=requestBody" json:"requestBody,omitempty"`
	DurationMs     *int32       `protobuf:"varint,15,opt,name=durationMs" json:"durationMs,omitempty"`
	CreatedAt      *int64       `protobuf:"varint,16,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (x *AuditLog) Reset() { *x = AuditLog{} }

func (x *AuditLog) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AuditLog) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AuditLog) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *AuditLog) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

func (x *AuditLog) GetTraceID() string {
	if x != nil && x.TraceID != nil {
		return *x.TraceID
	}
	return ""
}

func (x *AuditLog) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *AuditLog) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *AuditLog) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *AuditLog) GetAction() AuditAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return AuditAction_AUDIT_ACTION_UNSPECIFIED
}

func (x *AuditLog) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *AuditLog) GetResourceID() string {
	if x != nil && x.ResourceID != nil {
		return *x.ResourceID
	}
	return ""
}

func (x *AuditLog) GetStatusCode() int32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *AuditLog) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *AuditLog) GetClientIP() string {
	if x != nil && x.ClientIP != nil {
		return *x.ClientIP
	}
	return ""
}

func (x *AuditLog) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *AuditLog) GetRequestBody() string {
	if x != nil && x.RequestBody != nil {
		return *x.RequestBody
	}
	return ""
}

func (x *AuditLog) GetDurationMs() int32 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *AuditLog) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

// 用户画像。
type UserProfile struct {
	Id                    *string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username              *string          `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email                 *string          `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone                 *string          `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	FirstName             *string          `protobuf:"bytes,5,opt,name=firstName" json:"firstName,omitempty"`
	LastName              *string          `protobuf:"bytes,6,opt,name=lastName" json:"lastName,omitempty"`
	RealName              *string          `protobuf:"bytes,7,opt,name=realName" json:"realName,omitempty"`
	Gender                *core.Gender     `protobuf:"varint,8,opt,name=gender" json:"gender,omitempty"`
	ProfessionalTitle     *string          `protobuf:"bytes,9,opt,name=professionalTitle" json:"professionalTitle,omitempty"`
	EmployeeID            *string          `protobuf:"bytes,10,opt,name=employeeID" json:"employeeID,omitempty"`
	Status                *core.UserStatus `protobuf:"varint,11,opt,name=status" json:"status,omitempty"`
	LoginAttempts         *int32           `protobuf:"varint,12,opt,name=loginAttempts" json:"loginAttempts,omitempty"`
	MustChangePassword    *bool            `protobuf:"varint,13,opt,name=mustChangePassword" json:"mustChangePassword,omitempty"`
	AccountExpiry         *int64           `protobuf:"varint,14,opt,name=accountExpiry" json:"accountExpiry,omitempty"`
	LastLoginTime         *int64           `protobuf:"varint,15,opt,name=lastLoginTime" json:"lastLoginTime,omitempty"`
	CreatedAt             *int64           `protobuf:"varint,16,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt             *int64           `protobuf:"varint,17,opt,name=updatedAt" json:"updatedAt,omitempty"`
	CreatedBy             *string          `protobuf:"bytes,18,opt,name=createdBy" json:"createdBy,omitempty"`
	UpdatedBy             *string          `protobuf:"bytes,19,opt,name=updatedBy" json:"updatedBy,omitempty"`
	Deleted               *bool            `protobuf:"varint,20,opt,name=deleted" json:"deleted,omitempty"`
	RoleIDs               []string         `protobuf:"bytes,21,rep,name=roleIDs" json:"roleIDs,omitempty"`
	PrimaryOrganizationID *string          `protobuf:"bytes,22,opt,name=primaryOrganizationID" json:"primaryOrganizationID,omitempty"`
	PrimaryDepartmentID   *string          `protobuf:"bytes,23,opt,name=primaryDepartmentID" json:"primaryDepartmentID,omitempty"`
}

func (x *UserProfile) Reset() { *x = UserProfile{} }

func (x *UserProfile) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserProfile) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserProfile) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserProfile) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserProfile) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UserProfile) GetRealName() string {
	if x != nil && x.RealName != nil {
		return *x.RealName
	}
	return ""
}

func (x *UserProfile) GetGender() core.Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return core.Gender_GENDER_UNSPECIFIED
}

func (x *UserProfile) GetProfessionalTitle() string {
	if x != nil && x.ProfessionalTitle != nil {
		return *x.ProfessionalTitle
	}
	return ""
}

func (x *UserProfile) GetEmployeeID() string {
	if x != nil && x.EmployeeID != nil {
		return *x.EmployeeID
	}
	return ""
}

func (x *UserProfile) GetStatus() core.UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return core.UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UserProfile) GetLoginAttempts() int32 {
	if x != nil && x.LoginAttempts != nil {
		return *x.LoginAttempts
	}
	return 0
}

func (x *UserProfile) GetMustChangePassword() bool {
	if x != nil && x.MustChangePassword != nil {
		return *x.MustChangePassword
	}
	return false
}

func (x *UserProfile) GetAccountExpiry() int64 {
	if x != nil && x.AccountExpiry != nil {
		return *x.AccountExpiry
	}
	return 0
}

func (x *UserProfile) GetLastLoginTime() int64 {
	if x != nil && x.LastLoginTime != nil {
		return *x.LastLoginTime
	}
	return 0
}

func (x *UserProfile) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *UserProfile) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *UserProfile) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *UserProfile) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *UserProfile) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *UserProfile) GetRoleIDs() []string {
	if x != nil {
		return x.RoleIDs
	}
	return nil
}

func (x *UserProfile) GetPrimaryOrganizationID() string {
	if x != nil && x.PrimaryOrganizationID != nil {
		return *x.PrimaryOrganizationID
	}
	return ""
}

func (x *UserProfile) GetPrimaryDepartmentID() string {
	if x != nil && x.PrimaryDepartmentID != nil {
		return *x.PrimaryDepartmentID
	}
	return ""
}

// 用户成员关系。
type UserMembership struct {
	Id             *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserID         *string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	OrganizationID *string `protobuf:"bytes,3,opt,name=organizationID" json:"organizationID,omitempty"`
	DepartmentID   *string `protobuf:"bytes,4,opt,name=departmentID" json:"departmentID,omitempty"`
	IsPrimary      *bool   `protobuf:"varint,5,opt,name=isPrimary" json:"isPrimary,omitempty"`
	CreatedAt      *int64  `protobuf:"varint,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt      *int64  `protobuf:"varint,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (x *UserMembership) Reset() { *x = UserMembership{} }

func (x *UserMembership) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserMembership) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserMembership) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UserMembership) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *UserMembership) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *UserMembership) GetDepartmentID() string {
	if x != nil && x.DepartmentID != nil {
		return *x.DepartmentID
	}
	return ""
}

func (x *UserMembership) GetIsPrimary() bool {
	if x != nil && x.IsPrimary != nil {
		return *x.IsPrimary
	}
	return false
}

func (x *UserMembership) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *UserMembership) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

// 组织。
type Organization struct {
	Id                  *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code                *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Name                *string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ParentID            *string  `protobuf:"bytes,4,opt,name=parentID" json:"parentID,omitempty"`
	FacilityType        *string  `protobuf:"bytes,5,opt,name=facilityType" json:"facilityType,omitempty"`
	AccreditationStatus *string  `protobuf:"bytes,6,opt,name=accreditationStatus" json:"accreditationStatus,omitempty"`
	Logo                *string  `protobuf:"bytes,7,opt,name=logo" json:"logo,omitempty"`
	ProvinceCity        []string `protobuf:"bytes,8,rep,name=provinceCity" json:"provinceCity,omitempty"`
	CreatedAt           *int64   `protobuf:"varint,9,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt           *int64   `protobuf:"varint,10,opt,name=updatedAt" json:"updatedAt,omitempty"`
	LogoID              *string  `protobuf:"bytes,15,opt,name=logoID" json:"logoID,omitempty"`
}

func (x *Organization) Reset() { *x = Organization{} }

func (x *Organization) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Organization) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Organization) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Organization) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Organization) GetParentID() string {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return ""
}

func (x *Organization) GetFacilityType() string {
	if x != nil && x.FacilityType != nil {
		return *x.FacilityType
	}
	return ""
}

func (x *Organization) GetAccreditationStatus() string {
	if x != nil && x.AccreditationStatus != nil {
		return *x.AccreditationStatus
	}
	return ""
}

func (x *Organization) GetLogo() string {
	if x != nil && x.Logo != nil {
		return *x.Logo
	}
	return ""
}

func (x *Organization) GetProvinceCity() []string {
	if x != nil {
		return x.ProvinceCity
	}
	return nil
}

func (x *Organization) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *Organization) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *Organization) GetLogoID() string {
	if x != nil && x.LogoID != nil {
		return *x.LogoID
	}
	return ""
}

// 部门。
type Department struct {
	Id                 *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code               *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Name               *string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	OrganizationID     *string  `protobuf:"bytes,4,opt,name=organizationID" json:"organizationID,omitempty"`
	DepartmentType     *string  `protobuf:"bytes,5,opt,name=departmentType" json:"departmentType,omitempty"`
	AvailableEquipment []string `protobuf:"bytes,6,rep,name=availableEquipment" json:"availableEquipment,omitempty"`
	CreatedAt          *int64   `protobuf:"varint,7,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt          *int64   `protobuf:"varint,8,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (x *Department) Reset() { *x = Department{} }

func (x *Department) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Department) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Department) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Department) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Department) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *Department) GetDepartmentType() string {
	if x != nil && x.DepartmentType != nil {
		return *x.DepartmentType
	}
	return ""
}

func (x *Department) GetAvailableEquipment() []string {
	if x != nil {
		return x.AvailableEquipment
	}
	return nil
}

func (x *Department) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *Department) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

// 组织 Logo。
type OrganizationLogo struct {
	Id                  *string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FileID              *string                 `protobuf:"bytes,2,opt,name=fileID" json:"fileID,omitempty"`
	Status              *OrganizationLogoStatus `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	BoundOrganizationID *string                 `protobuf:"bytes,4,opt,name=boundOrganizationID" json:"boundOrganizationID,omitempty"`
	FileName            *string                 `protobuf:"bytes,5,opt,name=fileName" json:"fileName,omitempty"`
	FileSize            *int64                  `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	MimeType            *string                 `protobuf:"bytes,7,opt,name=mimeType" json:"mimeType,omitempty"`
	DownloadUrl         *string                 `protobuf:"bytes,8,opt,name=downloadUrl" json:"downloadUrl,omitempty"`
	ExpiresAt           *int64                  `protobuf:"varint,9,opt,name=expiresAt" json:"expiresAt,omitempty"`
	UploadedBy          *string                 `protobuf:"bytes,10,opt,name=uploadedBy" json:"uploadedBy,omitempty"`
	CreatedAt           *int64                  `protobuf:"varint,11,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt           *int64                  `protobuf:"varint,12,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (x *OrganizationLogo) Reset() { *x = OrganizationLogo{} }

func (x *OrganizationLogo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OrganizationLogo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OrganizationLogo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrganizationLogo) GetFileID() string {
	if x != nil && x.FileID != nil {
		return *x.FileID
	}
	return ""
}

func (x *OrganizationLogo) GetStatus() OrganizationLogoStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OrganizationLogoStatus_ORGANIZATION_LOGO_STATUS_UNSPECIFIED
}

func (x *OrganizationLogo) GetBoundOrganizationID() string {
	if x != nil && x.BoundOrganizationID != nil {
		return *x.BoundOrganizationID
	}
	return ""
}

func (x *OrganizationLogo) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *OrganizationLogo) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *OrganizationLogo) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *OrganizationLogo) GetDownloadUrl() string {
	if x != nil && x.DownloadUrl != nil {
		return *x.DownloadUrl
	}
	return ""
}

func (x *OrganizationLogo) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *OrganizationLogo) GetUploadedBy() string {
	if x != nil && x.UploadedBy != nil {
		return *x.UploadedBy
	}
	return ""
}

func (x *OrganizationLogo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *OrganizationLogo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

// 权限。
type Permission struct {
	Resource    *string `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Action      *string `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (x *Permission) Reset() { *x = Permission{} }

func (x *Permission) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Permission) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Permission) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// 角色定义。
type RoleDefinition struct {
	Id           *string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         *string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  *string          `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Status       *core.RoleStatus `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	Permissions  []*Permission    `protobuf:"bytes,6,rep,name=permissions" json:"permissions,omitempty"`
	IsSystemRole *bool            `protobuf:"varint,7,opt,name=isSystemRole" json:"isSystemRole,omitempty"`
	CreatedBy    *string          `protobuf:"bytes,8,opt,name=createdBy" json:"createdBy,omitempty"`
	UpdatedBy    *string          `protobuf:"bytes,9,opt,name=updatedBy" json:"updatedBy,omitempty"`
	CreatedAt    *int64           `protobuf:"varint,10,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt    *int64           `protobuf:"varint,11,opt,name=updatedAt" json:"updatedAt,omitempty"`
	UserCount    *int64           `protobuf:"varint,12,opt,name=userCount" json:"userCount,omitempty"`
	RoleCode     *string          `protobuf:"bytes,13,opt,name=roleCode" json:"roleCode,omitempty"`
	ParentRoleID *string          `protobuf:"bytes,14,opt,name=parentRoleID" json:"parentRoleID,omitempty"`
	DepartmentID *string          `protobuf:"bytes,15,opt,name=departmentID" json:"departmentID,omitempty"`
	DefaultScope *DataScope       `protobuf:"varint,16,opt,name=defaultScope" json:"defaultScope,omitempty"`
}

func (x *RoleDefinition) Reset() { *x = RoleDefinition{} }

func (x *RoleDefinition) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RoleDefinition) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RoleDefinition) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RoleDefinition) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RoleDefinition) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RoleDefinition) GetStatus() core.RoleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return core.RoleStatus_ROLE_STATUS_UNSPECIFIED
}

func (x *RoleDefinition) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RoleDefinition) GetIsSystemRole() bool {
	if x != nil && x.IsSystemRole != nil {
		return *x.IsSystemRole
	}
	return false
}

func (x *RoleDefinition) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *RoleDefinition) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *RoleDefinition) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *RoleDefinition) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *RoleDefinition) GetUserCount() int64 {
	if x != nil && x.UserCount != nil {
		return *x.UserCount
	}
	return 0
}

func (x *RoleDefinition) GetRoleCode() string {
	if x != nil && x.RoleCode != nil {
		return *x.RoleCode
	}
	return ""
}

func (x *RoleDefinition) GetParentRoleID() string {
	if x != nil && x.ParentRoleID != nil {
		return *x.ParentRoleID
	}
	return ""
}

func (x *RoleDefinition) GetDepartmentID() string {
	if x != nil && x.DepartmentID != nil {
		return *x.DepartmentID
	}
	return ""
}

func (x *RoleDefinition) GetDefaultScope() DataScope {
	if x != nil && x.DefaultScope != nil {
		return *x.DefaultScope
	}
	return DataScope_DATA_SCOPE_UNSPECIFIED
}

// 用户角色分配。
type UserRoleAssignment struct {
	Id        *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserID    *string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	RoleID    *string `protobuf:"bytes,3,opt,name=roleID" json:"roleID,omitempty"`
	CreatedBy *string `protobuf:"bytes,11,opt,name=createdBy" json:"createdBy,omitempty"`
	UpdatedBy *string `protobuf:"bytes,12,opt,name=updatedBy" json:"updatedBy,omitempty"`
	CreatedAt *int64  `protobuf:"varint,13,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt *int64  `protobuf:"varint,14,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (x *UserRoleAssignment) Reset() { *x = UserRoleAssignment{} }

func (x *UserRoleAssignment) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserRoleAssignment) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserRoleAssignment) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UserRoleAssignment) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *UserRoleAssignment) GetRoleID() string {
	if x != nil && x.RoleID != nil {
		return *x.RoleID
	}
	return ""
}

func (x *UserRoleAssignment) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *UserRoleAssignment) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *UserRoleAssignment) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *UserRoleAssignment) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

// 菜单节点。
type MenuNode struct {
	Name            *string          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id              *string          `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Path            *string          `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Icon            *string          `protobuf:"bytes,4,opt,name=icon" json:"icon,omitempty"`
	Component       *string          `protobuf:"bytes,5,opt,name=component" json:"component,omitempty"`
	Children        []*MenuNode      `protobuf:"bytes,6,rep,name=children" json:"children,omitempty"`
	HasPermission   *bool            `protobuf:"varint,7,opt,name=hasPermission" json:"hasPermission,omitempty"`
	PermissionLevel *PermissionLevel `protobuf:"varint,8,opt,name=permissionLevel" json:"permissionLevel,omitempty"`
}

func (x *MenuNode) Reset() { *x = MenuNode{} }

func (x *MenuNode) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MenuNode) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MenuNode) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MenuNode) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *MenuNode) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *MenuNode) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *MenuNode) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *MenuNode) GetChildren() []*MenuNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *MenuNode) GetHasPermission() bool {
	if x != nil && x.HasPermission != nil {
		return *x.HasPermission
	}
	return false
}

func (x *MenuNode) GetPermissionLevel() PermissionLevel {
	if x != nil && x.PermissionLevel != nil {
		return *x.PermissionLevel
	}
	return PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED
}
