// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package identity_srv

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/kitex_gen/core"
)

type OAuth2ClientType int64

const (
	OAuth2ClientType_CONFIDENTIAL OAuth2ClientType = 1
	OAuth2ClientType_PUBLIC       OAuth2ClientType = 2
)

func (p OAuth2ClientType) String() string {
	switch p {
	case OAuth2ClientType_CONFIDENTIAL:
		return "CONFIDENTIAL"
	case OAuth2ClientType_PUBLIC:
		return "PUBLIC"
	}
	return "<UNSET>"
}

func OAuth2ClientTypeFromString(s string) (OAuth2ClientType, error) {
	switch s {
	case "CONFIDENTIAL":
		return OAuth2ClientType_CONFIDENTIAL, nil
	case "PUBLIC":
		return OAuth2ClientType_PUBLIC, nil
	}
	return OAuth2ClientType(0), fmt.Errorf("not a valid OAuth2ClientType string")
}

func OAuth2ClientTypePtr(v OAuth2ClientType) *OAuth2ClientType { return &v }
func (p *OAuth2ClientType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OAuth2ClientType(result.Int64)
	return
}

func (p *OAuth2ClientType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OAuth2GrantType int64

const (
	OAuth2GrantType_AUTHORIZATION_CODE OAuth2GrantType = 1
	OAuth2GrantType_CLIENT_CREDENTIALS OAuth2GrantType = 2
	OAuth2GrantType_REFRESH_TOKEN      OAuth2GrantType = 3
)

func (p OAuth2GrantType) String() string {
	switch p {
	case OAuth2GrantType_AUTHORIZATION_CODE:
		return "AUTHORIZATION_CODE"
	case OAuth2GrantType_CLIENT_CREDENTIALS:
		return "CLIENT_CREDENTIALS"
	case OAuth2GrantType_REFRESH_TOKEN:
		return "REFRESH_TOKEN"
	}
	return "<UNSET>"
}

func OAuth2GrantTypeFromString(s string) (OAuth2GrantType, error) {
	switch s {
	case "AUTHORIZATION_CODE":
		return OAuth2GrantType_AUTHORIZATION_CODE, nil
	case "CLIENT_CREDENTIALS":
		return OAuth2GrantType_CLIENT_CREDENTIALS, nil
	case "REFRESH_TOKEN":
		return OAuth2GrantType_REFRESH_TOKEN, nil
	}
	return OAuth2GrantType(0), fmt.Errorf("not a valid OAuth2GrantType string")
}

func OAuth2GrantTypePtr(v OAuth2GrantType) *OAuth2GrantType { return &v }
func (p *OAuth2GrantType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OAuth2GrantType(result.Int64)
	return
}

func (p *OAuth2GrantType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OAuth2ResponseType int64

const (
	OAuth2ResponseType_CODE OAuth2ResponseType = 1
)

func (p OAuth2ResponseType) String() string {
	switch p {
	case OAuth2ResponseType_CODE:
		return "CODE"
	}
	return "<UNSET>"
}

func OAuth2ResponseTypeFromString(s string) (OAuth2ResponseType, error) {
	switch s {
	case "CODE":
		return OAuth2ResponseType_CODE, nil
	}
	return OAuth2ResponseType(0), fmt.Errorf("not a valid OAuth2ResponseType string")
}

func OAuth2ResponseTypePtr(v OAuth2ResponseType) *OAuth2ResponseType { return &v }
func (p *OAuth2ResponseType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OAuth2ResponseType(result.Int64)
	return
}

func (p *OAuth2ResponseType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OAuth2Client struct {
	Id                   *core.UUID        `thrift:"id,1,optional" frugal:"1,optional,string" json:"id,omitempty"`
	ClientID             *string           `thrift:"clientID,2,optional" frugal:"2,optional,string" json:"clientID,omitempty"`
	ClientName           *string           `thrift:"clientName,3,optional" frugal:"3,optional,string" json:"clientName,omitempty"`
	Description          *string           `thrift:"description,4,optional" frugal:"4,optional,string" json:"description,omitempty"`
	ClientType           *OAuth2ClientType `thrift:"clientType,5,optional" frugal:"5,optional,OAuth2ClientType" json:"clientType,omitempty"`
	GrantTypes           []OAuth2GrantType `thrift:"grantTypes,6,optional" frugal:"6,optional,list<OAuth2GrantType>" json:"grantTypes,omitempty"`
	RedirectURIs         []string          `thrift:"redirectURIs,7,optional" frugal:"7,optional,list<string>" json:"redirectURIs,omitempty"`
	Scopes               []string          `thrift:"scopes,8,optional" frugal:"8,optional,list<string>" json:"scopes,omitempty"`
	LogoURI              *string           `thrift:"logoURI,9,optional" frugal:"9,optional,string" json:"logoURI,omitempty"`
	ClientURI            *string           `thrift:"clientURI,10,optional" frugal:"10,optional,string" json:"clientURI,omitempty"`
	AccessTokenLifespan  *int32            `thrift:"accessTokenLifespan,11,optional" frugal:"11,optional,i32" json:"accessTokenLifespan,omitempty"`
	RefreshTokenLifespan *int32            `thrift:"refreshTokenLifespan,12,optional" frugal:"12,optional,i32" json:"refreshTokenLifespan,omitempty"`
	IsActive             *bool             `thrift:"isActive,13,optional" frugal:"13,optional,bool" json:"isActive,omitempty"`
	OwnerID              *core.UUID        `thrift:"ownerID,14,optional" frugal:"14,optional,string" json:"ownerID,omitempty"`
	CreatedAt            *core.TimestampMS `thrift:"createdAt,15,optional" frugal:"15,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt            *core.TimestampMS `thrift:"updatedAt,16,optional" frugal:"16,optional,i64" json:"updatedAt,omitempty"`
}

func NewOAuth2Client() *OAuth2Client {
	return &OAuth2Client{}
}

func (p *OAuth2Client) InitDefault() {
}

var OAuth2Client_Id_DEFAULT core.UUID

func (p *OAuth2Client) GetId() (v core.UUID) {
	if !p.IsSetId() {
		return OAuth2Client_Id_DEFAULT
	}
	return *p.Id
}

var OAuth2Client_ClientID_DEFAULT string

func (p *OAuth2Client) GetClientID() (v string) {
	if !p.IsSetClientID() {
		return OAuth2Client_ClientID_DEFAULT
	}
	return *p.ClientID
}

var OAuth2Client_ClientName_DEFAULT string

func (p *OAuth2Client) GetClientName() (v string) {
	if !p.IsSetClientName() {
		return OAuth2Client_ClientName_DEFAULT
	}
	return *p.ClientName
}

var OAuth2Client_Description_DEFAULT string

func (p *OAuth2Client) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return OAuth2Client_Description_DEFAULT
	}
	return *p.Description
}

var OAuth2Client_ClientType_DEFAULT OAuth2ClientType

func (p *OAuth2Client) GetClientType() (v OAuth2ClientType) {
	if !p.IsSetClientType() {
		return OAuth2Client_ClientType_DEFAULT
	}
	return *p.ClientType
}

var OAuth2Client_GrantTypes_DEFAULT []OAuth2GrantType

func (p *OAuth2Client) GetGrantTypes() (v []OAuth2GrantType) {
	if !p.IsSetGrantTypes() {
		return OAuth2Client_GrantTypes_DEFAULT
	}
	return p.GrantTypes
}

var OAuth2Client_RedirectURIs_DEFAULT []string

func (p *OAuth2Client) GetRedirectURIs() (v []string) {
	if !p.IsSetRedirectURIs() {
		return OAuth2Client_RedirectURIs_DEFAULT
	}
	return p.RedirectURIs
}

var OAuth2Client_Scopes_DEFAULT []string

func (p *OAuth2Client) GetScopes() (v []string) {
	if !p.IsSetScopes() {
		return OAuth2Client_Scopes_DEFAULT
	}
	return p.Scopes
}

var OAuth2Client_LogoURI_DEFAULT string

func (p *OAuth2Client) GetLogoURI() (v string) {
	if !p.IsSetLogoURI() {
		return OAuth2Client_LogoURI_DEFAULT
	}
	return *p.LogoURI
}

var OAuth2Client_ClientURI_DEFAULT string

func (p *OAuth2Client) GetClientURI() (v string) {
	if !p.IsSetClientURI() {
		return OAuth2Client_ClientURI_DEFAULT
	}
	return *p.ClientURI
}

var OAuth2Client_AccessTokenLifespan_DEFAULT int32

func (p *OAuth2Client) GetAccessTokenLifespan() (v int32) {
	if !p.IsSetAccessTokenLifespan() {
		return OAuth2Client_AccessTokenLifespan_DEFAULT
	}
	return *p.AccessTokenLifespan
}

var OAuth2Client_RefreshTokenLifespan_DEFAULT int32

func (p *OAuth2Client) GetRefreshTokenLifespan() (v int32) {
	if !p.IsSetRefreshTokenLifespan() {
		return OAuth2Client_RefreshTokenLifespan_DEFAULT
	}
	return *p.RefreshTokenLifespan
}

var OAuth2Client_IsActive_DEFAULT bool

func (p *OAuth2Client) GetIsActive() (v bool) {
	if !p.IsSetIsActive() {
		return OAuth2Client_IsActive_DEFAULT
	}
	return *p.IsActive
}

var OAuth2Client_OwnerID_DEFAULT core.UUID

func (p *OAuth2Client) GetOwnerID() (v core.UUID) {
	if !p.IsSetOwnerID() {
		return OAuth2Client_OwnerID_DEFAULT
	}
	return *p.OwnerID
}

var OAuth2Client_CreatedAt_DEFAULT core.TimestampMS

func (p *OAuth2Client) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return OAuth2Client_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var OAuth2Client_UpdatedAt_DEFAULT core.TimestampMS

func (p *OAuth2Client) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return OAuth2Client_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *OAuth2Client) SetId(val *core.UUID) {
	p.Id = val
}
func (p *OAuth2Client) SetClientID(val *string) {
	p.ClientID = val
}
func (p *OAuth2Client) SetClientName(val *string) {
	p.ClientName = val
}
func (p *OAuth2Client) SetDescription(val *string) {
	p.Description = val
}
func (p *OAuth2Client) SetClientType(val *OAuth2ClientType) {
	p.ClientType = val
}
func (p *OAuth2Client) SetGrantTypes(val []OAuth2GrantType) {
	p.GrantTypes = val
}
func (p *OAuth2Client) SetRedirectURIs(val []string) {
	p.RedirectURIs = val
}
func (p *OAuth2Client) SetScopes(val []string) {
	p.Scopes = val
}
func (p *OAuth2Client) SetLogoURI(val *string) {
	p.LogoURI = val
}
func (p *OAuth2Client) SetClientURI(val *string) {
	p.ClientURI = val
}
func (p *OAuth2Client) SetAccessTokenLifespan(val *int32) {
	p.AccessTokenLifespan = val
}
func (p *OAuth2Client) SetRefreshTokenLifespan(val *int32) {
	p.RefreshTokenLifespan = val
}
func (p *OAuth2Client) SetIsActive(val *bool) {
	p.IsActive = val
}
func (p *OAuth2Client) SetOwnerID(val *core.UUID) {
	p.OwnerID = val
}
func (p *OAuth2Client) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *OAuth2Client) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *OAuth2Client) IsSetId() bool {
	return p.Id != nil
}

func (p *OAuth2Client) IsSetClientID() bool {
	return p.ClientID != nil
}

func (p *OAuth2Client) IsSetClientName() bool {
	return p.ClientName != nil
}

func (p *OAuth2Client) IsSetDescription() bool {
	return p.Description != nil
}

func (p *OAuth2Client) IsSetClientType() bool {
	return p.ClientType != nil
}

func (p *OAuth2Client) IsSetGrantTypes() bool {
	return p.GrantTypes != nil
}

func (p *OAuth2Client) IsSetRedirectURIs() bool {
	return p.RedirectURIs != nil
}

func (p *OAuth2Client) IsSetScopes() bool {
	return p.Scopes != nil
}

func (p *OAuth2Client) IsSetLogoURI() bool {
	return p.LogoURI != nil
}

func (p *OAuth2Client) IsSetClientURI() bool {
	return p.ClientURI != nil
}

func (p *OAuth2Client) IsSetAccessTokenLifespan() bool {
	return p.AccessTokenLifespan != nil
}

func (p *OAuth2Client) IsSetRefreshTokenLifespan() bool {
	return p.RefreshTokenLifespan != nil
}

func (p *OAuth2Client) IsSetIsActive() bool {
	return p.IsActive != nil
}

func (p *OAuth2Client) IsSetOwnerID() bool {
	return p.OwnerID != nil
}

func (p *OAuth2Client) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *OAuth2Client) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *OAuth2Client) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAuth2Client(%+v)", *p)
}

var fieldIDToName_OAuth2Client = map[int16]string{
	1:  "id",
	2:  "clientID",
	3:  "clientName",
	4:  "description",
	5:  "clientType",
	6:  "grantTypes",
	7:  "redirectURIs",
	8:  "scopes",
	9:  "logoURI",
	10: "clientURI",
	11: "accessTokenLifespan",
	12: "refreshTokenLifespan",
	13: "isActive",
	14: "ownerID",
	15: "createdAt",
	16: "updatedAt",
}

type OAuth2Scope struct {
	Id          *core.UUID        `thrift:"id,1,optional" frugal:"1,optional,string" json:"id,omitempty"`
	Name        *string           `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	DisplayName *string           `thrift:"displayName,3,optional" frugal:"3,optional,string" json:"displayName,omitempty"`
	Description *string           `thrift:"description,4,optional" frugal:"4,optional,string" json:"description,omitempty"`
	IsDefault   *bool             `thrift:"isDefault,5,optional" frugal:"5,optional,bool" json:"isDefault,omitempty"`
	IsSystem    *bool             `thrift:"isSystem,6,optional" frugal:"6,optional,bool" json:"isSystem,omitempty"`
	CreatedAt   *core.TimestampMS `thrift:"createdAt,7,optional" frugal:"7,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt   *core.TimestampMS `thrift:"updatedAt,8,optional" frugal:"8,optional,i64" json:"updatedAt,omitempty"`
}

func NewOAuth2Scope() *OAuth2Scope {
	return &OAuth2Scope{}
}

func (p *OAuth2Scope) InitDefault() {
}

var OAuth2Scope_Id_DEFAULT core.UUID

func (p *OAuth2Scope) GetId() (v core.UUID) {
	if !p.IsSetId() {
		return OAuth2Scope_Id_DEFAULT
	}
	return *p.Id
}

var OAuth2Scope_Name_DEFAULT string

func (p *OAuth2Scope) GetName() (v string) {
	if !p.IsSetName() {
		return OAuth2Scope_Name_DEFAULT
	}
	return *p.Name
}

var OAuth2Scope_DisplayName_DEFAULT string

func (p *OAuth2Scope) GetDisplayName() (v string) {
	if !p.IsSetDisplayName() {
		return OAuth2Scope_DisplayName_DEFAULT
	}
	return *p.DisplayName
}

var OAuth2Scope_Description_DEFAULT string

func (p *OAuth2Scope) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return OAuth2Scope_Description_DEFAULT
	}
	return *p.Description
}

var OAuth2Scope_IsDefault_DEFAULT bool

func (p *OAuth2Scope) GetIsDefault() (v bool) {
	if !p.IsSetIsDefault() {
		return OAuth2Scope_IsDefault_DEFAULT
	}
	return *p.IsDefault
}

var OAuth2Scope_IsSystem_DEFAULT bool

func (p *OAuth2Scope) GetIsSystem() (v bool) {
	if !p.IsSetIsSystem() {
		return OAuth2Scope_IsSystem_DEFAULT
	}
	return *p.IsSystem
}

var OAuth2Scope_CreatedAt_DEFAULT core.TimestampMS

func (p *OAuth2Scope) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return OAuth2Scope_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var OAuth2Scope_UpdatedAt_DEFAULT core.TimestampMS

func (p *OAuth2Scope) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return OAuth2Scope_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *OAuth2Scope) SetId(val *core.UUID) {
	p.Id = val
}
func (p *OAuth2Scope) SetName(val *string) {
	p.Name = val
}
func (p *OAuth2Scope) SetDisplayName(val *string) {
	p.DisplayName = val
}
func (p *OAuth2Scope) SetDescription(val *string) {
	p.Description = val
}
func (p *OAuth2Scope) SetIsDefault(val *bool) {
	p.IsDefault = val
}
func (p *OAuth2Scope) SetIsSystem(val *bool) {
	p.IsSystem = val
}
func (p *OAuth2Scope) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *OAuth2Scope) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *OAuth2Scope) IsSetId() bool {
	return p.Id != nil
}

func (p *OAuth2Scope) IsSetName() bool {
	return p.Name != nil
}

func (p *OAuth2Scope) IsSetDisplayName() bool {
	return p.DisplayName != nil
}

func (p *OAuth2Scope) IsSetDescription() bool {
	return p.Description != nil
}

func (p *OAuth2Scope) IsSetIsDefault() bool {
	return p.IsDefault != nil
}

func (p *OAuth2Scope) IsSetIsSystem() bool {
	return p.IsSystem != nil
}

func (p *OAuth2Scope) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *OAuth2Scope) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *OAuth2Scope) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAuth2Scope(%+v)", *p)
}

var fieldIDToName_OAuth2Scope = map[int16]string{
	1: "id",
	2: "name",
	3: "displayName",
	4: "description",
	5: "isDefault",
	6: "isSystem",
	7: "createdAt",
	8: "updatedAt",
}

type OAuth2Consent struct {
	Id         *core.UUID        `thrift:"id,1,optional" frugal:"1,optional,string" json:"id,omitempty"`
	UserID     *core.UUID        `thrift:"userID,2,optional" frugal:"2,optional,string" json:"userID,omitempty"`
	ClientID   *string           `thrift:"clientID,3,optional" frugal:"3,optional,string" json:"clientID,omitempty"`
	ClientName *string           `thrift:"clientName,4,optional" frugal:"4,optional,string" json:"clientName,omitempty"`
	Scopes     []string          `thrift:"scopes,5,optional" frugal:"5,optional,list<string>" json:"scopes,omitempty"`
	GrantedAt  *core.TimestampMS `thrift:"grantedAt,6,optional" frugal:"6,optional,i64" json:"grantedAt,omitempty"`
	ExpiresAt  *core.TimestampMS `thrift:"expiresAt,7,optional" frugal:"7,optional,i64" json:"expiresAt,omitempty"`
	IsRevoked  *bool             `thrift:"isRevoked,8,optional" frugal:"8,optional,bool" json:"isRevoked,omitempty"`
	CreatedAt  *core.TimestampMS `thrift:"createdAt,9,optional" frugal:"9,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt  *core.TimestampMS `thrift:"updatedAt,10,optional" frugal:"10,optional,i64" json:"updatedAt,omitempty"`
}

func NewOAuth2Consent() *OAuth2Consent {
	return &OAuth2Consent{}
}

func (p *OAuth2Consent) InitDefault() {
}

var OAuth2Consent_Id_DEFAULT core.UUID

func (p *OAuth2Consent) GetId() (v core.UUID) {
	if !p.IsSetId() {
		return OAuth2Consent_Id_DEFAULT
	}
	return *p.Id
}

var OAuth2Consent_UserID_DEFAULT core.UUID

func (p *OAuth2Consent) GetUserID() (v core.UUID) {
	if !p.IsSetUserID() {
		return OAuth2Consent_UserID_DEFAULT
	}
	return *p.UserID
}

var OAuth2Consent_ClientID_DEFAULT string

func (p *OAuth2Consent) GetClientID() (v string) {
	if !p.IsSetClientID() {
		return OAuth2Consent_ClientID_DEFAULT
	}
	return *p.ClientID
}

var OAuth2Consent_ClientName_DEFAULT string

func (p *OAuth2Consent) GetClientName() (v string) {
	if !p.IsSetClientName() {
		return OAuth2Consent_ClientName_DEFAULT
	}
	return *p.ClientName
}

var OAuth2Consent_Scopes_DEFAULT []string

func (p *OAuth2Consent) GetScopes() (v []string) {
	if !p.IsSetScopes() {
		return OAuth2Consent_Scopes_DEFAULT
	}
	return p.Scopes
}

var OAuth2Consent_GrantedAt_DEFAULT core.TimestampMS

func (p *OAuth2Consent) GetGrantedAt() (v core.TimestampMS) {
	if !p.IsSetGrantedAt() {
		return OAuth2Consent_GrantedAt_DEFAULT
	}
	return *p.GrantedAt
}

var OAuth2Consent_ExpiresAt_DEFAULT core.TimestampMS

func (p *OAuth2Consent) GetExpiresAt() (v core.TimestampMS) {
	if !p.IsSetExpiresAt() {
		return OAuth2Consent_ExpiresAt_DEFAULT
	}
	return *p.ExpiresAt
}

var OAuth2Consent_IsRevoked_DEFAULT bool

func (p *OAuth2Consent) GetIsRevoked() (v bool) {
	if !p.IsSetIsRevoked() {
		return OAuth2Consent_IsRevoked_DEFAULT
	}
	return *p.IsRevoked
}

var OAuth2Consent_CreatedAt_DEFAULT core.TimestampMS

func (p *OAuth2Consent) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return OAuth2Consent_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var OAuth2Consent_UpdatedAt_DEFAULT core.TimestampMS

func (p *OAuth2Consent) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return OAuth2Consent_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *OAuth2Consent) SetId(val *core.UUID) {
	p.Id = val
}
func (p *OAuth2Consent) SetUserID(val *core.UUID) {
	p.UserID = val
}
func (p *OAuth2Consent) SetClientID(val *string) {
	p.ClientID = val
}
func (p *OAuth2Consent) SetClientName(val *string) {
	p.ClientName = val
}
func (p *OAuth2Consent) SetScopes(val []string) {
	p.Scopes = val
}
func (p *OAuth2Consent) SetGrantedAt(val *core.TimestampMS) {
	p.GrantedAt = val
}
func (p *OAuth2Consent) SetExpiresAt(val *core.TimestampMS) {
	p.ExpiresAt = val
}
func (p *OAuth2Consent) SetIsRevoked(val *bool) {
	p.IsRevoked = val
}
func (p *OAuth2Consent) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *OAuth2Consent) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *OAuth2Consent) IsSetId() bool {
	return p.Id != nil
}

func (p *OAuth2Consent) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *OAuth2Consent) IsSetClientID() bool {
	return p.ClientID != nil
}

func (p *OAuth2Consent) IsSetClientName() bool {
	return p.ClientName != nil
}

func (p *OAuth2Consent) IsSetScopes() bool {
	return p.Scopes != nil
}

func (p *OAuth2Consent) IsSetGrantedAt() bool {
	return p.GrantedAt != nil
}

func (p *OAuth2Consent) IsSetExpiresAt() bool {
	return p.ExpiresAt != nil
}

func (p *OAuth2Consent) IsSetIsRevoked() bool {
	return p.IsRevoked != nil
}

func (p *OAuth2Consent) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *OAuth2Consent) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *OAuth2Consent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAuth2Consent(%+v)", *p)
}

var fieldIDToName_OAuth2Consent = map[int16]string{
	1:  "id",
	2:  "userID",
	3:  "clientID",
	4:  "clientName",
	5:  "scopes",
	6:  "grantedAt",
	7:  "expiresAt",
	8:  "isRevoked",
	9:  "createdAt",
	10: "updatedAt",
}
