// Code generated by Kitex v0.16.1. DO NOT EDIT.

package core

import "github.com/cloudwego/prutal"

// Common wrapper for map presence.
type StringMapValue struct {
	Entries map[string]string `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *StringMapValue) Reset() { *x = StringMapValue{} }

func (x *StringMapValue) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *StringMapValue) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *StringMapValue) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Common wrapper for repeated string presence.
type StringListValue struct {
	Items []string `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (x *StringListValue) Reset() { *x = StringListValue{} }

func (x *StringListValue) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *StringListValue) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *StringListValue) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// RequestContext carries core request metadata.
type RequestContext struct {
	RequestID      *string         `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
	TraceID        *string         `protobuf:"bytes,2,opt,name=traceID" json:"traceID,omitempty"`
	RequestTime    *int64          `protobuf:"varint,3,opt,name=requestTime" json:"requestTime,omitempty"`
	ClientIP       *string         `protobuf:"bytes,4,opt,name=clientIP" json:"clientIP,omitempty"`
	UserAgent      *string         `protobuf:"bytes,5,opt,name=userAgent" json:"userAgent,omitempty"`
	UserID         *string         `protobuf:"bytes,6,opt,name=userID" json:"userID,omitempty"`
	OrganizationID *string         `protobuf:"bytes,7,opt,name=organizationID" json:"organizationID,omitempty"`
	TenantID       *string         `protobuf:"bytes,8,opt,name=tenantID" json:"tenantID,omitempty"`
	Source         *string         `protobuf:"bytes,9,opt,name=source" json:"source,omitempty"`
	Locale         *string         `protobuf:"bytes,10,opt,name=locale" json:"locale,omitempty"`
	Metadata       *StringMapValue `protobuf:"bytes,11,opt,name=metadata" json:"metadata,omitempty"`
}

func (x *RequestContext) Reset() { *x = RequestContext{} }

func (x *RequestContext) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RequestContext) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RequestContext) GetRequestID() string {
	if x != nil && x.RequestID != nil {
		return *x.RequestID
	}
	return ""
}

func (x *RequestContext) GetTraceID() string {
	if x != nil && x.TraceID != nil {
		return *x.TraceID
	}
	return ""
}

func (x *RequestContext) GetRequestTime() int64 {
	if x != nil && x.RequestTime != nil {
		return *x.RequestTime
	}
	return 0
}

func (x *RequestContext) GetClientIP() string {
	if x != nil && x.ClientIP != nil {
		return *x.ClientIP
	}
	return ""
}

func (x *RequestContext) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *RequestContext) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *RequestContext) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *RequestContext) GetTenantID() string {
	if x != nil && x.TenantID != nil {
		return *x.TenantID
	}
	return ""
}

func (x *RequestContext) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *RequestContext) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *RequestContext) GetMetadata() *StringMapValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}
