// Code generated by Kitex v0.16.1. DO NOT EDIT.

package core

import "strconv"

// User account status.
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_INACTIVE    UserStatus = 2
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 3
	UserStatus_USER_STATUS_LOCKED      UserStatus = 4
)

// Enum value maps for UserStatus.
var UserStatus_name = map[int32]string{
	0: "USER_STATUS_UNSPECIFIED",
	1: "USER_STATUS_ACTIVE",
	2: "USER_STATUS_INACTIVE",
	3: "USER_STATUS_SUSPENDED",
	4: "USER_STATUS_LOCKED",
}

var UserStatus_value = map[string]int32{
	"USER_STATUS_UNSPECIFIED": 0,
	"USER_STATUS_ACTIVE":      1,
	"USER_STATUS_INACTIVE":    2,
	"USER_STATUS_SUSPENDED":   3,
	"USER_STATUS_LOCKED":      4,
}

func (x UserStatus) String() string {
	s, ok := UserStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// Role definition status.
type RoleStatus int32

const (
	RoleStatus_ROLE_STATUS_UNSPECIFIED RoleStatus = 0
	RoleStatus_ROLE_STATUS_ACTIVE      RoleStatus = 1
	RoleStatus_ROLE_STATUS_INACTIVE    RoleStatus = 2
	RoleStatus_ROLE_STATUS_DEPRECATED  RoleStatus = 3
)

// Enum value maps for RoleStatus.
var RoleStatus_name = map[int32]string{
	0: "ROLE_STATUS_UNSPECIFIED",
	1: "ROLE_STATUS_ACTIVE",
	2: "ROLE_STATUS_INACTIVE",
	3: "ROLE_STATUS_DEPRECATED",
}

var RoleStatus_value = map[string]int32{
	"ROLE_STATUS_UNSPECIFIED": 0,
	"ROLE_STATUS_ACTIVE":      1,
	"ROLE_STATUS_INACTIVE":    2,
	"ROLE_STATUS_DEPRECATED":  3,
}

func (x RoleStatus) String() string {
	s, ok := RoleStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// Gender zero value follows protobuf UNSPECIFIED convention.
type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var Gender_name = map[int32]string{
	0: "GENDER_UNSPECIFIED",
	1: "GENDER_MALE",
	2: "GENDER_FEMALE",
}

var Gender_value = map[string]int32{
	"GENDER_UNSPECIFIED": 0,
	"GENDER_MALE":        1,
	"GENDER_FEMALE":      2,
}

func (x Gender) String() string {
	s, ok := Gender_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
