// Code generated by Kitex v0.16.1. DO NOT EDIT.

package policy_srv

import "github.com/cloudwego/prutal"

// Subject 权限检查的主体（谁在操作）
type Subject struct {
	UserId     string            `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`                                                                                 // sub (UUID)
	Tenant     string            `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`                                                                                   // tenant = OrganizationID
	Roles      []string          `protobuf:"bytes,3,rep,name=roles" json:"roles,omitempty"`                                                                                     // 角色 code 列表
	Attributes map[string]string `protobuf:"bytes,4,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 业务侧注入的额外属性（部门等）
}

func (x *Subject) Reset() { *x = Subject{} }

func (x *Subject) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Subject) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Subject) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subject) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Subject) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Subject) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// CheckRequest 单点权限检查请求
type CheckRequest struct {
	Subject            *Subject          `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Action             string            `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`                                                                                                     // e.g. "read", "write", "approve"
	Resource           string            `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`                                                                                                 // e.g. "patient:7a3e..." 或 "patient.*"
	ResourceAttributes map[string]string `protobuf:"bytes,4,rep,name=resource_attributes" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 资源属性（owner_id 等）
}

func (x *CheckRequest) Reset() { *x = CheckRequest{} }

func (x *CheckRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

// CheckResponse 单点权限检查响应
type CheckResponse struct {
	Allowed       bool   `protobuf:"varint,1,opt,name=allowed" json:"allowed,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`                   // 拒绝原因（仅 debug）
	DataScopeHint string `protobuf:"bytes,3,opt,name=data_scope_hint" json:"data_scope_hint,omitempty"` // 数据范围提示（可选）
}

func (x *CheckResponse) Reset() { *x = CheckResponse{} }

func (x *CheckResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckResponse) GetDataScopeHint() string {
	if x != nil {
		return x.DataScopeHint
	}
	return ""
}

// BatchCheckRequest 批量权限检查请求
type BatchCheckRequest struct {
	Subject *Subject     `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Items   []*CheckItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *BatchCheckRequest) Reset() { *x = BatchCheckRequest{} }

func (x *BatchCheckRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BatchCheckRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchCheckRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *BatchCheckRequest) GetItems() []*CheckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckItem struct {
	Action             string            `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Resource           string            `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	ResourceAttributes map[string]string `protobuf:"bytes,3,rep,name=resource_attributes" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *CheckItem) Reset() { *x = CheckItem{} }

func (x *CheckItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckItem) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckItem) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

// BatchCheckResponse 批量权限检查响应
type BatchCheckResponse struct {
	Results []*CheckResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *BatchCheckResponse) Reset() { *x = BatchCheckResponse{} }

func (x *BatchCheckResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BatchCheckResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchCheckResponse) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CheckResult struct {
	Action   string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	Allowed  bool   `protobuf:"varint,3,opt,name=allowed" json:"allowed,omitempty"`
	Reason   string `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
}

func (x *CheckResult) Reset() { *x = CheckResult{} }

func (x *CheckResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckResult) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ListPermissionsRequest 查询主体所有权限
type ListPermissionsRequest struct {
	Subject *Subject `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
}

func (x *ListPermissionsRequest) Reset() { *x = ListPermissionsRequest{} }

func (x *ListPermissionsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListPermissionsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPermissionsRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

// ListPermissionsResponse 查询主体所有权限响应
type ListPermissionsResponse struct {
	Permissions []*PermissionItem `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (x *ListPermissionsResponse) Reset() { *x = ListPermissionsResponse{} }

func (x *ListPermissionsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListPermissionsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPermissionsResponse) GetPermissions() []*PermissionItem {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PermissionItem struct {
	Resource  string `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Action    string `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	DataScope string `protobuf:"bytes,3,opt,name=data_scope" json:"data_scope,omitempty"`
}

func (x *PermissionItem) Reset() { *x = PermissionItem{} }

func (x *PermissionItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PermissionItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PermissionItem) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionItem) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

// UpsertPolicyRequest 策略创建/更新请求
type UpsertPolicyRequest struct {
	Ptype string   `protobuf:"bytes,1,opt,name=ptype" json:"ptype,omitempty"` // p / g / g2
	Rule  []string `protobuf:"bytes,2,rep,name=rule" json:"rule,omitempty"`   // 策略规则项
}

func (x *UpsertPolicyRequest) Reset() { *x = UpsertPolicyRequest{} }

func (x *UpsertPolicyRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpsertPolicyRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpsertPolicyRequest) GetPtype() string {
	if x != nil {
		return x.Ptype
	}
	return ""
}

func (x *UpsertPolicyRequest) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

// UpsertPolicyResponse 策略创建/更新响应
type UpsertPolicyResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *UpsertPolicyResponse) Reset() { *x = UpsertPolicyResponse{} }

func (x *UpsertPolicyResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpsertPolicyResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpsertPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeletePolicyRequest 策略删除请求
type DeletePolicyRequest struct {
	Ptype string   `protobuf:"bytes,1,opt,name=ptype" json:"ptype,omitempty"` // p / g / g2
	Rule  []string `protobuf:"bytes,2,rep,name=rule" json:"rule,omitempty"`   // 策略规则项
}

func (x *DeletePolicyRequest) Reset() { *x = DeletePolicyRequest{} }

func (x *DeletePolicyRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeletePolicyRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePolicyRequest) GetPtype() string {
	if x != nil {
		return x.Ptype
	}
	return ""
}

func (x *DeletePolicyRequest) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

// DeletePolicyResponse 策略删除响应
type DeletePolicyResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *DeletePolicyResponse) Reset() { *x = DeletePolicyResponse{} }

func (x *DeletePolicyResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeletePolicyResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ReloadPoliciesRequest 策略重载请求
type ReloadPoliciesRequest struct {
}

func (x *ReloadPoliciesRequest) Reset() { *x = ReloadPoliciesRequest{} }

func (x *ReloadPoliciesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ReloadPoliciesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

// ReloadPoliciesResponse 策略重载响应
type ReloadPoliciesResponse struct {
	Success              bool  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	PolicyCount          int32 `protobuf:"varint,2,opt,name=policy_count" json:"policy_count,omitempty"`
	GroupingPolicyCount  int32 `protobuf:"varint,3,opt,name=grouping_policy_count" json:"grouping_policy_count,omitempty"`
	RoleInheritanceCount int32 `protobuf:"varint,4,opt,name=role_inheritance_count" json:"role_inheritance_count,omitempty"`
}

func (x *ReloadPoliciesResponse) Reset() { *x = ReloadPoliciesResponse{} }

func (x *ReloadPoliciesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ReloadPoliciesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReloadPoliciesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadPoliciesResponse) GetPolicyCount() int32 {
	if x != nil {
		return x.PolicyCount
	}
	return 0
}

func (x *ReloadPoliciesResponse) GetGroupingPolicyCount() int32 {
	if x != nil {
		return x.GroupingPolicyCount
	}
	return 0
}

func (x *ReloadPoliciesResponse) GetRoleInheritanceCount() int32 {
	if x != nil {
		return x.RoleInheritanceCount
	}
	return 0
}
