// Code generated by Kitex v0.16.1. DO NOT EDIT.

package policy_srv

import "context"

type PolicyService interface {
	Check(ctx context.Context, req *CheckRequest) (res *CheckResponse, err error)
	BatchCheck(ctx context.Context, req *BatchCheckRequest) (res *BatchCheckResponse, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest) (res *ListPermissionsResponse, err error)
	UpsertPolicy(ctx context.Context, req *UpsertPolicyRequest) (res *UpsertPolicyResponse, err error)
	DeletePolicy(ctx context.Context, req *DeletePolicyRequest) (res *DeletePolicyResponse, err error)
	ReloadPolicies(ctx context.Context, req *ReloadPoliciesRequest) (res *ReloadPoliciesResponse, err error)
}
