// Code generated by hertz generator.

package identity

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	http_base "github.com/masonsxu/cloudwego-microservice-demo/gateway/biz/model/http_base"
	identity "github.com/masonsxu/cloudwego-microservice-demo/gateway/biz/model/identity"
)

// Login .
// @router /api/v1/identity/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.LoginRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.LoginResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// Logout .
// @router /api/v1/identity/auth/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.LogoutRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ChangePassword .
// @router /api/v1/identity/auth/password [PUT]
func ChangePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ChangePasswordRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ResetPassword .
// @router /api/v1/identity/auth/password/reset [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ResetPasswordRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ForcePasswordChange .
// @router /api/v1/identity/auth/password/force-change [PUT]
func ForcePasswordChange(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ForcePasswordChangeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// RefreshToken .
// @router /api/v1/identity/auth/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.RefreshTokenRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.RefreshTokenResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// CreateUser .
// @router /api/v1/identity/users [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.CreateUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.UserProfileResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetUser .
// @router /api/v1/identity/users/:userID [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.UserProfileResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetMe .
// @router /api/v1/identity/users/me [GET]
func GetMe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetMeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.UserProfileResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UpdateUser .
// @router /api/v1/identity/users/:userID [PUT]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.UserProfileResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UpdateMe .
// @router /api/v1/identity/users/me [PUT]
func UpdateMe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateMeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.UserProfileResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// DeleteUser .
// @router /api/v1/identity/users/:userID [DELETE]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ListUsers .
// @router /api/v1/identity/users [GET]
func ListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ListUsersRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.ListUsersResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// SearchUsers .
// @router /api/v1/identity/users/search [GET]
func SearchUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.SearchUsersRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.SearchUsersResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ChangeUserStatus .
// @router /api/v1/identity/users/:userID/status [PUT]
func ChangeUserStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ChangeUserStatusRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UnlockUser .
// @router /api/v1/identity/users/:userID/unlock [PUT]
func UnlockUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UnlockUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetUserMemberships .
// @router /api/v1/identity/users/:userID/memberships [GET]
func GetUserMemberships(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetUserMembershipsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.GetUserMembershipsResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetPrimaryMembership .
// @router /api/v1/identity/users/:userID/primary-membership [GET]
func GetPrimaryMembership(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetPrimaryMembershipRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.UserMembershipResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// CreateOrganization .
// @router /api/v1/identity/organizations [POST]
func CreateOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.CreateOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.OrganizationResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetOrganization .
// @router /api/v1/identity/organizations/:organizationID [GET]
func GetOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.OrganizationResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UpdateOrganization .
// @router /api/v1/identity/organizations/:organizationID [PUT]
func UpdateOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.OrganizationResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// DeleteOrganization .
// @router /api/v1/identity/organizations/:organizationID [DELETE]
func DeleteOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ListOrganizations .
// @router /api/v1/identity/organizations [GET]
func ListOrganizations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ListOrganizationsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.ListOrganizationsResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// CreateDepartment .
// @router /api/v1/identity/departments [POST]
func CreateDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.CreateDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.DepartmentResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetDepartment .
// @router /api/v1/identity/departments/:departmentID [GET]
func GetDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.DepartmentResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UpdateDepartment .
// @router /api/v1/identity/departments/:departmentID [PUT]
func UpdateDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.DepartmentResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// DeleteDepartment .
// @router /api/v1/identity/departments/:departmentID [DELETE]
func DeleteDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetOrganizationDepartments .
// @router /api/v1/identity/organizations/:organizationID/departments [GET]
func GetOrganizationDepartments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetOrganizationDepartmentsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.GetOrganizationDepartmentsResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// UploadTemporaryLogo .
// @router /api/v1/identity/organization-logos/temporary [POST]
func UploadTemporaryLogo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UploadTemporaryLogoRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.OrganizationLogoResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// GetOrganizationLogo .
// @router /api/v1/identity/organization-logos/:logoID [GET]
func GetOrganizationLogo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetOrganizationLogoRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.OrganizationLogoResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// DeleteOrganizationLogo .
// @router /api/v1/identity/organization-logos/:logoID [DELETE]
func DeleteOrganizationLogo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteOrganizationLogoRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http_base.OperationStatusResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// BindLogoToOrganization .
// @router /api/v1/identity/organizations/:organizationID/logo [PUT]
func BindLogoToOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.BindLogoToOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.OrganizationResponseDTO)

	c.JSON(consts.StatusOK, resp)
}

// ListAuditLogs .
// @router /api/v1/identity/audit-logs [GET]
func ListAuditLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ListAuditLogsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(identity.ListAuditLogsResponseDTO)

	c.JSON(consts.StatusOK, resp)
}
