// Code generated by Kitex v0.16.1. DO NOT EDIT.

package identityservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	identity_srv "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/kitex_gen/identity_srv"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, Req *identity_srv.LoginRequest, callOptions ...callopt.Option) (r *identity_srv.LoginResponse, err error)
	ChangePassword(ctx context.Context, Req *identity_srv.ChangePasswordRequest, callOptions ...callopt.Option) (r *identity_srv.ChangePasswordResponse, err error)
	ResetPassword(ctx context.Context, Req *identity_srv.ResetPasswordRequest, callOptions ...callopt.Option) (r *identity_srv.ResetPasswordResponse, err error)
	ForcePasswordChange(ctx context.Context, Req *identity_srv.ForcePasswordChangeRequest, callOptions ...callopt.Option) (r *identity_srv.ForcePasswordChangeResponse, err error)
	CreateUser(ctx context.Context, Req *identity_srv.CreateUserRequest, callOptions ...callopt.Option) (r *identity_srv.CreateUserResponse, err error)
	GetUser(ctx context.Context, Req *identity_srv.GetUserRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserResponse, err error)
	UpdateUser(ctx context.Context, Req *identity_srv.UpdateUserRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateUserResponse, err error)
	DeleteUser(ctx context.Context, Req *identity_srv.DeleteUserRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteUserResponse, err error)
	ListUsers(ctx context.Context, Req *identity_srv.ListUsersRequest, callOptions ...callopt.Option) (r *identity_srv.ListUsersResponse, err error)
	SearchUsers(ctx context.Context, Req *identity_srv.SearchUsersRequest, callOptions ...callopt.Option) (r *identity_srv.SearchUsersResponse, err error)
	ChangeUserStatus(ctx context.Context, Req *identity_srv.ChangeUserStatusRequest, callOptions ...callopt.Option) (r *identity_srv.ChangeUserStatusResponse, err error)
	UnlockUser(ctx context.Context, Req *identity_srv.UnlockUserRequest, callOptions ...callopt.Option) (r *identity_srv.UnlockUserResponse, err error)
	CreateOrganization(ctx context.Context, Req *identity_srv.CreateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.CreateOrganizationResponse, err error)
	GetOrganization(ctx context.Context, Req *identity_srv.GetOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationResponse, err error)
	UpdateOrganization(ctx context.Context, Req *identity_srv.UpdateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateOrganizationResponse, err error)
	DeleteOrganization(ctx context.Context, Req *identity_srv.DeleteOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOrganizationResponse, err error)
	ListOrganizations(ctx context.Context, Req *identity_srv.ListOrganizationsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOrganizationsResponse, err error)
	AddMembership(ctx context.Context, Req *identity_srv.AddMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.AddMembershipResponse, err error)
	UpdateMembership(ctx context.Context, Req *identity_srv.UpdateMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateMembershipResponse, err error)
	RemoveMembership(ctx context.Context, Req *identity_srv.RemoveMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.RemoveMembershipResponse, err error)
	GetMembership(ctx context.Context, Req *identity_srv.GetMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.GetMembershipResponse, err error)
	GetUserMemberships(ctx context.Context, Req *identity_srv.GetUserMembershipsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMembershipsResponse, err error)
	GetPrimaryMembership(ctx context.Context, Req *identity_srv.GetPrimaryMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.GetPrimaryMembershipResponse, err error)
	CheckMembership(ctx context.Context, Req *identity_srv.CheckMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.CheckMembershipResponse, err error)
	CreateDepartment(ctx context.Context, Req *identity_srv.CreateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.CreateDepartmentResponse, err error)
	GetDepartment(ctx context.Context, Req *identity_srv.GetDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.GetDepartmentResponse, err error)
	UpdateDepartment(ctx context.Context, Req *identity_srv.UpdateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateDepartmentResponse, err error)
	DeleteDepartment(ctx context.Context, Req *identity_srv.DeleteDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteDepartmentResponse, err error)
	GetOrganizationDepartments(ctx context.Context, Req *identity_srv.GetOrganizationDepartmentsRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationDepartmentsResponse, err error)
	UploadTemporaryLogo(ctx context.Context, Req *identity_srv.UploadTemporaryLogoRequest, callOptions ...callopt.Option) (r *identity_srv.UploadTemporaryLogoResponse, err error)
	GetOrganizationLogo(ctx context.Context, Req *identity_srv.GetOrganizationLogoRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationLogoResponse, err error)
	DeleteOrganizationLogo(ctx context.Context, Req *identity_srv.DeleteOrganizationLogoRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOrganizationLogoResponse, err error)
	BindLogoToOrganization(ctx context.Context, Req *identity_srv.BindLogoToOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.BindLogoToOrganizationResponse, err error)
	CreateRoleDefinition(ctx context.Context, Req *identity_srv.RoleDefinitionCreateRequest, callOptions ...callopt.Option) (r *identity_srv.CreateRoleDefinitionResponse, err error)
	UpdateRoleDefinition(ctx context.Context, Req *identity_srv.RoleDefinitionUpdateRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateRoleDefinitionResponse, err error)
	DeleteRoleDefinition(ctx context.Context, Req *identity_srv.DeleteRoleDefinitionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteRoleDefinitionResponse, err error)
	GetRoleDefinition(ctx context.Context, Req *identity_srv.GetRoleDefinitionRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleDefinitionResponse, err error)
	ListRoleDefinitions(ctx context.Context, Req *identity_srv.RoleDefinitionQueryRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinitionListResponse, err error)
	AssignRoleToUser(ctx context.Context, Req *identity_srv.AssignRoleToUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleAssignmentResponse, err error)
	UpdateUserRoleAssignment(ctx context.Context, Req *identity_srv.UpdateUserRoleAssignmentRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateUserRoleAssignmentResponse, err error)
	RevokeRoleFromUser(ctx context.Context, Req *identity_srv.RevokeRoleFromUserRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeRoleFromUserResponse, err error)
	GetLastUserRoleAssignment(ctx context.Context, Req *identity_srv.GetLastUserRoleAssignmentRequest, callOptions ...callopt.Option) (r *identity_srv.GetLastUserRoleAssignmentResponse, err error)
	ListUserRoleAssignments(ctx context.Context, Req *identity_srv.UserRoleQueryRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleListResponse, err error)
	GetUsersByRole(ctx context.Context, Req *identity_srv.GetUsersByRoleRequest, callOptions ...callopt.Option) (r *identity_srv.GetUsersByRoleResponse, err error)
	BatchBindUsersToRole(ctx context.Context, Req *identity_srv.BatchBindUsersToRoleRequest, callOptions ...callopt.Option) (r *identity_srv.BatchBindUsersToRoleResponse, err error)
	BatchGetUserRoles(ctx context.Context, Req *identity_srv.BatchGetUserRolesRequest, callOptions ...callopt.Option) (r *identity_srv.BatchGetUserRolesResponse, err error)
	UploadMenu(ctx context.Context, Req *identity_srv.UploadMenuRequest, callOptions ...callopt.Option) (r *identity_srv.UploadMenuResponse, err error)
	GetMenuTree(ctx context.Context, Req *identity_srv.GetMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetMenuTreeResponse, err error)
	ConfigureRoleMenus(ctx context.Context, Req *identity_srv.ConfigureRoleMenusRequest, callOptions ...callopt.Option) (r *identity_srv.ConfigureRoleMenusResponse, err error)
	GetRoleMenuTree(ctx context.Context, Req *identity_srv.GetRoleMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuTreeResponse, err error)
	GetUserMenuTree(ctx context.Context, Req *identity_srv.GetUserMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuTreeResponse, err error)
	GetRoleMenuPermissions(ctx context.Context, Req *identity_srv.GetRoleMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuPermissionsResponse, err error)
	HasMenuPermission(ctx context.Context, Req *identity_srv.HasMenuPermissionRequest, callOptions ...callopt.Option) (r *identity_srv.HasMenuPermissionResponse, err error)
	GetUserMenuPermissions(ctx context.Context, Req *identity_srv.GetUserMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuPermissionsResponse, err error)
	CheckPermission(ctx context.Context, Req *identity_srv.CheckPermissionRequest, callOptions ...callopt.Option) (r *identity_srv.CheckPermissionResponse, err error)
	SyncPolicies(ctx context.Context, Req *identity_srv.SyncPoliciesRequest, callOptions ...callopt.Option) (r *identity_srv.SyncPoliciesResponse, err error)
	GetUserDataScope(ctx context.Context, Req *identity_srv.GetUserDataScopeRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserDataScopeResponse, err error)
	CreateAuditLog(ctx context.Context, Req *identity_srv.CreateAuditLogRequest, callOptions ...callopt.Option) (r *identity_srv.CreateAuditLogResponse, err error)
	ListAuditLogs(ctx context.Context, Req *identity_srv.ListAuditLogsRequest, callOptions ...callopt.Option) (r *identity_srv.ListAuditLogsResponse, err error)
	CreateOAuth2Client(ctx context.Context, Req *identity_srv.CreateOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2ClientResponse, err error)
	GetOAuth2Client(ctx context.Context, Req *identity_srv.GetOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2Client, err error)
	UpdateOAuth2Client(ctx context.Context, Req *identity_srv.UpdateOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2Client, err error)
	DeleteOAuth2Client(ctx context.Context, Req *identity_srv.DeleteOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2ClientResponse, err error)
	ListOAuth2Clients(ctx context.Context, Req *identity_srv.ListOAuth2ClientsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOAuth2ClientsResponse, err error)
	RotateOAuth2ClientSecret(ctx context.Context, Req *identity_srv.RotateOAuth2ClientSecretRequest, callOptions ...callopt.Option) (r *identity_srv.RotateOAuth2ClientSecretResponse, err error)
	GetOAuth2ClientForAuth(ctx context.Context, Req *identity_srv.GetOAuth2ClientForAuthRequest, callOptions ...callopt.Option) (r *identity_srv.GetOAuth2ClientForAuthResponse, err error)
	ListOAuth2Scopes(ctx context.Context, Req *identity_srv.ListOAuth2ScopesRequest, callOptions ...callopt.Option) (r *identity_srv.ListOAuth2ScopesResponse, err error)
	SaveOAuth2Consent(ctx context.Context, Req *identity_srv.SaveOAuth2ConsentRequest, callOptions ...callopt.Option) (r *identity_srv.SaveOAuth2ConsentResponse, err error)
	GetOAuth2Consent(ctx context.Context, Req *identity_srv.GetOAuth2ConsentRequest, callOptions ...callopt.Option) (r *identity_srv.GetOAuth2ConsentResponse, err error)
	ListOAuth2Consents(ctx context.Context, Req *identity_srv.ListOAuth2ConsentsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOAuth2ConsentsResponse, err error)
	RevokeOAuth2Consent(ctx context.Context, Req *identity_srv.RevokeOAuth2ConsentRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeOAuth2ConsentResponse, err error)
	CreateOAuth2AuthorizeCodeSession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2AuthorizeCodeSessionResponse, err error)
	GetOAuth2AuthorizeCodeSession(ctx context.Context, Req *identity_srv.GetOAuth2AuthorizeCodeSessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error)
	InvalidateOAuth2AuthorizeCodeSession(ctx context.Context, Req *identity_srv.InvalidateOAuth2AuthorizeCodeSessionRequest, callOptions ...callopt.Option) (r *identity_srv.InvalidateOAuth2AuthorizeCodeSessionResponse, err error)
	CreateOAuth2AccessTokenSession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2AccessTokenSessionResponse, err error)
	GetOAuth2AccessTokenSession(ctx context.Context, Req *identity_srv.GetOAuth2AccessTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error)
	DeleteOAuth2AccessTokenSession(ctx context.Context, Req *identity_srv.DeleteOAuth2AccessTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2AccessTokenSessionResponse, err error)
	RevokeOAuth2AccessToken(ctx context.Context, Req *identity_srv.RevokeOAuth2AccessTokenRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeOAuth2AccessTokenResponse, err error)
	CreateOAuth2RefreshTokenSession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2RefreshTokenSessionResponse, err error)
	GetOAuth2RefreshTokenSession(ctx context.Context, Req *identity_srv.GetOAuth2RefreshTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error)
	DeleteOAuth2RefreshTokenSession(ctx context.Context, Req *identity_srv.DeleteOAuth2RefreshTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2RefreshTokenSessionResponse, err error)
	RevokeOAuth2RefreshToken(ctx context.Context, Req *identity_srv.RevokeOAuth2RefreshTokenRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeOAuth2RefreshTokenResponse, err error)
	CreateOAuth2PKCESession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2PKCESessionResponse, err error)
	GetOAuth2PKCESession(ctx context.Context, Req *identity_srv.GetOAuth2PKCESessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error)
	DeleteOAuth2PKCESession(ctx context.Context, Req *identity_srv.DeleteOAuth2PKCESessionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2PKCESessionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kIdentityServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIdentityServiceClient struct {
	*kClient
}

func (p *kIdentityServiceClient) Login(ctx context.Context, Req *identity_srv.LoginRequest, callOptions ...callopt.Option) (r *identity_srv.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kIdentityServiceClient) ChangePassword(ctx context.Context, Req *identity_srv.ChangePasswordRequest, callOptions ...callopt.Option) (r *identity_srv.ChangePasswordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, Req)
}

func (p *kIdentityServiceClient) ResetPassword(ctx context.Context, Req *identity_srv.ResetPasswordRequest, callOptions ...callopt.Option) (r *identity_srv.ResetPasswordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetPassword(ctx, Req)
}

func (p *kIdentityServiceClient) ForcePasswordChange(ctx context.Context, Req *identity_srv.ForcePasswordChangeRequest, callOptions ...callopt.Option) (r *identity_srv.ForcePasswordChangeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ForcePasswordChange(ctx, Req)
}

func (p *kIdentityServiceClient) CreateUser(ctx context.Context, Req *identity_srv.CreateUserRequest, callOptions ...callopt.Option) (r *identity_srv.CreateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, Req)
}

func (p *kIdentityServiceClient) GetUser(ctx context.Context, Req *identity_srv.GetUserRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateUser(ctx context.Context, Req *identity_srv.UpdateUserRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteUser(ctx context.Context, Req *identity_srv.DeleteUserRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUser(ctx, Req)
}

func (p *kIdentityServiceClient) ListUsers(ctx context.Context, Req *identity_srv.ListUsersRequest, callOptions ...callopt.Option) (r *identity_srv.ListUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, Req)
}

func (p *kIdentityServiceClient) SearchUsers(ctx context.Context, Req *identity_srv.SearchUsersRequest, callOptions ...callopt.Option) (r *identity_srv.SearchUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchUsers(ctx, Req)
}

func (p *kIdentityServiceClient) ChangeUserStatus(ctx context.Context, Req *identity_srv.ChangeUserStatusRequest, callOptions ...callopt.Option) (r *identity_srv.ChangeUserStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeUserStatus(ctx, Req)
}

func (p *kIdentityServiceClient) UnlockUser(ctx context.Context, Req *identity_srv.UnlockUserRequest, callOptions ...callopt.Option) (r *identity_srv.UnlockUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnlockUser(ctx, Req)
}

func (p *kIdentityServiceClient) CreateOrganization(ctx context.Context, Req *identity_srv.CreateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.CreateOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrganization(ctx, Req)
}

func (p *kIdentityServiceClient) GetOrganization(ctx context.Context, Req *identity_srv.GetOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganization(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateOrganization(ctx context.Context, Req *identity_srv.UpdateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrganization(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteOrganization(ctx context.Context, Req *identity_srv.DeleteOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrganization(ctx, Req)
}

func (p *kIdentityServiceClient) ListOrganizations(ctx context.Context, Req *identity_srv.ListOrganizationsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOrganizationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrganizations(ctx, Req)
}

func (p *kIdentityServiceClient) AddMembership(ctx context.Context, Req *identity_srv.AddMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.AddMembershipResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddMembership(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateMembership(ctx context.Context, Req *identity_srv.UpdateMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateMembershipResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateMembership(ctx, Req)
}

func (p *kIdentityServiceClient) RemoveMembership(ctx context.Context, Req *identity_srv.RemoveMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.RemoveMembershipResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveMembership(ctx, Req)
}

func (p *kIdentityServiceClient) GetMembership(ctx context.Context, Req *identity_srv.GetMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.GetMembershipResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMembership(ctx, Req)
}

func (p *kIdentityServiceClient) GetUserMemberships(ctx context.Context, Req *identity_srv.GetUserMembershipsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMembershipsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMemberships(ctx, Req)
}

func (p *kIdentityServiceClient) GetPrimaryMembership(ctx context.Context, Req *identity_srv.GetPrimaryMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.GetPrimaryMembershipResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPrimaryMembership(ctx, Req)
}

func (p *kIdentityServiceClient) CheckMembership(ctx context.Context, Req *identity_srv.CheckMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.CheckMembershipResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckMembership(ctx, Req)
}

func (p *kIdentityServiceClient) CreateDepartment(ctx context.Context, Req *identity_srv.CreateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.CreateDepartmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateDepartment(ctx, Req)
}

func (p *kIdentityServiceClient) GetDepartment(ctx context.Context, Req *identity_srv.GetDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.GetDepartmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDepartment(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateDepartment(ctx context.Context, Req *identity_srv.UpdateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateDepartmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDepartment(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteDepartment(ctx context.Context, Req *identity_srv.DeleteDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteDepartmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDepartment(ctx, Req)
}

func (p *kIdentityServiceClient) GetOrganizationDepartments(ctx context.Context, Req *identity_srv.GetOrganizationDepartmentsRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationDepartmentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationDepartments(ctx, Req)
}

func (p *kIdentityServiceClient) UploadTemporaryLogo(ctx context.Context, Req *identity_srv.UploadTemporaryLogoRequest, callOptions ...callopt.Option) (r *identity_srv.UploadTemporaryLogoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadTemporaryLogo(ctx, Req)
}

func (p *kIdentityServiceClient) GetOrganizationLogo(ctx context.Context, Req *identity_srv.GetOrganizationLogoRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationLogoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationLogo(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteOrganizationLogo(ctx context.Context, Req *identity_srv.DeleteOrganizationLogoRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOrganizationLogoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrganizationLogo(ctx, Req)
}

func (p *kIdentityServiceClient) BindLogoToOrganization(ctx context.Context, Req *identity_srv.BindLogoToOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.BindLogoToOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindLogoToOrganization(ctx, Req)
}

func (p *kIdentityServiceClient) CreateRoleDefinition(ctx context.Context, Req *identity_srv.RoleDefinitionCreateRequest, callOptions ...callopt.Option) (r *identity_srv.CreateRoleDefinitionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRoleDefinition(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateRoleDefinition(ctx context.Context, Req *identity_srv.RoleDefinitionUpdateRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateRoleDefinitionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRoleDefinition(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteRoleDefinition(ctx context.Context, Req *identity_srv.DeleteRoleDefinitionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteRoleDefinitionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRoleDefinition(ctx, Req)
}

func (p *kIdentityServiceClient) GetRoleDefinition(ctx context.Context, Req *identity_srv.GetRoleDefinitionRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleDefinitionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoleDefinition(ctx, Req)
}

func (p *kIdentityServiceClient) ListRoleDefinitions(ctx context.Context, Req *identity_srv.RoleDefinitionQueryRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinitionListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoleDefinitions(ctx, Req)
}

func (p *kIdentityServiceClient) AssignRoleToUser(ctx context.Context, Req *identity_srv.AssignRoleToUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleAssignmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssignRoleToUser(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateUserRoleAssignment(ctx context.Context, Req *identity_srv.UpdateUserRoleAssignmentRequest, callOptions ...callopt.Option) (r *identity_srv.UpdateUserRoleAssignmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserRoleAssignment(ctx, Req)
}

func (p *kIdentityServiceClient) RevokeRoleFromUser(ctx context.Context, Req *identity_srv.RevokeRoleFromUserRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeRoleFromUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeRoleFromUser(ctx, Req)
}

func (p *kIdentityServiceClient) GetLastUserRoleAssignment(ctx context.Context, Req *identity_srv.GetLastUserRoleAssignmentRequest, callOptions ...callopt.Option) (r *identity_srv.GetLastUserRoleAssignmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastUserRoleAssignment(ctx, Req)
}

func (p *kIdentityServiceClient) ListUserRoleAssignments(ctx context.Context, Req *identity_srv.UserRoleQueryRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUserRoleAssignments(ctx, Req)
}

func (p *kIdentityServiceClient) GetUsersByRole(ctx context.Context, Req *identity_srv.GetUsersByRoleRequest, callOptions ...callopt.Option) (r *identity_srv.GetUsersByRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUsersByRole(ctx, Req)
}

func (p *kIdentityServiceClient) BatchBindUsersToRole(ctx context.Context, Req *identity_srv.BatchBindUsersToRoleRequest, callOptions ...callopt.Option) (r *identity_srv.BatchBindUsersToRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchBindUsersToRole(ctx, Req)
}

func (p *kIdentityServiceClient) BatchGetUserRoles(ctx context.Context, Req *identity_srv.BatchGetUserRolesRequest, callOptions ...callopt.Option) (r *identity_srv.BatchGetUserRolesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetUserRoles(ctx, Req)
}

func (p *kIdentityServiceClient) UploadMenu(ctx context.Context, Req *identity_srv.UploadMenuRequest, callOptions ...callopt.Option) (r *identity_srv.UploadMenuResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadMenu(ctx, Req)
}

func (p *kIdentityServiceClient) GetMenuTree(ctx context.Context, Req *identity_srv.GetMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMenuTree(ctx, Req)
}

func (p *kIdentityServiceClient) ConfigureRoleMenus(ctx context.Context, Req *identity_srv.ConfigureRoleMenusRequest, callOptions ...callopt.Option) (r *identity_srv.ConfigureRoleMenusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfigureRoleMenus(ctx, Req)
}

func (p *kIdentityServiceClient) GetRoleMenuTree(ctx context.Context, Req *identity_srv.GetRoleMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoleMenuTree(ctx, Req)
}

func (p *kIdentityServiceClient) GetUserMenuTree(ctx context.Context, Req *identity_srv.GetUserMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMenuTree(ctx, Req)
}

func (p *kIdentityServiceClient) GetRoleMenuPermissions(ctx context.Context, Req *identity_srv.GetRoleMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuPermissionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoleMenuPermissions(ctx, Req)
}

func (p *kIdentityServiceClient) HasMenuPermission(ctx context.Context, Req *identity_srv.HasMenuPermissionRequest, callOptions ...callopt.Option) (r *identity_srv.HasMenuPermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HasMenuPermission(ctx, Req)
}

func (p *kIdentityServiceClient) GetUserMenuPermissions(ctx context.Context, Req *identity_srv.GetUserMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuPermissionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMenuPermissions(ctx, Req)
}

func (p *kIdentityServiceClient) CheckPermission(ctx context.Context, Req *identity_srv.CheckPermissionRequest, callOptions ...callopt.Option) (r *identity_srv.CheckPermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckPermission(ctx, Req)
}

func (p *kIdentityServiceClient) SyncPolicies(ctx context.Context, Req *identity_srv.SyncPoliciesRequest, callOptions ...callopt.Option) (r *identity_srv.SyncPoliciesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SyncPolicies(ctx, Req)
}

func (p *kIdentityServiceClient) GetUserDataScope(ctx context.Context, Req *identity_srv.GetUserDataScopeRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserDataScopeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserDataScope(ctx, Req)
}

func (p *kIdentityServiceClient) CreateAuditLog(ctx context.Context, Req *identity_srv.CreateAuditLogRequest, callOptions ...callopt.Option) (r *identity_srv.CreateAuditLogResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAuditLog(ctx, Req)
}

func (p *kIdentityServiceClient) ListAuditLogs(ctx context.Context, Req *identity_srv.ListAuditLogsRequest, callOptions ...callopt.Option) (r *identity_srv.ListAuditLogsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAuditLogs(ctx, Req)
}

func (p *kIdentityServiceClient) CreateOAuth2Client(ctx context.Context, Req *identity_srv.CreateOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2ClientResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOAuth2Client(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2Client(ctx context.Context, Req *identity_srv.GetOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2Client, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2Client(ctx, Req)
}

func (p *kIdentityServiceClient) UpdateOAuth2Client(ctx context.Context, Req *identity_srv.UpdateOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2Client, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOAuth2Client(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteOAuth2Client(ctx context.Context, Req *identity_srv.DeleteOAuth2ClientRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2ClientResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOAuth2Client(ctx, Req)
}

func (p *kIdentityServiceClient) ListOAuth2Clients(ctx context.Context, Req *identity_srv.ListOAuth2ClientsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOAuth2ClientsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOAuth2Clients(ctx, Req)
}

func (p *kIdentityServiceClient) RotateOAuth2ClientSecret(ctx context.Context, Req *identity_srv.RotateOAuth2ClientSecretRequest, callOptions ...callopt.Option) (r *identity_srv.RotateOAuth2ClientSecretResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RotateOAuth2ClientSecret(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2ClientForAuth(ctx context.Context, Req *identity_srv.GetOAuth2ClientForAuthRequest, callOptions ...callopt.Option) (r *identity_srv.GetOAuth2ClientForAuthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2ClientForAuth(ctx, Req)
}

func (p *kIdentityServiceClient) ListOAuth2Scopes(ctx context.Context, Req *identity_srv.ListOAuth2ScopesRequest, callOptions ...callopt.Option) (r *identity_srv.ListOAuth2ScopesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOAuth2Scopes(ctx, Req)
}

func (p *kIdentityServiceClient) SaveOAuth2Consent(ctx context.Context, Req *identity_srv.SaveOAuth2ConsentRequest, callOptions ...callopt.Option) (r *identity_srv.SaveOAuth2ConsentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveOAuth2Consent(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2Consent(ctx context.Context, Req *identity_srv.GetOAuth2ConsentRequest, callOptions ...callopt.Option) (r *identity_srv.GetOAuth2ConsentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2Consent(ctx, Req)
}

func (p *kIdentityServiceClient) ListOAuth2Consents(ctx context.Context, Req *identity_srv.ListOAuth2ConsentsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOAuth2ConsentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOAuth2Consents(ctx, Req)
}

func (p *kIdentityServiceClient) RevokeOAuth2Consent(ctx context.Context, Req *identity_srv.RevokeOAuth2ConsentRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeOAuth2ConsentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeOAuth2Consent(ctx, Req)
}

func (p *kIdentityServiceClient) CreateOAuth2AuthorizeCodeSession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2AuthorizeCodeSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOAuth2AuthorizeCodeSession(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2AuthorizeCodeSession(ctx context.Context, Req *identity_srv.GetOAuth2AuthorizeCodeSessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2AuthorizeCodeSession(ctx, Req)
}

func (p *kIdentityServiceClient) InvalidateOAuth2AuthorizeCodeSession(ctx context.Context, Req *identity_srv.InvalidateOAuth2AuthorizeCodeSessionRequest, callOptions ...callopt.Option) (r *identity_srv.InvalidateOAuth2AuthorizeCodeSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InvalidateOAuth2AuthorizeCodeSession(ctx, Req)
}

func (p *kIdentityServiceClient) CreateOAuth2AccessTokenSession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2AccessTokenSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOAuth2AccessTokenSession(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2AccessTokenSession(ctx context.Context, Req *identity_srv.GetOAuth2AccessTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2AccessTokenSession(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteOAuth2AccessTokenSession(ctx context.Context, Req *identity_srv.DeleteOAuth2AccessTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2AccessTokenSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOAuth2AccessTokenSession(ctx, Req)
}

func (p *kIdentityServiceClient) RevokeOAuth2AccessToken(ctx context.Context, Req *identity_srv.RevokeOAuth2AccessTokenRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeOAuth2AccessTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeOAuth2AccessToken(ctx, Req)
}

func (p *kIdentityServiceClient) CreateOAuth2RefreshTokenSession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2RefreshTokenSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOAuth2RefreshTokenSession(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2RefreshTokenSession(ctx context.Context, Req *identity_srv.GetOAuth2RefreshTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2RefreshTokenSession(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteOAuth2RefreshTokenSession(ctx context.Context, Req *identity_srv.DeleteOAuth2RefreshTokenSessionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2RefreshTokenSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOAuth2RefreshTokenSession(ctx, Req)
}

func (p *kIdentityServiceClient) RevokeOAuth2RefreshToken(ctx context.Context, Req *identity_srv.RevokeOAuth2RefreshTokenRequest, callOptions ...callopt.Option) (r *identity_srv.RevokeOAuth2RefreshTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeOAuth2RefreshToken(ctx, Req)
}

func (p *kIdentityServiceClient) CreateOAuth2PKCESession(ctx context.Context, Req *identity_srv.OAuth2TokenSession, callOptions ...callopt.Option) (r *identity_srv.CreateOAuth2PKCESessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOAuth2PKCESession(ctx, Req)
}

func (p *kIdentityServiceClient) GetOAuth2PKCESession(ctx context.Context, Req *identity_srv.GetOAuth2PKCESessionRequest, callOptions ...callopt.Option) (r *identity_srv.OAuth2TokenSession, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOAuth2PKCESession(ctx, Req)
}

func (p *kIdentityServiceClient) DeleteOAuth2PKCESession(ctx context.Context, Req *identity_srv.DeleteOAuth2PKCESessionRequest, callOptions ...callopt.Option) (r *identity_srv.DeleteOAuth2PKCESessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOAuth2PKCESession(ctx, Req)
}
