// Code generated by hertz generator.

package oauth2

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauth2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clientsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listoauth2clientsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clientidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rotateoauth2clientsecretMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clients0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createoauth2clientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteoauth2clientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoauth2clientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateoauth2clientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmyoauth2consentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokemyoauth2consentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listoauth2scopesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoauth2configMw() []app.HandlerFunc {
	// your code...
	return nil
}
