// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/masonsxu/cloudwego-microservice-demo/gateway/internal/application/assembler/identity"
	"github.com/masonsxu/cloudwego-microservice-demo/gateway/internal/application/assembler/permission"
)

// Injectors from wire.go:

// InitializeApp 初始化应用容器
// 统一初始化所有依赖，避免重复创建 Logger 等实例
func InitializeApp() (*AppContainer, func(), error) {
	configuration := ProvideConfig()
	logger := ProvideLogger(configuration)
	identityClient := ProvideIdentityClient(logger)
	iAuthAssembler := identity.NewAuthAssembler()
	iUserAssembler := identity.NewUserAssembler()
	iOrgAssembler := identity.NewOrgAssembler()
	iDepartmentAssembler := identity.NewDepartmentAssembler()
	iMembershipAssembler := identity.NewMembershipAssembler()
	iLogoAssembler := identity.NewLogoAssembler()
	assembler := identity.NewIdentityAggregateAssembler(iAuthAssembler, iUserAssembler, iOrgAssembler, iDepartmentAssembler, iMembershipAssembler, iLogoAssembler)
	authService := ProvideAuthService(identityClient, assembler, logger)
	userService := ProvideUserService(identityClient, assembler, logger)
	membershipService := ProvideMembershipService(identityClient, assembler, logger)
	organizationService := ProvideOrganizationService(identityClient, assembler, logger)
	departmentService := ProvideDepartmentService(identityClient, assembler, logger)
	logoService := ProvideLogoService(identityClient, assembler, logger)
	service := ProvideIdentityService(authService, userService, membershipService, organizationService, departmentService, logoService)
	iPermissionAssembler := permission.NewPermissionAssembler()
	iRoleAssembler := permission.NewRoleAssembler(iPermissionAssembler)
	iUserRoleAssembler := permission.NewUserRoleAssembler()
	iMenuAssembler := permission.NewMenuAssembler()
	permissionAssembler := permission.NewPermissionAggregateAssembler(iRoleAssembler, iPermissionAssembler, iUserRoleAssembler, iMenuAssembler)
	roleDefinitionService := ProvideRoleDefinitionService(identityClient, permissionAssembler, logger)
	userRoleAssignmentService := ProvideUserRoleAssignmentService(identityClient, permissionAssembler, logger)
	menuService := ProvideMenuService(identityClient, permissionAssembler, logger)
	permissionService := ProvidePermissionService(roleDefinitionService, userRoleAssignmentService, menuService)
	serviceContainer := NewServiceContainer(service, permissionService)
	traceMiddlewareService := ProvideTraceMiddleware(logger)
	corsMiddlewareService := ProvideCORSMiddleware(configuration, logger)
	errorHandlerMiddlewareService := ProvideErrorHandlerMiddleware(configuration, logger)
	jwtConfig := ProvideJWTConfig(configuration)
	redisConfig := ProvideRedisConfig(configuration)
	client, err := ProvideRedisClient(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	tokenCacheService := ProvideTokenCache(client, logger)
	jwtMiddlewareService := ProvideJWTMiddleware(service, jwtConfig, tokenCacheService, logger)
	responseHeaderMiddlewareService := ProvideResponseHeaderMiddleware()
	middlewareContainer := NewMiddlewareContainer(traceMiddlewareService, corsMiddlewareService, errorHandlerMiddlewareService, jwtMiddlewareService, responseHeaderMiddlewareService)
	tracer := ProvideTracer(configuration)
	provider, cleanup, err := ProvideOtelProvider(configuration)
	if err != nil {
		return nil, nil, err
	}
	serverFactory := ProvideServerFactory(configuration, tracer, provider)
	handlerRegistry := ProvideHandlerRegistry(serverFactory, tracer, middlewareContainer, serviceContainer, logger)
	appContainer := NewAppContainer(configuration, logger, serviceContainer, middlewareContainer, handlerRegistry)
	return appContainer, func() {
		cleanup()
	}, nil
}

// wire.go:

// AllSet 所有依赖注入集合
// 按照分层架构组织：基础设施层 -> 应用层 -> 领域层 -> 中间件层 -> 服务器层
var AllSet = wire.NewSet(

	InfrastructureSet,

	ApplicationSet,

	DomainServiceSet,

	MiddlewareSet,

	ServerSet,

	NewServiceContainer,
	NewAppContainer,
)
