// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/assignment/user_role_assignment_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/assignment/user_role_assignment_interface.go -destination=biz/mock/assignment_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	assignment "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/assignment"
	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserRoleAssignmentRepository is a mock of UserRoleAssignmentRepository interface.
type MockUserRoleAssignmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleAssignmentRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRoleAssignmentRepositoryMockRecorder is the mock recorder for MockUserRoleAssignmentRepository.
type MockUserRoleAssignmentRepositoryMockRecorder struct {
	mock *MockUserRoleAssignmentRepository
}

// NewMockUserRoleAssignmentRepository creates a new mock instance.
func NewMockUserRoleAssignmentRepository(ctrl *gomock.Controller) *MockUserRoleAssignmentRepository {
	mock := &MockUserRoleAssignmentRepository{ctrl: ctrl}
	mock.recorder = &MockUserRoleAssignmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleAssignmentRepository) EXPECT() *MockUserRoleAssignmentRepositoryMockRecorder {
	return m.recorder
}

// BatchAssignRoleToUsers mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchAssignRoleToUsers(ctx context.Context, userIDs []string, roleID, assignedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAssignRoleToUsers", ctx, userIDs, roleID, assignedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchAssignRoleToUsers indicates an expected call of BatchAssignRoleToUsers.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchAssignRoleToUsers(ctx, userIDs, roleID, assignedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAssignRoleToUsers", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchAssignRoleToUsers), ctx, userIDs, roleID, assignedBy)
}

// BatchCreate mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchCreate(ctx context.Context, entities []*models.UserRoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchCreate), ctx, entities)
}

// BatchDelete mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchDelete), ctx, ids)
}

// BatchGetByIDs mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]*models.UserRoleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.UserRoleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchRestore), ctx, ids)
}

// BatchRevokeUserRoles mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchRevokeUserRoles(ctx context.Context, assignmentIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRevokeUserRoles", ctx, assignmentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRevokeUserRoles indicates an expected call of BatchRevokeUserRoles.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchRevokeUserRoles(ctx, assignmentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRevokeUserRoles", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchRevokeUserRoles), ctx, assignmentIDs)
}

// BatchSoftDelete mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockUserRoleAssignmentRepository) BatchUpdate(ctx context.Context, entities []*models.UserRoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).BatchUpdate), ctx, entities)
}

// CheckUserRoleExists mocks base method.
func (m *MockUserRoleAssignmentRepository) CheckUserRoleExists(ctx context.Context, userID, roleID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserRoleExists", ctx, userID, roleID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserRoleExists indicates an expected call of CheckUserRoleExists.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) CheckUserRoleExists(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserRoleExists", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).CheckUserRoleExists), ctx, userID, roleID)
}

// Count mocks base method.
func (m *MockUserRoleAssignmentRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).Count), ctx, opts)
}

// CountByRoleID mocks base method.
func (m *MockUserRoleAssignmentRepository) CountByRoleID(ctx context.Context, roleID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRoleID", ctx, roleID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRoleID indicates an expected call of CountByRoleID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) CountByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRoleID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).CountByRoleID), ctx, roleID)
}

// CountByUserID mocks base method.
func (m *MockUserRoleAssignmentRepository) CountByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockUserRoleAssignmentRepository) Create(ctx context.Context, entity *models.UserRoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserRoleAssignmentRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockUserRoleAssignmentRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).Exists), ctx, id)
}

// FindAll mocks base method.
func (m *MockUserRoleAssignmentRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]*models.UserRoleAssignment, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]*models.UserRoleAssignment)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).FindAll), ctx, opts)
}

// FindByRoleID mocks base method.
func (m *MockUserRoleAssignmentRepository) FindByRoleID(ctx context.Context, roleID string, page *base.QueryOptions) ([]*models.UserRoleAssignment, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoleID", ctx, roleID, page)
	ret0, _ := ret[0].([]*models.UserRoleAssignment)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByRoleID indicates an expected call of FindByRoleID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) FindByRoleID(ctx, roleID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoleID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).FindByRoleID), ctx, roleID, page)
}

// FindByUserAndRole mocks base method.
func (m *MockUserRoleAssignmentRepository) FindByUserAndRole(ctx context.Context, userID, roleID string) (*models.UserRoleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndRole", ctx, userID, roleID)
	ret0, _ := ret[0].(*models.UserRoleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndRole indicates an expected call of FindByUserAndRole.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) FindByUserAndRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndRole", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).FindByUserAndRole), ctx, userID, roleID)
}

// FindByUserID mocks base method.
func (m *MockUserRoleAssignmentRepository) FindByUserID(ctx context.Context, userID string, page *base.QueryOptions) ([]*models.UserRoleAssignment, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, page)
	ret0, _ := ret[0].([]*models.UserRoleAssignment)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) FindByUserID(ctx, userID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).FindByUserID), ctx, userID, page)
}

// FindWithConditions mocks base method.
func (m *MockUserRoleAssignmentRepository) FindWithConditions(ctx context.Context, conditions *assignment.UserRoleAssignmentQueryConditions) ([]*models.UserRoleAssignment, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithConditions", ctx, conditions)
	ret0, _ := ret[0].([]*models.UserRoleAssignment)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithConditions indicates an expected call of FindWithConditions.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) FindWithConditions(ctx, conditions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithConditions", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).FindWithConditions), ctx, conditions)
}

// GetActiveRoleIDsWithStatus mocks base method.
func (m *MockUserRoleAssignmentRepository) GetActiveRoleIDsWithStatus(ctx context.Context, userID string, status models.RoleStatus) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRoleIDsWithStatus", ctx, userID, status)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRoleIDsWithStatus indicates an expected call of GetActiveRoleIDsWithStatus.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) GetActiveRoleIDsWithStatus(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRoleIDsWithStatus", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).GetActiveRoleIDsWithStatus), ctx, userID, status)
}

// GetActiveRolesByUserID mocks base method.
func (m *MockUserRoleAssignmentRepository) GetActiveRolesByUserID(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRolesByUserID", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRolesByUserID indicates an expected call of GetActiveRolesByUserID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) GetActiveRolesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRolesByUserID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).GetActiveRolesByUserID), ctx, userID)
}

// GetAllUserIDsByRoleID mocks base method.
func (m *MockUserRoleAssignmentRepository) GetAllUserIDsByRoleID(ctx context.Context, roleID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserIDsByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserIDsByRoleID indicates an expected call of GetAllUserIDsByRoleID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) GetAllUserIDsByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserIDsByRoleID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).GetAllUserIDsByRoleID), ctx, roleID)
}

// GetByID mocks base method.
func (m *MockUserRoleAssignmentRepository) GetByID(ctx context.Context, id string) (*models.UserRoleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.UserRoleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).GetByID), ctx, id)
}

// GetLastUserRoleAssignment mocks base method.
func (m *MockUserRoleAssignmentRepository) GetLastUserRoleAssignment(ctx context.Context, userID string) (*models.UserRoleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUserRoleAssignment", ctx, userID)
	ret0, _ := ret[0].(*models.UserRoleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUserRoleAssignment indicates an expected call of GetLastUserRoleAssignment.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) GetLastUserRoleAssignment(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUserRoleAssignment", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).GetLastUserRoleAssignment), ctx, userID)
}

// GetRolesByUserIDs mocks base method.
func (m *MockUserRoleAssignmentRepository) GetRolesByUserIDs(ctx context.Context, userIDs []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesByUserIDs indicates an expected call of GetRolesByUserIDs.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) GetRolesByUserIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByUserIDs", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).GetRolesByUserIDs), ctx, userIDs)
}

// HardDelete mocks base method.
func (m *MockUserRoleAssignmentRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).HardDelete), ctx, id)
}

// ReplaceRoleUsers mocks base method.
func (m *MockUserRoleAssignmentRepository) ReplaceRoleUsers(ctx context.Context, roleID string, userIDs []string, operatorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRoleUsers", ctx, roleID, userIDs, operatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceRoleUsers indicates an expected call of ReplaceRoleUsers.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) ReplaceRoleUsers(ctx, roleID, userIDs, operatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRoleUsers", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).ReplaceRoleUsers), ctx, roleID, userIDs, operatorID)
}

// Restore mocks base method.
func (m *MockUserRoleAssignmentRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).Restore), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockUserRoleAssignmentRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserRoleAssignmentRepository) Update(ctx context.Context, entity *models.UserRoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).Update), ctx, entity)
}

// WithTx mocks base method.
func (m *MockUserRoleAssignmentRepository) WithTx(tx *gorm.DB) base.BaseRepository[models.UserRoleAssignment] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[models.UserRoleAssignment])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserRoleAssignmentRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserRoleAssignmentRepository)(nil).WithTx), tx)
}
