// Code generated by MockGen. DO NOT EDIT.
// Source: biz/converter/converter.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	assignment "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/assignment"
	authentication "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/authentication"
	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/base"
	definition "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/definition"
	department "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/department"
	enum "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/enum"
	logo "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/logo"
	membership "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/membership"
	menu "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/menu"
	organization "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/organization"
	user "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter/user"
	identity_srv "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/kitex_gen/identity_srv"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
)

// MockConverter is a mock of Converter interface.
type MockConverter struct {
	ctrl     *gomock.Controller
	recorder *MockConverterMockRecorder
}

// MockConverterMockRecorder is the mock recorder for MockConverter.
type MockConverterMockRecorder struct {
	mock *MockConverter
}

// NewMockConverter creates a new mock instance.
func NewMockConverter(ctrl *gomock.Controller) *MockConverter {
	mock := &MockConverter{ctrl: ctrl}
	mock.recorder = &MockConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverter) EXPECT() *MockConverterMockRecorder {
	return m.recorder
}

// Authentication mocks base method.
func (m *MockConverter) Authentication() authentication.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authentication")
	ret0, _ := ret[0].(authentication.Converter)
	return ret0
}

// Authentication indicates an expected call of Authentication.
func (mr *MockConverterMockRecorder) Authentication() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authentication", reflect.TypeOf((*MockConverter)(nil).Authentication))
}

// Base mocks base method.
func (m *MockConverter) Base() base.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Base")
	ret0, _ := ret[0].(base.Converter)
	return ret0
}

// Base indicates an expected call of Base.
func (mr *MockConverterMockRecorder) Base() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Base", reflect.TypeOf((*MockConverter)(nil).Base))
}

// BuildLoginResponse mocks base method.
func (m *MockConverter) BuildLoginResponse(userProfile *models.UserProfile, memberships []*models.UserMembership) *identity_srv.LoginResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildLoginResponse", userProfile, memberships)
	ret0, _ := ret[0].(*identity_srv.LoginResponse)
	return ret0
}

// BuildLoginResponse indicates an expected call of BuildLoginResponse.
func (mr *MockConverterMockRecorder) BuildLoginResponse(userProfile, memberships interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildLoginResponse", reflect.TypeOf((*MockConverter)(nil).BuildLoginResponse), userProfile, memberships)
}

// Department mocks base method.
func (m *MockConverter) Department() department.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Department")
	ret0, _ := ret[0].(department.Converter)
	return ret0
}

// Department indicates an expected call of Department.
func (mr *MockConverterMockRecorder) Department() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Department", reflect.TypeOf((*MockConverter)(nil).Department))
}

// Enum mocks base method.
func (m *MockConverter) Enum() enum.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enum")
	ret0, _ := ret[0].(enum.Converter)
	return ret0
}

// Enum indicates an expected call of Enum.
func (mr *MockConverterMockRecorder) Enum() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enum", reflect.TypeOf((*MockConverter)(nil).Enum))
}

// Logo mocks base method.
func (m *MockConverter) Logo() logo.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logo")
	ret0, _ := ret[0].(logo.Converter)
	return ret0
}

// Logo indicates an expected call of Logo.
func (mr *MockConverterMockRecorder) Logo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logo", reflect.TypeOf((*MockConverter)(nil).Logo))
}

// Membership mocks base method.
func (m *MockConverter) Membership() membership.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Membership")
	ret0, _ := ret[0].(membership.Converter)
	return ret0
}

// Membership indicates an expected call of Membership.
func (mr *MockConverterMockRecorder) Membership() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Membership", reflect.TypeOf((*MockConverter)(nil).Membership))
}

// Menu mocks base method.
func (m *MockConverter) Menu() menu.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Menu")
	ret0, _ := ret[0].(menu.Converter)
	return ret0
}

// Menu indicates an expected call of Menu.
func (mr *MockConverterMockRecorder) Menu() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Menu", reflect.TypeOf((*MockConverter)(nil).Menu))
}

// Organization mocks base method.
func (m *MockConverter) Organization() organization.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Organization")
	ret0, _ := ret[0].(organization.Converter)
	return ret0
}

// Organization indicates an expected call of Organization.
func (mr *MockConverterMockRecorder) Organization() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Organization", reflect.TypeOf((*MockConverter)(nil).Organization))
}

// RoleDefinition mocks base method.
func (m *MockConverter) RoleDefinition() definition.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDefinition")
	ret0, _ := ret[0].(definition.Converter)
	return ret0
}

// RoleDefinition indicates an expected call of RoleDefinition.
func (mr *MockConverterMockRecorder) RoleDefinition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDefinition", reflect.TypeOf((*MockConverter)(nil).RoleDefinition))
}

// UserProfile mocks base method.
func (m *MockConverter) UserProfile() user.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserProfile")
	ret0, _ := ret[0].(user.Converter)
	return ret0
}

// UserProfile indicates an expected call of UserProfile.
func (mr *MockConverterMockRecorder) UserProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserProfile", reflect.TypeOf((*MockConverter)(nil).UserProfile))
}

// UserRoleAssignment mocks base method.
func (m *MockConverter) UserRoleAssignment() assignment.Converter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRoleAssignment")
	ret0, _ := ret[0].(assignment.Converter)
	return ret0
}

// UserRoleAssignment indicates an expected call of UserRoleAssignment.
func (mr *MockConverterMockRecorder) UserRoleAssignment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRoleAssignment", reflect.TypeOf((*MockConverter)(nil).UserRoleAssignment))
}
