// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/dal.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dal "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal"
	assignment "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/assignment"
	definition "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/definition"
	department "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/department"
	logo "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/logo"
	membership "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/membership"
	menu "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/menu"
	organization "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/organization"
	rolemenu "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/rolemenu"
	user "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/user"
	gorm "gorm.io/gorm"
)

// MockDAL is a mock of DAL interface.
type MockDAL struct {
	ctrl     *gomock.Controller
	recorder *MockDALMockRecorder
}

// MockDALMockRecorder is the mock recorder for MockDAL.
type MockDALMockRecorder struct {
	mock *MockDAL
}

// NewMockDAL creates a new mock instance.
func NewMockDAL(ctrl *gomock.Controller) *MockDAL {
	mock := &MockDAL{ctrl: ctrl}
	mock.recorder = &MockDALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDAL) EXPECT() *MockDALMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDAL) BeginTx(ctx context.Context) (dal.DAL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(dal.DAL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDALMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDAL)(nil).BeginTx), ctx)
}

// Commit mocks base method.
func (m *MockDAL) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockDALMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDAL)(nil).Commit))
}

// DB mocks base method.
func (m *MockDAL) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockDALMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockDAL)(nil).DB))
}

// Department mocks base method.
func (m *MockDAL) Department() department.DepartmentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Department")
	ret0, _ := ret[0].(department.DepartmentRepository)
	return ret0
}

// Department indicates an expected call of Department.
func (mr *MockDALMockRecorder) Department() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Department", reflect.TypeOf((*MockDAL)(nil).Department))
}

// Logo mocks base method.
func (m *MockDAL) Logo() logo.LogoRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logo")
	ret0, _ := ret[0].(logo.LogoRepository)
	return ret0
}

// Logo indicates an expected call of Logo.
func (mr *MockDALMockRecorder) Logo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logo", reflect.TypeOf((*MockDAL)(nil).Logo))
}

// Menu mocks base method.
func (m *MockDAL) Menu() menu.MenuRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Menu")
	ret0, _ := ret[0].(menu.MenuRepository)
	return ret0
}

// Menu indicates an expected call of Menu.
func (mr *MockDALMockRecorder) Menu() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Menu", reflect.TypeOf((*MockDAL)(nil).Menu))
}

// Organization mocks base method.
func (m *MockDAL) Organization() organization.OrganizationRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Organization")
	ret0, _ := ret[0].(organization.OrganizationRepository)
	return ret0
}

// Organization indicates an expected call of Organization.
func (mr *MockDALMockRecorder) Organization() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Organization", reflect.TypeOf((*MockDAL)(nil).Organization))
}

// RoleDefinition mocks base method.
func (m *MockDAL) RoleDefinition() definition.RoleDefinitionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDefinition")
	ret0, _ := ret[0].(definition.RoleDefinitionRepository)
	return ret0
}

// RoleDefinition indicates an expected call of RoleDefinition.
func (mr *MockDALMockRecorder) RoleDefinition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDefinition", reflect.TypeOf((*MockDAL)(nil).RoleDefinition))
}

// RoleMenuPermission mocks base method.
func (m *MockDAL) RoleMenuPermission() rolemenu.RoleMenuPermissionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleMenuPermission")
	ret0, _ := ret[0].(rolemenu.RoleMenuPermissionRepository)
	return ret0
}

// RoleMenuPermission indicates an expected call of RoleMenuPermission.
func (mr *MockDALMockRecorder) RoleMenuPermission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleMenuPermission", reflect.TypeOf((*MockDAL)(nil).RoleMenuPermission))
}

// Rollback mocks base method.
func (m *MockDAL) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockDALMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDAL)(nil).Rollback))
}

// UserMembership mocks base method.
func (m *MockDAL) UserMembership() membership.UserMembershipRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserMembership")
	ret0, _ := ret[0].(membership.UserMembershipRepository)
	return ret0
}

// UserMembership indicates an expected call of UserMembership.
func (mr *MockDALMockRecorder) UserMembership() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserMembership", reflect.TypeOf((*MockDAL)(nil).UserMembership))
}

// UserProfile mocks base method.
func (m *MockDAL) UserProfile() user.UserProfileRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserProfile")
	ret0, _ := ret[0].(user.UserProfileRepository)
	return ret0
}

// UserProfile indicates an expected call of UserProfile.
func (mr *MockDALMockRecorder) UserProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserProfile", reflect.TypeOf((*MockDAL)(nil).UserProfile))
}

// UserRoleAssignment mocks base method.
func (m *MockDAL) UserRoleAssignment() assignment.UserRoleAssignmentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRoleAssignment")
	ret0, _ := ret[0].(assignment.UserRoleAssignmentRepository)
	return ret0
}

// UserRoleAssignment indicates an expected call of UserRoleAssignment.
func (mr *MockDALMockRecorder) UserRoleAssignment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRoleAssignment", reflect.TypeOf((*MockDAL)(nil).UserRoleAssignment))
}

// WithDB mocks base method.
func (m *MockDAL) WithDB(db *gorm.DB) dal.DAL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDB", db)
	ret0, _ := ret[0].(dal.DAL)
	return ret0
}

// WithDB indicates an expected call of WithDB.
func (mr *MockDALMockRecorder) WithDB(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDB", reflect.TypeOf((*MockDAL)(nil).WithDB), db)
}

// WithTransaction mocks base method.
func (m *MockDAL) WithTransaction(ctx context.Context, fn func(context.Context, dal.DAL) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockDALMockRecorder) WithTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockDAL)(nil).WithTransaction), ctx, fn)
}
