// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/definition/role_definition_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/definition/role_definition_interface.go -destination=biz/mock/definition_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	definition "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/definition"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRoleDefinitionRepository is a mock of RoleDefinitionRepository interface.
type MockRoleDefinitionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleDefinitionRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleDefinitionRepositoryMockRecorder is the mock recorder for MockRoleDefinitionRepository.
type MockRoleDefinitionRepositoryMockRecorder struct {
	mock *MockRoleDefinitionRepository
}

// NewMockRoleDefinitionRepository creates a new mock instance.
func NewMockRoleDefinitionRepository(ctrl *gomock.Controller) *MockRoleDefinitionRepository {
	mock := &MockRoleDefinitionRepository{ctrl: ctrl}
	mock.recorder = &MockRoleDefinitionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleDefinitionRepository) EXPECT() *MockRoleDefinitionRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockRoleDefinitionRepository) BatchCreate(ctx context.Context, entities []*models.RoleDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchCreate), ctx, entities)
}

// BatchDelete mocks base method.
func (m *MockRoleDefinitionRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchDelete), ctx, ids)
}

// BatchGetByIDs mocks base method.
func (m *MockRoleDefinitionRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]*models.RoleDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.RoleDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockRoleDefinitionRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockRoleDefinitionRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchRestore), ctx, ids)
}

// BatchSoftDelete mocks base method.
func (m *MockRoleDefinitionRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockRoleDefinitionRepository) BatchUpdate(ctx context.Context, entities []*models.RoleDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockRoleDefinitionRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).BatchUpdate), ctx, entities)
}

// CheckNameExists mocks base method.
func (m *MockRoleDefinitionRepository) CheckNameExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNameExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNameExists indicates an expected call of CheckNameExists.
func (mr *MockRoleDefinitionRepositoryMockRecorder) CheckNameExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNameExists", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).CheckNameExists), ctx, name)
}

// Count mocks base method.
func (m *MockRoleDefinitionRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRoleDefinitionRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).Count), ctx, opts)
}

// CountByStatus mocks base method.
func (m *MockRoleDefinitionRepository) CountByStatus(ctx context.Context, status models.RoleStatus) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockRoleDefinitionRepositoryMockRecorder) CountByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).CountByStatus), ctx, status)
}

// Create mocks base method.
func (m *MockRoleDefinitionRepository) Create(ctx context.Context, entity *models.RoleDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleDefinitionRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockRoleDefinitionRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleDefinitionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockRoleDefinitionRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRoleDefinitionRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).Exists), ctx, id)
}

// FindAll mocks base method.
func (m *MockRoleDefinitionRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]*models.RoleDefinition, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]*models.RoleDefinition)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRoleDefinitionRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).FindAll), ctx, opts)
}

// FindByName mocks base method.
func (m *MockRoleDefinitionRepository) FindByName(ctx context.Context, name string) (*models.RoleDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*models.RoleDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRoleDefinitionRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).FindByName), ctx, name)
}

// FindByStatus mocks base method.
func (m *MockRoleDefinitionRepository) FindByStatus(ctx context.Context, status models.RoleStatus, page *base.QueryOptions) ([]*models.RoleDefinition, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, status, page)
	ret0, _ := ret[0].([]*models.RoleDefinition)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockRoleDefinitionRepositoryMockRecorder) FindByStatus(ctx, status, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).FindByStatus), ctx, status, page)
}

// FindBySystemRole mocks base method.
func (m *MockRoleDefinitionRepository) FindBySystemRole(ctx context.Context, isSystemRole bool, page *base.QueryOptions) ([]*models.RoleDefinition, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySystemRole", ctx, isSystemRole, page)
	ret0, _ := ret[0].([]*models.RoleDefinition)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBySystemRole indicates an expected call of FindBySystemRole.
func (mr *MockRoleDefinitionRepositoryMockRecorder) FindBySystemRole(ctx, isSystemRole, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySystemRole", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).FindBySystemRole), ctx, isSystemRole, page)
}

// FindWithConditions mocks base method.
func (m *MockRoleDefinitionRepository) FindWithConditions(ctx context.Context, conditions *definition.RoleDefinitionQueryConditions) ([]*models.RoleDefinition, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithConditions", ctx, conditions)
	ret0, _ := ret[0].([]*models.RoleDefinition)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithConditions indicates an expected call of FindWithConditions.
func (mr *MockRoleDefinitionRepositoryMockRecorder) FindWithConditions(ctx, conditions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithConditions", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).FindWithConditions), ctx, conditions)
}

// GetByID mocks base method.
func (m *MockRoleDefinitionRepository) GetByID(ctx context.Context, id string) (*models.RoleDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.RoleDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleDefinitionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).GetByID), ctx, id)
}

// HardDelete mocks base method.
func (m *MockRoleDefinitionRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockRoleDefinitionRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).HardDelete), ctx, id)
}

// ListActiveRoles mocks base method.
func (m *MockRoleDefinitionRepository) ListActiveRoles(ctx context.Context, page *base.QueryOptions) ([]*models.RoleDefinition, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveRoles", ctx, page)
	ret0, _ := ret[0].([]*models.RoleDefinition)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActiveRoles indicates an expected call of ListActiveRoles.
func (mr *MockRoleDefinitionRepositoryMockRecorder) ListActiveRoles(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveRoles", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).ListActiveRoles), ctx, page)
}

// Restore mocks base method.
func (m *MockRoleDefinitionRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockRoleDefinitionRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).Restore), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockRoleDefinitionRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockRoleDefinitionRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockRoleDefinitionRepository) Update(ctx context.Context, entity *models.RoleDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleDefinitionRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).Update), ctx, entity)
}

// WithTx mocks base method.
func (m *MockRoleDefinitionRepository) WithTx(tx *gorm.DB) base.BaseRepository[models.RoleDefinition] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[models.RoleDefinition])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRoleDefinitionRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRoleDefinitionRepository)(nil).WithTx), tx)
}
