// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/department/department_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/department/department_interface.go -destination=biz/mock/department_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	department "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/department"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
	isgomock struct{}
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// AddEquipment mocks base method.
func (m *MockDepartmentRepository) AddEquipment(ctx context.Context, departmentID string, equipmentIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEquipment", ctx, departmentID, equipmentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEquipment indicates an expected call of AddEquipment.
func (mr *MockDepartmentRepositoryMockRecorder) AddEquipment(ctx, departmentID, equipmentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEquipment", reflect.TypeOf((*MockDepartmentRepository)(nil).AddEquipment), ctx, departmentID, equipmentIDs)
}

// BatchCreate mocks base method.
func (m *MockDepartmentRepository) BatchCreate(ctx context.Context, entities []*models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockDepartmentRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchCreate), ctx, entities)
}

// BatchCreateDepartments mocks base method.
func (m *MockDepartmentRepository) BatchCreateDepartments(ctx context.Context, departments []*models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateDepartments", ctx, departments)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateDepartments indicates an expected call of BatchCreateDepartments.
func (mr *MockDepartmentRepositoryMockRecorder) BatchCreateDepartments(ctx, departments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateDepartments", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchCreateDepartments), ctx, departments)
}

// BatchDelete mocks base method.
func (m *MockDepartmentRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDepartmentRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchDelete), ctx, ids)
}

// BatchDeleteByOrganization mocks base method.
func (m *MockDepartmentRepository) BatchDeleteByOrganization(ctx context.Context, organizationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDeleteByOrganization", ctx, organizationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDeleteByOrganization indicates an expected call of BatchDeleteByOrganization.
func (mr *MockDepartmentRepositoryMockRecorder) BatchDeleteByOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteByOrganization", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchDeleteByOrganization), ctx, organizationID)
}

// BatchGetByIDs mocks base method.
func (m *MockDepartmentRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockDepartmentRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockDepartmentRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockDepartmentRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockDepartmentRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockDepartmentRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchRestore), ctx, ids)
}

// BatchSoftDelete mocks base method.
func (m *MockDepartmentRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockDepartmentRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockDepartmentRepository) BatchUpdate(ctx context.Context, entities []*models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockDepartmentRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchUpdate), ctx, entities)
}

// BatchUpdateOrganization mocks base method.
func (m *MockDepartmentRepository) BatchUpdateOrganization(ctx context.Context, departmentIDs []string, newOrganizationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateOrganization", ctx, departmentIDs, newOrganizationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateOrganization indicates an expected call of BatchUpdateOrganization.
func (mr *MockDepartmentRepositoryMockRecorder) BatchUpdateOrganization(ctx, departmentIDs, newOrganizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateOrganization", reflect.TypeOf((*MockDepartmentRepository)(nil).BatchUpdateOrganization), ctx, departmentIDs, newOrganizationID)
}

// CheckNameExists mocks base method.
func (m *MockDepartmentRepository) CheckNameExists(ctx context.Context, name, organizationID string, excludeID ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, organizationID}
	for _, a := range excludeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckNameExists", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNameExists indicates an expected call of CheckNameExists.
func (mr *MockDepartmentRepositoryMockRecorder) CheckNameExists(ctx, name, organizationID any, excludeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, organizationID}, excludeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNameExists", reflect.TypeOf((*MockDepartmentRepository)(nil).CheckNameExists), varargs...)
}

// Count mocks base method.
func (m *MockDepartmentRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockDepartmentRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDepartmentRepository)(nil).Count), ctx, opts)
}

// CountByDepartmentType mocks base method.
func (m *MockDepartmentRepository) CountByDepartmentType(ctx context.Context, departmentType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByDepartmentType", ctx, departmentType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByDepartmentType indicates an expected call of CountByDepartmentType.
func (mr *MockDepartmentRepositoryMockRecorder) CountByDepartmentType(ctx, departmentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByDepartmentType", reflect.TypeOf((*MockDepartmentRepository)(nil).CountByDepartmentType), ctx, departmentType)
}

// CountByOrganization mocks base method.
func (m *MockDepartmentRepository) CountByOrganization(ctx context.Context, organizationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByOrganization", ctx, organizationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByOrganization indicates an expected call of CountByOrganization.
func (mr *MockDepartmentRepositoryMockRecorder) CountByOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByOrganization", reflect.TypeOf((*MockDepartmentRepository)(nil).CountByOrganization), ctx, organizationID)
}

// CountMembers mocks base method.
func (m *MockDepartmentRepository) CountMembers(ctx context.Context, departmentID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembers", ctx, departmentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembers indicates an expected call of CountMembers.
func (mr *MockDepartmentRepositoryMockRecorder) CountMembers(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembers", reflect.TypeOf((*MockDepartmentRepository)(nil).CountMembers), ctx, departmentID)
}

// Create mocks base method.
func (m *MockDepartmentRepository) Create(ctx context.Context, entity *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockDepartmentRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockDepartmentRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockDepartmentRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDepartmentRepository)(nil).Exists), ctx, id)
}

// ExistsByID mocks base method.
func (m *MockDepartmentRepository) ExistsByID(ctx context.Context, departmentID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByID", ctx, departmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByID indicates an expected call of ExistsByID.
func (mr *MockDepartmentRepositoryMockRecorder) ExistsByID(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByID", reflect.TypeOf((*MockDepartmentRepository)(nil).ExistsByID), ctx, departmentID)
}

// FindAll mocks base method.
func (m *MockDepartmentRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]*models.Department, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]*models.Department)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDepartmentRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDepartmentRepository)(nil).FindAll), ctx, opts)
}

// FindWithConditions mocks base method.
func (m *MockDepartmentRepository) FindWithConditions(ctx context.Context, conditions *department.DepartmentQueryConditions) ([]*models.Department, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithConditions", ctx, conditions)
	ret0, _ := ret[0].([]*models.Department)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithConditions indicates an expected call of FindWithConditions.
func (mr *MockDepartmentRepositoryMockRecorder) FindWithConditions(ctx, conditions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithConditions", reflect.TypeOf((*MockDepartmentRepository)(nil).FindWithConditions), ctx, conditions)
}

// GetByID mocks base method.
func (m *MockDepartmentRepository) GetByID(ctx context.Context, id string) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDepartmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDepartmentRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockDepartmentRepository) GetByName(ctx context.Context, name, organizationID string) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name, organizationID)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockDepartmentRepositoryMockRecorder) GetByName(ctx, name, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockDepartmentRepository)(nil).GetByName), ctx, name, organizationID)
}

// GetDepartmentEquipment mocks base method.
func (m *MockDepartmentRepository) GetDepartmentEquipment(ctx context.Context, departmentID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentEquipment", ctx, departmentID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentEquipment indicates an expected call of GetDepartmentEquipment.
func (mr *MockDepartmentRepositoryMockRecorder) GetDepartmentEquipment(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentEquipment", reflect.TypeOf((*MockDepartmentRepository)(nil).GetDepartmentEquipment), ctx, departmentID)
}

// GetDepartmentMembers mocks base method.
func (m *MockDepartmentRepository) GetDepartmentMembers(ctx context.Context, departmentID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentMembers", ctx, departmentID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentMembers indicates an expected call of GetDepartmentMembers.
func (mr *MockDepartmentRepositoryMockRecorder) GetDepartmentMembers(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentMembers", reflect.TypeOf((*MockDepartmentRepository)(nil).GetDepartmentMembers), ctx, departmentID)
}

// GetDepartmentStatistics mocks base method.
func (m *MockDepartmentRepository) GetDepartmentStatistics(ctx context.Context, departmentID string) (*department.DepartmentStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentStatistics", ctx, departmentID)
	ret0, _ := ret[0].(*department.DepartmentStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentStatistics indicates an expected call of GetDepartmentStatistics.
func (mr *MockDepartmentRepositoryMockRecorder) GetDepartmentStatistics(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentStatistics", reflect.TypeOf((*MockDepartmentRepository)(nil).GetDepartmentStatistics), ctx, departmentID)
}

// GetOrganizationDepartmentStatistics mocks base method.
func (m *MockDepartmentRepository) GetOrganizationDepartmentStatistics(ctx context.Context, organizationID string) (*department.OrganizationDepartmentStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationDepartmentStatistics", ctx, organizationID)
	ret0, _ := ret[0].(*department.OrganizationDepartmentStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationDepartmentStatistics indicates an expected call of GetOrganizationDepartmentStatistics.
func (mr *MockDepartmentRepositoryMockRecorder) GetOrganizationDepartmentStatistics(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationDepartmentStatistics", reflect.TypeOf((*MockDepartmentRepository)(nil).GetOrganizationDepartmentStatistics), ctx, organizationID)
}

// HardDelete mocks base method.
func (m *MockDepartmentRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockDepartmentRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockDepartmentRepository)(nil).HardDelete), ctx, id)
}

// HasMembers mocks base method.
func (m *MockDepartmentRepository) HasMembers(ctx context.Context, departmentID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMembers", ctx, departmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMembers indicates an expected call of HasMembers.
func (mr *MockDepartmentRepositoryMockRecorder) HasMembers(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMembers", reflect.TypeOf((*MockDepartmentRepository)(nil).HasMembers), ctx, departmentID)
}

// RemoveEquipment mocks base method.
func (m *MockDepartmentRepository) RemoveEquipment(ctx context.Context, departmentID string, equipmentIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEquipment", ctx, departmentID, equipmentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEquipment indicates an expected call of RemoveEquipment.
func (mr *MockDepartmentRepositoryMockRecorder) RemoveEquipment(ctx, departmentID, equipmentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEquipment", reflect.TypeOf((*MockDepartmentRepository)(nil).RemoveEquipment), ctx, departmentID, equipmentIDs)
}

// Restore mocks base method.
func (m *MockDepartmentRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockDepartmentRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockDepartmentRepository)(nil).Restore), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockDepartmentRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockDepartmentRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockDepartmentRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockDepartmentRepository) Update(ctx context.Context, entity *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentRepository)(nil).Update), ctx, entity)
}

// UpdateEquipment mocks base method.
func (m *MockDepartmentRepository) UpdateEquipment(ctx context.Context, departmentID string, equipmentIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEquipment", ctx, departmentID, equipmentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEquipment indicates an expected call of UpdateEquipment.
func (mr *MockDepartmentRepositoryMockRecorder) UpdateEquipment(ctx, departmentID, equipmentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEquipment", reflect.TypeOf((*MockDepartmentRepository)(nil).UpdateEquipment), ctx, departmentID, equipmentIDs)
}

// ValidateOrganizationExists mocks base method.
func (m *MockDepartmentRepository) ValidateOrganizationExists(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrganizationExists", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateOrganizationExists indicates an expected call of ValidateOrganizationExists.
func (mr *MockDepartmentRepositoryMockRecorder) ValidateOrganizationExists(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrganizationExists", reflect.TypeOf((*MockDepartmentRepository)(nil).ValidateOrganizationExists), ctx, organizationID)
}

// WithTx mocks base method.
func (m *MockDepartmentRepository) WithTx(tx *gorm.DB) base.BaseRepository[models.Department] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[models.Department])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockDepartmentRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockDepartmentRepository)(nil).WithTx), tx)
}
