// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/membership/user_membership_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/membership/user_membership_interface.go -destination=biz/mock/membership_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	membership "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/membership"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserMembershipRepository is a mock of UserMembershipRepository interface.
type MockUserMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserMembershipRepositoryMockRecorder
	isgomock struct{}
}

// MockUserMembershipRepositoryMockRecorder is the mock recorder for MockUserMembershipRepository.
type MockUserMembershipRepositoryMockRecorder struct {
	mock *MockUserMembershipRepository
}

// NewMockUserMembershipRepository creates a new mock instance.
func NewMockUserMembershipRepository(ctrl *gomock.Controller) *MockUserMembershipRepository {
	mock := &MockUserMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockUserMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserMembershipRepository) EXPECT() *MockUserMembershipRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockUserMembershipRepository) BatchCreate(ctx context.Context, entities []*models.UserMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchCreate), ctx, entities)
}

// BatchCreateMemberships mocks base method.
func (m *MockUserMembershipRepository) BatchCreateMemberships(ctx context.Context, memberships []*models.UserMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateMemberships", ctx, memberships)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateMemberships indicates an expected call of BatchCreateMemberships.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchCreateMemberships(ctx, memberships any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateMemberships", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchCreateMemberships), ctx, memberships)
}

// BatchDelete mocks base method.
func (m *MockUserMembershipRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchDelete), ctx, ids)
}

// BatchDeleteByOrganization mocks base method.
func (m *MockUserMembershipRepository) BatchDeleteByOrganization(ctx context.Context, organizationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDeleteByOrganization", ctx, organizationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDeleteByOrganization indicates an expected call of BatchDeleteByOrganization.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchDeleteByOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteByOrganization", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchDeleteByOrganization), ctx, organizationID)
}

// BatchDeleteByUser mocks base method.
func (m *MockUserMembershipRepository) BatchDeleteByUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDeleteByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDeleteByUser indicates an expected call of BatchDeleteByUser.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchDeleteByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteByUser", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchDeleteByUser), ctx, userID)
}

// BatchGetByIDs mocks base method.
func (m *MockUserMembershipRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]*models.UserMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.UserMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockUserMembershipRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockUserMembershipRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchRestore), ctx, ids)
}

// BatchSoftDelete mocks base method.
func (m *MockUserMembershipRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockUserMembershipRepository) BatchUpdate(ctx context.Context, entities []*models.UserMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchUpdate), ctx, entities)
}

// BatchUpdateStatus mocks base method.
func (m *MockUserMembershipRepository) BatchUpdateStatus(ctx context.Context, membershipIDs []string, status models.MembershipStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateStatus", ctx, membershipIDs, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateStatus indicates an expected call of BatchUpdateStatus.
func (mr *MockUserMembershipRepositoryMockRecorder) BatchUpdateStatus(ctx, membershipIDs, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateStatus", reflect.TypeOf((*MockUserMembershipRepository)(nil).BatchUpdateStatus), ctx, membershipIDs, status)
}

// CheckMembershipExists mocks base method.
func (m *MockUserMembershipRepository) CheckMembershipExists(ctx context.Context, userID, organizationID, departmentID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMembershipExists", ctx, userID, organizationID, departmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMembershipExists indicates an expected call of CheckMembershipExists.
func (mr *MockUserMembershipRepositoryMockRecorder) CheckMembershipExists(ctx, userID, organizationID, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMembershipExists", reflect.TypeOf((*MockUserMembershipRepository)(nil).CheckMembershipExists), ctx, userID, organizationID, departmentID)
}

// Count mocks base method.
func (m *MockUserMembershipRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserMembershipRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserMembershipRepository)(nil).Count), ctx, opts)
}

// CountByDepartmentID mocks base method.
func (m *MockUserMembershipRepository) CountByDepartmentID(ctx context.Context, departmentID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByDepartmentID", ctx, departmentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByDepartmentID indicates an expected call of CountByDepartmentID.
func (mr *MockUserMembershipRepositoryMockRecorder) CountByDepartmentID(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByDepartmentID", reflect.TypeOf((*MockUserMembershipRepository)(nil).CountByDepartmentID), ctx, departmentID)
}

// CountByOrganization mocks base method.
func (m *MockUserMembershipRepository) CountByOrganization(ctx context.Context, organizationID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByOrganization", ctx, organizationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByOrganization indicates an expected call of CountByOrganization.
func (mr *MockUserMembershipRepositoryMockRecorder) CountByOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByOrganization", reflect.TypeOf((*MockUserMembershipRepository)(nil).CountByOrganization), ctx, organizationID)
}

// Create mocks base method.
func (m *MockUserMembershipRepository) Create(ctx context.Context, entity *models.UserMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserMembershipRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserMembershipRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserMembershipRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserMembershipRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserMembershipRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockUserMembershipRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserMembershipRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserMembershipRepository)(nil).Exists), ctx, id)
}

// ExistsByID mocks base method.
func (m *MockUserMembershipRepository) ExistsByID(ctx context.Context, membershipID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByID", ctx, membershipID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByID indicates an expected call of ExistsByID.
func (mr *MockUserMembershipRepositoryMockRecorder) ExistsByID(ctx, membershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByID", reflect.TypeOf((*MockUserMembershipRepository)(nil).ExistsByID), ctx, membershipID)
}

// FindAll mocks base method.
func (m *MockUserMembershipRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]*models.UserMembership, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]*models.UserMembership)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserMembershipRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserMembershipRepository)(nil).FindAll), ctx, opts)
}

// FindUsersByOrganizationHierarchy mocks base method.
func (m *MockUserMembershipRepository) FindUsersByOrganizationHierarchy(ctx context.Context, rootOrganizationID string, opts *base.QueryOptions) ([]*models.UserMembership, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByOrganizationHierarchy", ctx, rootOrganizationID, opts)
	ret0, _ := ret[0].([]*models.UserMembership)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindUsersByOrganizationHierarchy indicates an expected call of FindUsersByOrganizationHierarchy.
func (mr *MockUserMembershipRepositoryMockRecorder) FindUsersByOrganizationHierarchy(ctx, rootOrganizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByOrganizationHierarchy", reflect.TypeOf((*MockUserMembershipRepository)(nil).FindUsersByOrganizationHierarchy), ctx, rootOrganizationID, opts)
}

// FindWithConditions mocks base method.
func (m *MockUserMembershipRepository) FindWithConditions(ctx context.Context, conditions *membership.UserMembershipQueryConditions) ([]*models.UserMembership, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithConditions", ctx, conditions)
	ret0, _ := ret[0].([]*models.UserMembership)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithConditions indicates an expected call of FindWithConditions.
func (mr *MockUserMembershipRepositoryMockRecorder) FindWithConditions(ctx, conditions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithConditions", reflect.TypeOf((*MockUserMembershipRepository)(nil).FindWithConditions), ctx, conditions)
}

// GetByID mocks base method.
func (m *MockUserMembershipRepository) GetByID(ctx context.Context, id string) (*models.UserMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.UserMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserMembershipRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetByID), ctx, id)
}

// GetByUserAndDepartment mocks base method.
func (m *MockUserMembershipRepository) GetByUserAndDepartment(ctx context.Context, userID, departmentID string) (*models.UserMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndDepartment", ctx, userID, departmentID)
	ret0, _ := ret[0].(*models.UserMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndDepartment indicates an expected call of GetByUserAndDepartment.
func (mr *MockUserMembershipRepositoryMockRecorder) GetByUserAndDepartment(ctx, userID, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndDepartment", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetByUserAndDepartment), ctx, userID, departmentID)
}

// GetByUserAndOrganization mocks base method.
func (m *MockUserMembershipRepository) GetByUserAndOrganization(ctx context.Context, userID, organizationID string) (*models.UserMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndOrganization", ctx, userID, organizationID)
	ret0, _ := ret[0].(*models.UserMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndOrganization indicates an expected call of GetByUserAndOrganization.
func (mr *MockUserMembershipRepositoryMockRecorder) GetByUserAndOrganization(ctx, userID, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndOrganization", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetByUserAndOrganization), ctx, userID, organizationID)
}

// GetMembershipStatistics mocks base method.
func (m *MockUserMembershipRepository) GetMembershipStatistics(ctx context.Context, organizationID string) (*membership.MembershipStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembershipStatistics", ctx, organizationID)
	ret0, _ := ret[0].(*membership.MembershipStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembershipStatistics indicates an expected call of GetMembershipStatistics.
func (mr *MockUserMembershipRepositoryMockRecorder) GetMembershipStatistics(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembershipStatistics", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetMembershipStatistics), ctx, organizationID)
}

// GetOrganizationUsers mocks base method.
func (m *MockUserMembershipRepository) GetOrganizationUsers(ctx context.Context, organizationID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationUsers", ctx, organizationID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationUsers indicates an expected call of GetOrganizationUsers.
func (mr *MockUserMembershipRepositoryMockRecorder) GetOrganizationUsers(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationUsers", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetOrganizationUsers), ctx, organizationID)
}

// GetPrimaryMembership mocks base method.
func (m *MockUserMembershipRepository) GetPrimaryMembership(ctx context.Context, userID string) (*models.UserMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimaryMembership", ctx, userID)
	ret0, _ := ret[0].(*models.UserMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrimaryMembership indicates an expected call of GetPrimaryMembership.
func (mr *MockUserMembershipRepositoryMockRecorder) GetPrimaryMembership(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimaryMembership", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetPrimaryMembership), ctx, userID)
}

// GetPrimaryMembershipsByUserIDs mocks base method.
func (m *MockUserMembershipRepository) GetPrimaryMembershipsByUserIDs(ctx context.Context, userIDs []string) (map[string]*models.UserMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimaryMembershipsByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]*models.UserMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrimaryMembershipsByUserIDs indicates an expected call of GetPrimaryMembershipsByUserIDs.
func (mr *MockUserMembershipRepositoryMockRecorder) GetPrimaryMembershipsByUserIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimaryMembershipsByUserIDs", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetPrimaryMembershipsByUserIDs), ctx, userIDs)
}

// GetUserOrganizations mocks base method.
func (m *MockUserMembershipRepository) GetUserOrganizations(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrganizations", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrganizations indicates an expected call of GetUserOrganizations.
func (mr *MockUserMembershipRepositoryMockRecorder) GetUserOrganizations(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrganizations", reflect.TypeOf((*MockUserMembershipRepository)(nil).GetUserOrganizations), ctx, userID)
}

// HardDelete mocks base method.
func (m *MockUserMembershipRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockUserMembershipRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockUserMembershipRepository)(nil).HardDelete), ctx, id)
}

// Restore mocks base method.
func (m *MockUserMembershipRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockUserMembershipRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockUserMembershipRepository)(nil).Restore), ctx, id)
}

// SetPrimaryMembership mocks base method.
func (m *MockUserMembershipRepository) SetPrimaryMembership(ctx context.Context, userID, membershipID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimaryMembership", ctx, userID, membershipID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPrimaryMembership indicates an expected call of SetPrimaryMembership.
func (mr *MockUserMembershipRepositoryMockRecorder) SetPrimaryMembership(ctx, userID, membershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryMembership", reflect.TypeOf((*MockUserMembershipRepository)(nil).SetPrimaryMembership), ctx, userID, membershipID)
}

// SoftDelete mocks base method.
func (m *MockUserMembershipRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserMembershipRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserMembershipRepository)(nil).SoftDelete), ctx, id)
}

// UnsetPrimaryByUserID mocks base method.
func (m *MockUserMembershipRepository) UnsetPrimaryByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetPrimaryByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsetPrimaryByUserID indicates an expected call of UnsetPrimaryByUserID.
func (mr *MockUserMembershipRepositoryMockRecorder) UnsetPrimaryByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetPrimaryByUserID", reflect.TypeOf((*MockUserMembershipRepository)(nil).UnsetPrimaryByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockUserMembershipRepository) Update(ctx context.Context, entity *models.UserMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserMembershipRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserMembershipRepository)(nil).Update), ctx, entity)
}

// UpdateStatus mocks base method.
func (m *MockUserMembershipRepository) UpdateStatus(ctx context.Context, membershipID string, status models.MembershipStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, membershipID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockUserMembershipRepositoryMockRecorder) UpdateStatus(ctx, membershipID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockUserMembershipRepository)(nil).UpdateStatus), ctx, membershipID, status)
}

// WithTx mocks base method.
func (m *MockUserMembershipRepository) WithTx(tx *gorm.DB) base.BaseRepository[models.UserMembership] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[models.UserMembership])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserMembershipRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserMembershipRepository)(nil).WithTx), tx)
}
