// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/menu/menu_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/menu/menu_interface.go -destination=biz/mock/menu_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockMenuRepository is a mock of MenuRepository interface.
type MockMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryMockRecorder
	isgomock struct{}
}

// MockMenuRepositoryMockRecorder is the mock recorder for MockMenuRepository.
type MockMenuRepositoryMockRecorder struct {
	mock *MockMenuRepository
}

// NewMockMenuRepository creates a new mock instance.
func NewMockMenuRepository(ctrl *gomock.Controller) *MockMenuRepository {
	mock := &MockMenuRepository{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepository) EXPECT() *MockMenuRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockMenuRepository) BatchCreate(ctx context.Context, entities []**models.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockMenuRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockMenuRepository)(nil).BatchCreate), ctx, entities)
}

// BatchDelete mocks base method.
func (m *MockMenuRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockMenuRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockMenuRepository)(nil).BatchDelete), ctx, ids)
}

// BatchGetByIDs mocks base method.
func (m *MockMenuRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]**models.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]**models.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockMenuRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockMenuRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockMenuRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockMenuRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockMenuRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockMenuRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockMenuRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockMenuRepository)(nil).BatchRestore), ctx, ids)
}

// BatchSoftDelete mocks base method.
func (m *MockMenuRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockMenuRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockMenuRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockMenuRepository) BatchUpdate(ctx context.Context, entities []**models.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockMenuRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockMenuRepository)(nil).BatchUpdate), ctx, entities)
}

// Count mocks base method.
func (m *MockMenuRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockMenuRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMenuRepository)(nil).Count), ctx, opts)
}

// Create mocks base method.
func (m *MockMenuRepository) Create(ctx context.Context, entity **models.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMenuRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMenuRepository)(nil).Create), ctx, entity)
}

// CreateMenuTree mocks base method.
func (m *MockMenuRepository) CreateMenuTree(ctx context.Context, menus []*models.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMenuTree", ctx, menus)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMenuTree indicates an expected call of CreateMenuTree.
func (mr *MockMenuRepositoryMockRecorder) CreateMenuTree(ctx, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenuTree", reflect.TypeOf((*MockMenuRepository)(nil).CreateMenuTree), ctx, menus)
}

// Delete mocks base method.
func (m *MockMenuRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMenuRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMenuRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockMenuRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockMenuRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockMenuRepository)(nil).Exists), ctx, id)
}

// FindAll mocks base method.
func (m *MockMenuRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]**models.Menu, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]**models.Menu)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMenuRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMenuRepository)(nil).FindAll), ctx, opts)
}

// GetByID mocks base method.
func (m *MockMenuRepository) GetByID(ctx context.Context, id string) (**models.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(**models.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMenuRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMenuRepository)(nil).GetByID), ctx, id)
}

// GetBySemanticID mocks base method.
func (m *MockMenuRepository) GetBySemanticID(ctx context.Context, productLine, semanticID string, version int) (*models.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySemanticID", ctx, productLine, semanticID, version)
	ret0, _ := ret[0].(*models.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySemanticID indicates an expected call of GetBySemanticID.
func (mr *MockMenuRepositoryMockRecorder) GetBySemanticID(ctx, productLine, semanticID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySemanticID", reflect.TypeOf((*MockMenuRepository)(nil).GetBySemanticID), ctx, productLine, semanticID, version)
}

// GetBySemanticIDs mocks base method.
func (m *MockMenuRepository) GetBySemanticIDs(ctx context.Context, productLine string, semanticIDs []string) ([]*models.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySemanticIDs", ctx, productLine, semanticIDs)
	ret0, _ := ret[0].([]*models.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySemanticIDs indicates an expected call of GetBySemanticIDs.
func (mr *MockMenuRepositoryMockRecorder) GetBySemanticIDs(ctx, productLine, semanticIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySemanticIDs", reflect.TypeOf((*MockMenuRepository)(nil).GetBySemanticIDs), ctx, productLine, semanticIDs)
}

// GetLatestContentHash mocks base method.
func (m *MockMenuRepository) GetLatestContentHash(ctx context.Context, productLine string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestContentHash", ctx, productLine)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestContentHash indicates an expected call of GetLatestContentHash.
func (mr *MockMenuRepositoryMockRecorder) GetLatestContentHash(ctx, productLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestContentHash", reflect.TypeOf((*MockMenuRepository)(nil).GetLatestContentHash), ctx, productLine)
}

// GetLatestMenuTree mocks base method.
func (m *MockMenuRepository) GetLatestMenuTree(ctx context.Context, productLine string) ([]*models.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestMenuTree", ctx, productLine)
	ret0, _ := ret[0].([]*models.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestMenuTree indicates an expected call of GetLatestMenuTree.
func (mr *MockMenuRepositoryMockRecorder) GetLatestMenuTree(ctx, productLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestMenuTree", reflect.TypeOf((*MockMenuRepository)(nil).GetLatestMenuTree), ctx, productLine)
}

// GetLatestSemanticIDMapping mocks base method.
func (m *MockMenuRepository) GetLatestSemanticIDMapping(ctx context.Context, productLine string) (map[string]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSemanticIDMapping", ctx, productLine)
	ret0, _ := ret[0].(map[string]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSemanticIDMapping indicates an expected call of GetLatestSemanticIDMapping.
func (mr *MockMenuRepositoryMockRecorder) GetLatestSemanticIDMapping(ctx, productLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSemanticIDMapping", reflect.TypeOf((*MockMenuRepository)(nil).GetLatestSemanticIDMapping), ctx, productLine)
}

// GetMaxVersion mocks base method.
func (m *MockMenuRepository) GetMaxVersion(ctx context.Context, productLine string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxVersion", ctx, productLine)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxVersion indicates an expected call of GetMaxVersion.
func (mr *MockMenuRepositoryMockRecorder) GetMaxVersion(ctx, productLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxVersion", reflect.TypeOf((*MockMenuRepository)(nil).GetMaxVersion), ctx, productLine)
}

// HardDelete mocks base method.
func (m *MockMenuRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockMenuRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockMenuRepository)(nil).HardDelete), ctx, id)
}

// Restore mocks base method.
func (m *MockMenuRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockMenuRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockMenuRepository)(nil).Restore), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockMenuRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockMenuRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockMenuRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockMenuRepository) Update(ctx context.Context, entity **models.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMenuRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMenuRepository)(nil).Update), ctx, entity)
}

// WithTx mocks base method.
func (m *MockMenuRepository) WithTx(tx *gorm.DB) base.BaseRepository[*models.Menu] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[*models.Menu])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockMenuRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockMenuRepository)(nil).WithTx), tx)
}
