// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/organization/organization_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/organization/organization_interface.go -destination=biz/mock/organization_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	organization "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/organization"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockOrganizationRepository) BatchCreate(ctx context.Context, entities []*models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockOrganizationRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchCreate), ctx, entities)
}

// BatchDelete mocks base method.
func (m *MockOrganizationRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockOrganizationRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchDelete), ctx, ids)
}

// BatchGetByIDs mocks base method.
func (m *MockOrganizationRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockOrganizationRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockOrganizationRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockOrganizationRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockOrganizationRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockOrganizationRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchRestore), ctx, ids)
}

// BatchSoftDelete mocks base method.
func (m *MockOrganizationRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockOrganizationRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockOrganizationRepository) BatchUpdate(ctx context.Context, entities []*models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockOrganizationRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockOrganizationRepository)(nil).BatchUpdate), ctx, entities)
}

// CheckNameConflict mocks base method.
func (m *MockOrganizationRepository) CheckNameConflict(ctx context.Context, name, parentID string, excludeID ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, parentID}
	for _, a := range excludeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckNameConflict", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNameConflict indicates an expected call of CheckNameConflict.
func (mr *MockOrganizationRepositoryMockRecorder) CheckNameConflict(ctx, name, parentID any, excludeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, parentID}, excludeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNameConflict", reflect.TypeOf((*MockOrganizationRepository)(nil).CheckNameConflict), varargs...)
}

// Count mocks base method.
func (m *MockOrganizationRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockOrganizationRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockOrganizationRepository)(nil).Count), ctx, opts)
}

// CountChildren mocks base method.
func (m *MockOrganizationRepository) CountChildren(ctx context.Context, parentID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChildren", ctx, parentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChildren indicates an expected call of CountChildren.
func (mr *MockOrganizationRepositoryMockRecorder) CountChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChildren", reflect.TypeOf((*MockOrganizationRepository)(nil).CountChildren), ctx, parentID)
}

// Create mocks base method.
func (m *MockOrganizationRepository) Create(ctx context.Context, entity *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockOrganizationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockOrganizationRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockOrganizationRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockOrganizationRepository)(nil).Exists), ctx, id)
}

// ExistsByID mocks base method.
func (m *MockOrganizationRepository) ExistsByID(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByID", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByID indicates an expected call of ExistsByID.
func (mr *MockOrganizationRepositoryMockRecorder) ExistsByID(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByID", reflect.TypeOf((*MockOrganizationRepository)(nil).ExistsByID), ctx, organizationID)
}

// FindAll mocks base method.
func (m *MockOrganizationRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]*models.Organization, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]*models.Organization)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOrganizationRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOrganizationRepository)(nil).FindAll), ctx, opts)
}

// FindWithConditions mocks base method.
func (m *MockOrganizationRepository) FindWithConditions(ctx context.Context, conditions *organization.OrganizationQueryConditions) ([]*models.Organization, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithConditions", ctx, conditions)
	ret0, _ := ret[0].([]*models.Organization)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithConditions indicates an expected call of FindWithConditions.
func (mr *MockOrganizationRepositoryMockRecorder) FindWithConditions(ctx, conditions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithConditions", reflect.TypeOf((*MockOrganizationRepository)(nil).FindWithConditions), ctx, conditions)
}

// GetByCode mocks base method.
func (m *MockOrganizationRepository) GetByCode(ctx context.Context, code string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockOrganizationRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockOrganizationRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockOrganizationRepository) GetByID(ctx context.Context, id string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrganizationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrganizationRepository)(nil).GetByID), ctx, id)
}

// HardDelete mocks base method.
func (m *MockOrganizationRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockOrganizationRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockOrganizationRepository)(nil).HardDelete), ctx, id)
}

// HasChildren mocks base method.
func (m *MockOrganizationRepository) HasChildren(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasChildren", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasChildren indicates an expected call of HasChildren.
func (mr *MockOrganizationRepositoryMockRecorder) HasChildren(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasChildren", reflect.TypeOf((*MockOrganizationRepository)(nil).HasChildren), ctx, organizationID)
}

// Restore mocks base method.
func (m *MockOrganizationRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockOrganizationRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockOrganizationRepository)(nil).Restore), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockOrganizationRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockOrganizationRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockOrganizationRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockOrganizationRepository) Update(ctx context.Context, entity *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationRepository)(nil).Update), ctx, entity)
}

// UpdateParent mocks base method.
func (m *MockOrganizationRepository) UpdateParent(ctx context.Context, organizationID, newParentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParent", ctx, organizationID, newParentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParent indicates an expected call of UpdateParent.
func (mr *MockOrganizationRepositoryMockRecorder) UpdateParent(ctx, organizationID, newParentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParent", reflect.TypeOf((*MockOrganizationRepository)(nil).UpdateParent), ctx, organizationID, newParentID)
}

// WithTx mocks base method.
func (m *MockOrganizationRepository) WithTx(tx *gorm.DB) base.BaseRepository[models.Organization] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[models.Organization])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockOrganizationRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockOrganizationRepository)(nil).WithTx), tx)
}
