// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/rolemenu/interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/rolemenu/interface.go -destination=biz/mock/rolemenu_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleMenuPermissionRepository is a mock of RoleMenuPermissionRepository interface.
type MockRoleMenuPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleMenuPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleMenuPermissionRepositoryMockRecorder is the mock recorder for MockRoleMenuPermissionRepository.
type MockRoleMenuPermissionRepositoryMockRecorder struct {
	mock *MockRoleMenuPermissionRepository
}

// NewMockRoleMenuPermissionRepository creates a new mock instance.
func NewMockRoleMenuPermissionRepository(ctrl *gomock.Controller) *MockRoleMenuPermissionRepository {
	mock := &MockRoleMenuPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockRoleMenuPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleMenuPermissionRepository) EXPECT() *MockRoleMenuPermissionRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockRoleMenuPermissionRepository) BatchCreate(ctx context.Context, permissions []*models.RoleMenuPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) BatchCreate(ctx, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).BatchCreate), ctx, permissions)
}

// Create mocks base method.
func (m *MockRoleMenuPermissionRepository) Create(ctx context.Context, permission *models.RoleMenuPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) Create(ctx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).Create), ctx, permission)
}

// Delete mocks base method.
func (m *MockRoleMenuPermissionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).Delete), ctx, id)
}

// DeleteByRoleID mocks base method.
func (m *MockRoleMenuPermissionRepository) DeleteByRoleID(ctx context.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRoleID", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRoleID indicates an expected call of DeleteByRoleID.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) DeleteByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRoleID", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).DeleteByRoleID), ctx, roleID)
}

// GetByID mocks base method.
func (m *MockRoleMenuPermissionRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.RoleMenuPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.RoleMenuPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetByID), ctx, id)
}

// GetByRoleAndMenu mocks base method.
func (m *MockRoleMenuPermissionRepository) GetByRoleAndMenu(ctx context.Context, roleID uuid.UUID, menuID string) (*models.RoleMenuPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoleAndMenu", ctx, roleID, menuID)
	ret0, _ := ret[0].(*models.RoleMenuPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleAndMenu indicates an expected call of GetByRoleAndMenu.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetByRoleAndMenu(ctx, roleID, menuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleAndMenu", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetByRoleAndMenu), ctx, roleID, menuID)
}

// GetByRoleID mocks base method.
func (m *MockRoleMenuPermissionRepository) GetByRoleID(ctx context.Context, roleID uuid.UUID) ([]*models.RoleMenuPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]*models.RoleMenuPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleID indicates an expected call of GetByRoleID.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleID", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetByRoleID), ctx, roleID)
}

// GetByRoleIDs mocks base method.
func (m *MockRoleMenuPermissionRepository) GetByRoleIDs(ctx context.Context, roleIDs []uuid.UUID) ([]*models.RoleMenuPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoleIDs", ctx, roleIDs)
	ret0, _ := ret[0].([]*models.RoleMenuPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleIDs indicates an expected call of GetByRoleIDs.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetByRoleIDs(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleIDs", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetByRoleIDs), ctx, roleIDs)
}

// GetMenuIDsByRoleID mocks base method.
func (m *MockRoleMenuPermissionRepository) GetMenuIDsByRoleID(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuIDsByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuIDsByRoleID indicates an expected call of GetMenuIDsByRoleID.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetMenuIDsByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuIDsByRoleID", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetMenuIDsByRoleID), ctx, roleID)
}

// GetMenuIDsByRoleIDs mocks base method.
func (m *MockRoleMenuPermissionRepository) GetMenuIDsByRoleIDs(ctx context.Context, roleIDs []uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuIDsByRoleIDs", ctx, roleIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuIDsByRoleIDs indicates an expected call of GetMenuIDsByRoleIDs.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetMenuIDsByRoleIDs(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuIDsByRoleIDs", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetMenuIDsByRoleIDs), ctx, roleIDs)
}

// GetMergedPermissions mocks base method.
func (m *MockRoleMenuPermissionRepository) GetMergedPermissions(ctx context.Context, roleIDs []uuid.UUID) ([]models.MenuPermissionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMergedPermissions", ctx, roleIDs)
	ret0, _ := ret[0].([]models.MenuPermissionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMergedPermissions indicates an expected call of GetMergedPermissions.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) GetMergedPermissions(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergedPermissions", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).GetMergedPermissions), ctx, roleIDs)
}

// HasPermission mocks base method.
func (m *MockRoleMenuPermissionRepository) HasPermission(ctx context.Context, roleID uuid.UUID, menuID string, permissionType models.MenuPermissionType) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", ctx, roleID, menuID, permissionType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) HasPermission(ctx, roleID, menuID, permissionType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).HasPermission), ctx, roleID, menuID, permissionType)
}

// SyncRoleMenus mocks base method.
func (m *MockRoleMenuPermissionRepository) SyncRoleMenus(ctx context.Context, roleID uuid.UUID, permissions []*models.RoleMenuPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncRoleMenus", ctx, roleID, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncRoleMenus indicates an expected call of SyncRoleMenus.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) SyncRoleMenus(ctx, roleID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncRoleMenus", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).SyncRoleMenus), ctx, roleID, permissions)
}

// Update mocks base method.
func (m *MockRoleMenuPermissionRepository) Update(ctx context.Context, permission *models.RoleMenuPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleMenuPermissionRepositoryMockRecorder) Update(ctx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleMenuPermissionRepository)(nil).Update), ctx, permission)
}
