// Code generated by MockGen. DO NOT EDIT.
// Source: biz/dal/user/user_profile_interface.go
//
// Generated by this command:
//
//	mockgen -source=biz/dal/user/user_profile_interface.go -destination=biz/mock/user_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	base "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/base"
	user "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal/user"
	models "github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserProfileRepository is a mock of UserProfileRepository interface.
type MockUserProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProfileRepositoryMockRecorder is the mock recorder for MockUserProfileRepository.
type MockUserProfileRepositoryMockRecorder struct {
	mock *MockUserProfileRepository
}

// NewMockUserProfileRepository creates a new mock instance.
func NewMockUserProfileRepository(ctrl *gomock.Controller) *MockUserProfileRepository {
	mock := &MockUserProfileRepository{ctrl: ctrl}
	mock.recorder = &MockUserProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileRepository) EXPECT() *MockUserProfileRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockUserProfileRepository) BatchCreate(ctx context.Context, entities []*models.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockUserProfileRepositoryMockRecorder) BatchCreate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchCreate), ctx, entities)
}

// BatchDelete mocks base method.
func (m *MockUserProfileRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockUserProfileRepositoryMockRecorder) BatchDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchDelete), ctx, ids)
}

// BatchGetByIDs mocks base method.
func (m *MockUserProfileRepository) BatchGetByIDs(ctx context.Context, ids []string) ([]*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockUserProfileRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchGetByIDs), ctx, ids)
}

// BatchHardDelete mocks base method.
func (m *MockUserProfileRepository) BatchHardDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchHardDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchHardDelete indicates an expected call of BatchHardDelete.
func (mr *MockUserProfileRepositoryMockRecorder) BatchHardDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchHardDelete", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchHardDelete), ctx, ids)
}

// BatchRestore mocks base method.
func (m *MockUserProfileRepository) BatchRestore(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRestore", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchRestore indicates an expected call of BatchRestore.
func (mr *MockUserProfileRepositoryMockRecorder) BatchRestore(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRestore", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchRestore), ctx, ids)
}

// BatchSoftDelete mocks base method.
func (m *MockUserProfileRepository) BatchSoftDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSoftDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSoftDelete indicates an expected call of BatchSoftDelete.
func (mr *MockUserProfileRepositoryMockRecorder) BatchSoftDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSoftDelete", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchSoftDelete), ctx, ids)
}

// BatchUpdate mocks base method.
func (m *MockUserProfileRepository) BatchUpdate(ctx context.Context, entities []*models.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockUserProfileRepositoryMockRecorder) BatchUpdate(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockUserProfileRepository)(nil).BatchUpdate), ctx, entities)
}

// CheckEmailExists mocks base method.
func (m *MockUserProfileRepository) CheckEmailExists(ctx context.Context, email string, excludeID ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, email}
	for _, a := range excludeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckEmailExists", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmailExists indicates an expected call of CheckEmailExists.
func (mr *MockUserProfileRepositoryMockRecorder) CheckEmailExists(ctx, email any, excludeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, email}, excludeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailExists", reflect.TypeOf((*MockUserProfileRepository)(nil).CheckEmailExists), varargs...)
}

// CheckPhoneExists mocks base method.
func (m *MockUserProfileRepository) CheckPhoneExists(ctx context.Context, phone string, excludeID ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, phone}
	for _, a := range excludeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckPhoneExists", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPhoneExists indicates an expected call of CheckPhoneExists.
func (mr *MockUserProfileRepositoryMockRecorder) CheckPhoneExists(ctx, phone any, excludeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, phone}, excludeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPhoneExists", reflect.TypeOf((*MockUserProfileRepository)(nil).CheckPhoneExists), varargs...)
}

// CheckUsernameExists mocks base method.
func (m *MockUserProfileRepository) CheckUsernameExists(ctx context.Context, username string, excludeID ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, username}
	for _, a := range excludeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckUsernameExists", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsernameExists indicates an expected call of CheckUsernameExists.
func (mr *MockUserProfileRepositoryMockRecorder) CheckUsernameExists(ctx, username any, excludeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, username}, excludeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsernameExists", reflect.TypeOf((*MockUserProfileRepository)(nil).CheckUsernameExists), varargs...)
}

// Count mocks base method.
func (m *MockUserProfileRepository) Count(ctx context.Context, opts *base.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserProfileRepositoryMockRecorder) Count(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserProfileRepository)(nil).Count), ctx, opts)
}

// Create mocks base method.
func (m *MockUserProfileRepository) Create(ctx context.Context, entity *models.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserProfileRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProfileRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserProfileRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserProfileRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserProfileRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockUserProfileRepository) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserProfileRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserProfileRepository)(nil).Exists), ctx, id)
}

// ExistsByID mocks base method.
func (m *MockUserProfileRepository) ExistsByID(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByID", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByID indicates an expected call of ExistsByID.
func (mr *MockUserProfileRepositoryMockRecorder) ExistsByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByID", reflect.TypeOf((*MockUserProfileRepository)(nil).ExistsByID), ctx, userID)
}

// FindAll mocks base method.
func (m *MockUserProfileRepository) FindAll(ctx context.Context, opts *base.QueryOptions) ([]*models.UserProfile, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, opts)
	ret0, _ := ret[0].([]*models.UserProfile)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserProfileRepositoryMockRecorder) FindAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserProfileRepository)(nil).FindAll), ctx, opts)
}

// FindByMedicalLicense mocks base method.
func (m *MockUserProfileRepository) FindByMedicalLicense(ctx context.Context, licenseNumber string) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByMedicalLicense", ctx, licenseNumber)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByMedicalLicense indicates an expected call of FindByMedicalLicense.
func (mr *MockUserProfileRepositoryMockRecorder) FindByMedicalLicense(ctx, licenseNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByMedicalLicense", reflect.TypeOf((*MockUserProfileRepository)(nil).FindByMedicalLicense), ctx, licenseNumber)
}

// FindBySpecialty mocks base method.
func (m *MockUserProfileRepository) FindBySpecialty(ctx context.Context, specialty string, opts *base.QueryOptions) ([]*models.UserProfile, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySpecialty", ctx, specialty, opts)
	ret0, _ := ret[0].([]*models.UserProfile)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBySpecialty indicates an expected call of FindBySpecialty.
func (mr *MockUserProfileRepositoryMockRecorder) FindBySpecialty(ctx, specialty, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySpecialty", reflect.TypeOf((*MockUserProfileRepository)(nil).FindBySpecialty), ctx, specialty, opts)
}

// FindSystemUsers mocks base method.
func (m *MockUserProfileRepository) FindSystemUsers(ctx context.Context) ([]*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSystemUsers", ctx)
	ret0, _ := ret[0].([]*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSystemUsers indicates an expected call of FindSystemUsers.
func (mr *MockUserProfileRepositoryMockRecorder) FindSystemUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSystemUsers", reflect.TypeOf((*MockUserProfileRepository)(nil).FindSystemUsers), ctx)
}

// FindWithConditions mocks base method.
func (m *MockUserProfileRepository) FindWithConditions(ctx context.Context, conditions *user.UserProfileQueryConditions) ([]*models.UserProfile, *models.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithConditions", ctx, conditions)
	ret0, _ := ret[0].([]*models.UserProfile)
	ret1, _ := ret[1].(*models.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithConditions indicates an expected call of FindWithConditions.
func (mr *MockUserProfileRepositoryMockRecorder) FindWithConditions(ctx, conditions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithConditions", reflect.TypeOf((*MockUserProfileRepository)(nil).FindWithConditions), ctx, conditions)
}

// GetByEmail mocks base method.
func (m *MockUserProfileRepository) GetByEmail(ctx context.Context, email string) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserProfileRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserProfileRepository) GetByID(ctx context.Context, id string) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserProfileRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByID), ctx, id)
}

// GetByPhone mocks base method.
func (m *MockUserProfileRepository) GetByPhone(ctx context.Context, phone string) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockUserProfileRepositoryMockRecorder) GetByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByPhone), ctx, phone)
}

// GetByUsername mocks base method.
func (m *MockUserProfileRepository) GetByUsername(ctx context.Context, username string) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserProfileRepositoryMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByUsername), ctx, username)
}

// HardDelete mocks base method.
func (m *MockUserProfileRepository) HardDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockUserProfileRepositoryMockRecorder) HardDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockUserProfileRepository)(nil).HardDelete), ctx, id)
}

// IncrementLoginAttempts mocks base method.
func (m *MockUserProfileRepository) IncrementLoginAttempts(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementLoginAttempts", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementLoginAttempts indicates an expected call of IncrementLoginAttempts.
func (mr *MockUserProfileRepositoryMockRecorder) IncrementLoginAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementLoginAttempts", reflect.TypeOf((*MockUserProfileRepository)(nil).IncrementLoginAttempts), ctx, userID)
}

// IsSystemUser mocks base method.
func (m *MockUserProfileRepository) IsSystemUser(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSystemUser", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSystemUser indicates an expected call of IsSystemUser.
func (mr *MockUserProfileRepositoryMockRecorder) IsSystemUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSystemUser", reflect.TypeOf((*MockUserProfileRepository)(nil).IsSystemUser), ctx, userID)
}

// ResetLoginAttempts mocks base method.
func (m *MockUserProfileRepository) ResetLoginAttempts(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetLoginAttempts", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetLoginAttempts indicates an expected call of ResetLoginAttempts.
func (mr *MockUserProfileRepositoryMockRecorder) ResetLoginAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetLoginAttempts", reflect.TypeOf((*MockUserProfileRepository)(nil).ResetLoginAttempts), ctx, userID)
}

// Restore mocks base method.
func (m *MockUserProfileRepository) Restore(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockUserProfileRepositoryMockRecorder) Restore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockUserProfileRepository)(nil).Restore), ctx, id)
}

// SetMustChangePassword mocks base method.
func (m *MockUserProfileRepository) SetMustChangePassword(ctx context.Context, userID string, mustChange bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMustChangePassword", ctx, userID, mustChange)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMustChangePassword indicates an expected call of SetMustChangePassword.
func (mr *MockUserProfileRepositoryMockRecorder) SetMustChangePassword(ctx, userID, mustChange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMustChangePassword", reflect.TypeOf((*MockUserProfileRepository)(nil).SetMustChangePassword), ctx, userID, mustChange)
}

// SoftDelete mocks base method.
func (m *MockUserProfileRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserProfileRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserProfileRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserProfileRepository) Update(ctx context.Context, entity *models.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfileRepository)(nil).Update), ctx, entity)
}

// UpdateLastLoginTime mocks base method.
func (m *MockUserProfileRepository) UpdateLastLoginTime(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLoginTime", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLoginTime indicates an expected call of UpdateLastLoginTime.
func (mr *MockUserProfileRepositoryMockRecorder) UpdateLastLoginTime(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLoginTime", reflect.TypeOf((*MockUserProfileRepository)(nil).UpdateLastLoginTime), ctx, userID)
}

// UpdateLoginAttempts mocks base method.
func (m *MockUserProfileRepository) UpdateLoginAttempts(ctx context.Context, userID string, attempts int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoginAttempts", ctx, userID, attempts)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoginAttempts indicates an expected call of UpdateLoginAttempts.
func (mr *MockUserProfileRepositoryMockRecorder) UpdateLoginAttempts(ctx, userID, attempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoginAttempts", reflect.TypeOf((*MockUserProfileRepository)(nil).UpdateLoginAttempts), ctx, userID, attempts)
}

// UpdatePassword mocks base method.
func (m *MockUserProfileRepository) UpdatePassword(ctx context.Context, userID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserProfileRepositoryMockRecorder) UpdatePassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserProfileRepository)(nil).UpdatePassword), ctx, userID, passwordHash)
}

// WithTx mocks base method.
func (m *MockUserProfileRepository) WithTx(tx *gorm.DB) base.BaseRepository[models.UserProfile] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(base.BaseRepository[models.UserProfile])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserProfileRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserProfileRepository)(nil).WithTx), tx)
}
