// Code generated by hertz generator. Modified to integrate with domain service.

package oauth2

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	oauth2model "github.com/masonsxu/cloudwego-microservice-demo/gateway/biz/model/oauth2"
	"github.com/masonsxu/cloudwego-microservice-demo/gateway/internal/application/context/auth_context"
	oauth2svc "github.com/masonsxu/cloudwego-microservice-demo/gateway/internal/domain/service/oauth2"
	"github.com/masonsxu/cloudwego-microservice-demo/gateway/internal/infrastructure/errors"
)

var oauth2MgmtService oauth2svc.OAuth2ManagementService

// SetOAuth2ManagementService 注入 OAuth2 管理服务实例（由 Wire 在启动时调用）
func SetOAuth2ManagementService(service oauth2svc.OAuth2ManagementService) {
	oauth2MgmtService = service
}

// CreateOAuth2Client 创建 OAuth2 客户端
// @Summary 创建 OAuth2 客户端
// @Description 创建新的 OAuth2 客户端应用，返回客户端密钥（仅此一次可见）
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param request body oauth2.CreateOAuth2ClientRequestDTO true "客户端配置信息"
// @Success 201 {object} oauth2.CreateOAuth2ClientResponseDTO "创建成功，返回客户端信息和密钥"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/clients [POST]
func CreateOAuth2Client(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.CreateOAuth2ClientRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := oauth2MgmtService.CreateClient(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "创建 OAuth2 客户端失败")
		return
	}

	errors.JSON(c, consts.StatusCreated, resp)
}

// GetOAuth2Client 获取 OAuth2 客户端详情
// @Summary 获取 OAuth2 客户端详情
// @Description 根据客户端ID查询 OAuth2 客户端的详细信息
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path string true "客户端ID"
// @Success 200 {object} oauth2.OAuth2ClientResponseDTO "成功"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 404 {object} http_base.OperationStatusResponseDTO "客户端不存在"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/clients/{id} [GET]
func GetOAuth2Client(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.GetOAuth2ClientRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := oauth2MgmtService.GetClient(ctx, *req.Id)
	if err != nil {
		errors.HandleServiceError(c, err, "获取 OAuth2 客户端失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UpdateOAuth2Client 更新 OAuth2 客户端
// @Summary 更新 OAuth2 客户端
// @Description 更新指定 OAuth2 客户端的配置信息（不包括密钥）
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path string true "客户端ID"
// @Param request body oauth2.UpdateOAuth2ClientRequestDTO true "更新的配置信息"
// @Success 200 {object} oauth2.OAuth2ClientResponseDTO "更新成功"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 404 {object} http_base.OperationStatusResponseDTO "客户端不存在"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/clients/{id} [PUT]
func UpdateOAuth2Client(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.UpdateOAuth2ClientRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := oauth2MgmtService.UpdateClient(ctx, *req.Id, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "更新 OAuth2 客户端失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// DeleteOAuth2Client 删除 OAuth2 客户端
// @Summary 删除 OAuth2 客户端
// @Description 永久删除指定的 OAuth2 客户端（此操作不可逆）
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path string true "客户端ID"
// @Success 200 {object} http_base.OperationStatusResponseDTO "删除成功"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 404 {object} http_base.OperationStatusResponseDTO "客户端不存在"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/clients/{id} [DELETE]
func DeleteOAuth2Client(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.DeleteOAuth2ClientRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := oauth2MgmtService.DeleteClient(ctx, *req.Id)
	if err != nil {
		errors.HandleServiceError(c, err, "删除 OAuth2 客户端失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ListOAuth2Clients 列出 OAuth2 客户端
// @Summary 列出 OAuth2 客户端
// @Description 查询 OAuth2 客户端列表，支持按激活状态过滤
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param is_active query bool false "是否仅返回激活的客户端"
// @Success 200 {object} oauth2.ListOAuth2ClientsResponseDTO "成功"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/clients [GET]
func ListOAuth2Clients(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.ListOAuth2ClientsRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := oauth2MgmtService.ListClients(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "列出 OAuth2 客户端失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// RotateOAuth2ClientSecret 轮换客户端密钥
// @Summary 轮换客户端密钥
// @Description 生成新的客户端密钥，旧密钥立即失效（新密钥仅此一次可见）
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path string true "客户端ID"
// @Success 200 {object} oauth2.RotateOAuth2ClientSecretResponseDTO "轮换成功，返回新密钥"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 404 {object} http_base.OperationStatusResponseDTO "客户端不存在"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/clients/{id}/rotate-secret [POST]
func RotateOAuth2ClientSecret(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.RotateOAuth2ClientSecretRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := oauth2MgmtService.RotateClientSecret(ctx, *req.Id)
	if err != nil {
		errors.HandleServiceError(c, err, "轮换客户端密钥失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ListOAuth2Scopes 列出可用的 OAuth2 作用域
// @Summary 列出可用的 OAuth2 作用域
// @Description 获取系统中所有可用的 OAuth2 作用域（Scope）列表
// @Tags OAuth2 管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Success 200 {object} oauth2.ListOAuth2ScopesResponseDTO "成功"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/scopes [GET]
func ListOAuth2Scopes(ctx context.Context, c *app.RequestContext) {
	resp, err := oauth2MgmtService.ListScopes(ctx)
	if err != nil {
		errors.HandleServiceError(c, err, "列出作用域失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ListMyOAuth2Consents 查询我的授权记录
// @Summary 查询我的授权记录
// @Description 获取当前用户对所有 OAuth2 客户端的授权同意记录
// @Tags OAuth2 用户授权
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Success 200 {object} oauth2.ListOAuth2ConsentsResponseDTO "成功"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/consents [GET]
func ListMyOAuth2Consents(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.ListMyOAuth2ConsentsRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID, _ := auth_context.GetCurrentUserProfileID(c)

	resp, err := oauth2MgmtService.ListMyConsents(ctx, userID, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "列出授权同意失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// RevokeMyOAuth2Consent 撤销我的授权
// @Summary 撤销我的授权
// @Description 撤销当前用户对指定 OAuth2 客户端的授权同意
// @Tags OAuth2 用户授权
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param clientID path string true "客户端ID"
// @Success 200 {object} http_base.OperationStatusResponseDTO "撤销成功"
// @Failure 400 {object} http_base.OperationStatusResponseDTO "请求参数错误"
// @Failure 401 {object} http_base.OperationStatusResponseDTO "认证失败"
// @Failure 404 {object} http_base.OperationStatusResponseDTO "授权记录不存在"
// @Failure 500 {object} http_base.OperationStatusResponseDTO "内部错误"
// @Router /api/v1/oauth2/consents/{clientID} [DELETE]
func RevokeMyOAuth2Consent(ctx context.Context, c *app.RequestContext) {
	var req oauth2model.RevokeMyOAuth2ConsentRequestDTO
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID, _ := auth_context.GetCurrentUserProfileID(c)

	resp, err := oauth2MgmtService.RevokeMyConsent(ctx, userID, *req.ClientID)
	if err != nil {
		errors.HandleServiceError(c, err, "撤销授权同意失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}
