// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/casbin"
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/converter"
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/dal"
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/biz/logic"
	"github.com/masonsxu/cloudwego-microservice-demo/rpc/identity-srv/config"
	"github.com/rs/zerolog"
)

// Injectors from wire.go:

// InitializeApp 初始化应用容器
// 统一初始化所有依赖，避免重复创建实例
// 返回 cleanup 函数用于资源清理（如 OpenTelemetry shutdown）
func InitializeApp() (*AppContainer, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db, err := ProvideDB(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	dalDAL := dal.NewDALImpl(db)
	casbinConfig := ProvideCasbinConfig(configConfig)
	casbinManager, err := casbin.NewCasbinManager(db, casbinConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	logicLogic := logic.NewLogicImpl(dalDAL, configConfig, casbinManager)
	provider, cleanup, err := ProvideOtelProvider(configConfig)
	if err != nil {
		return nil, nil, err
	}
	registry, err := ProvideEtcdRegistry(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metaInfoMiddleware := ProvideMetaMiddleware(logger)
	error2 := ProvideKitexLogger(configConfig)
	serverOptions, err := ProvideServerOptions(configConfig, provider, registry, metaInfoMiddleware, error2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sqlDB, err := ProvideSQLDB(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	healthCheckServer := ProvideHealthCheckServer(configConfig, sqlDB)
	appContainer := NewAppContainer(configConfig, logger, db, logicLogic, serverOptions, healthCheckServer)
	return appContainer, func() {
		cleanup()
	}, nil
}

// InitializeLogger 仅初始化日志器
func InitializeLogger() (*zerolog.Logger, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	return logger, nil
}

// wire.go:

// InfrastructureSet 基础设施层 Provider 集合
// 包含配置、数据库、日志等基础组件
var InfrastructureSet = wire.NewSet(config.LoadConfig, ProvideDB,
	ProvideLogger,
)

// ConverterSet 转换器 Provider 集合
var ConverterSet = wire.NewSet(converter.NewConverter)

// CasbinSet Casbin 权限管理 Provider 集合
var CasbinSet = wire.NewSet(
	ProvideCasbinConfig, casbin.NewCasbinManager, casbin.NewMenuPermissionLogic,
)

// DALSet 数据访问层 Provider 集合
var DALSet = wire.NewSet(dal.NewDALImpl)

// LogicSet 业务逻辑层 Provider 集合
var LogicSet = wire.NewSet(logic.NewLogicImpl)

// ApplicationSet 完整应用 Provider 集合
// 包含业务逻辑相关的所有依赖
var ApplicationSet = wire.NewSet(
	InfrastructureSet,
	ConverterSet,
	CasbinSet,
	DALSet,
	LogicSet,
)

// AllSet 所有依赖注入集合
// 按照分层架构组织：基础设施层 -> 业务层 -> 服务器层 -> 健康检查层
var AllSet = wire.NewSet(
	ApplicationSet,
	ServerSet,
	HealthCheckSet,
	NewAppContainer,
)
