// Code generated by Kitex v0.16.1. DO NOT EDIT.

package policyservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	policy_srv "github.com/masonsxu/cloudwego-microservice-demo/rpc/policy-srv/kitex_gen/policy_srv"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Check(ctx context.Context, Req *policy_srv.CheckRequest, callOptions ...callopt.Option) (r *policy_srv.CheckResponse, err error)
	BatchCheck(ctx context.Context, Req *policy_srv.BatchCheckRequest, callOptions ...callopt.Option) (r *policy_srv.BatchCheckResponse, err error)
	ListPermissions(ctx context.Context, Req *policy_srv.ListPermissionsRequest, callOptions ...callopt.Option) (r *policy_srv.ListPermissionsResponse, err error)
	UpsertPolicy(ctx context.Context, Req *policy_srv.UpsertPolicyRequest, callOptions ...callopt.Option) (r *policy_srv.UpsertPolicyResponse, err error)
	DeletePolicy(ctx context.Context, Req *policy_srv.DeletePolicyRequest, callOptions ...callopt.Option) (r *policy_srv.DeletePolicyResponse, err error)
	ReloadPolicies(ctx context.Context, Req *policy_srv.ReloadPoliciesRequest, callOptions ...callopt.Option) (r *policy_srv.ReloadPoliciesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPolicyServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPolicyServiceClient struct {
	*kClient
}

func (p *kPolicyServiceClient) Check(ctx context.Context, Req *policy_srv.CheckRequest, callOptions ...callopt.Option) (r *policy_srv.CheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Check(ctx, Req)
}

func (p *kPolicyServiceClient) BatchCheck(ctx context.Context, Req *policy_srv.BatchCheckRequest, callOptions ...callopt.Option) (r *policy_srv.BatchCheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchCheck(ctx, Req)
}

func (p *kPolicyServiceClient) ListPermissions(ctx context.Context, Req *policy_srv.ListPermissionsRequest, callOptions ...callopt.Option) (r *policy_srv.ListPermissionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPermissions(ctx, Req)
}

func (p *kPolicyServiceClient) UpsertPolicy(ctx context.Context, Req *policy_srv.UpsertPolicyRequest, callOptions ...callopt.Option) (r *policy_srv.UpsertPolicyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertPolicy(ctx, Req)
}

func (p *kPolicyServiceClient) DeletePolicy(ctx context.Context, Req *policy_srv.DeletePolicyRequest, callOptions ...callopt.Option) (r *policy_srv.DeletePolicyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePolicy(ctx, Req)
}

func (p *kPolicyServiceClient) ReloadPolicies(ctx context.Context, Req *policy_srv.ReloadPoliciesRequest, callOptions ...callopt.Option) (r *policy_srv.ReloadPoliciesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReloadPolicies(ctx, Req)
}
