// Code generated by Kitex v0.16.1. DO NOT EDIT.

package policyservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	policy_srv "github.com/masonsxu/cloudwego-microservice-demo/rpc/policy-srv/kitex_gen/policy_srv"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Check": kitex.NewMethodInfo(
		checkHandler,
		newCheckArgs,
		newCheckResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchCheck": kitex.NewMethodInfo(
		batchCheckHandler,
		newBatchCheckArgs,
		newBatchCheckResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListPermissions": kitex.NewMethodInfo(
		listPermissionsHandler,
		newListPermissionsArgs,
		newListPermissionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpsertPolicy": kitex.NewMethodInfo(
		upsertPolicyHandler,
		newUpsertPolicyArgs,
		newUpsertPolicyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeletePolicy": kitex.NewMethodInfo(
		deletePolicyHandler,
		newDeletePolicyArgs,
		newDeletePolicyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReloadPolicies": kitex.NewMethodInfo(
		reloadPoliciesHandler,
		newReloadPoliciesArgs,
		newReloadPoliciesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	policyServiceServiceInfo                = NewServiceInfo()
	policyServiceServiceInfoForClient       = NewServiceInfoForClient()
	policyServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return policyServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return policyServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return policyServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PolicyService"
	handlerType := (*policy_srv.PolicyService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "policy_srv",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func checkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(policy_srv.CheckRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(policy_srv.PolicyService).Check(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckArgs:
		success, err := handler.(policy_srv.PolicyService).Check(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckArgs() interface{} {
	return &CheckArgs{}
}

func newCheckResult() interface{} {
	return &CheckResult{}
}

type CheckArgs struct {
	Req *policy_srv.CheckRequest
}

func (p *CheckArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckArgs) Unmarshal(in []byte) error {
	msg := new(policy_srv.CheckRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckArgs_Req_DEFAULT *policy_srv.CheckRequest

func (p *CheckArgs) GetReq() *policy_srv.CheckRequest {
	if !p.IsSetReq() {
		return CheckArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckResult struct {
	Success *policy_srv.CheckResponse
}

var CheckResult_Success_DEFAULT *policy_srv.CheckResponse

func (p *CheckResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckResult) Unmarshal(in []byte) error {
	msg := new(policy_srv.CheckResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckResult) GetSuccess() *policy_srv.CheckResponse {
	if !p.IsSetSuccess() {
		return CheckResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*policy_srv.CheckResponse)
}

func (p *CheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckResult) GetResult() interface{} {
	return p.Success
}

func batchCheckHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(policy_srv.BatchCheckRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(policy_srv.PolicyService).BatchCheck(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchCheckArgs:
		success, err := handler.(policy_srv.PolicyService).BatchCheck(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchCheckResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchCheckArgs() interface{} {
	return &BatchCheckArgs{}
}

func newBatchCheckResult() interface{} {
	return &BatchCheckResult{}
}

type BatchCheckArgs struct {
	Req *policy_srv.BatchCheckRequest
}

func (p *BatchCheckArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchCheckArgs) Unmarshal(in []byte) error {
	msg := new(policy_srv.BatchCheckRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchCheckArgs_Req_DEFAULT *policy_srv.BatchCheckRequest

func (p *BatchCheckArgs) GetReq() *policy_srv.BatchCheckRequest {
	if !p.IsSetReq() {
		return BatchCheckArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchCheckArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchCheckArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchCheckResult struct {
	Success *policy_srv.BatchCheckResponse
}

var BatchCheckResult_Success_DEFAULT *policy_srv.BatchCheckResponse

func (p *BatchCheckResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchCheckResult) Unmarshal(in []byte) error {
	msg := new(policy_srv.BatchCheckResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchCheckResult) GetSuccess() *policy_srv.BatchCheckResponse {
	if !p.IsSetSuccess() {
		return BatchCheckResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchCheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*policy_srv.BatchCheckResponse)
}

func (p *BatchCheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchCheckResult) GetResult() interface{} {
	return p.Success
}

func listPermissionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(policy_srv.ListPermissionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(policy_srv.PolicyService).ListPermissions(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListPermissionsArgs:
		success, err := handler.(policy_srv.PolicyService).ListPermissions(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListPermissionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListPermissionsArgs() interface{} {
	return &ListPermissionsArgs{}
}

func newListPermissionsResult() interface{} {
	return &ListPermissionsResult{}
}

type ListPermissionsArgs struct {
	Req *policy_srv.ListPermissionsRequest
}

func (p *ListPermissionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListPermissionsArgs) Unmarshal(in []byte) error {
	msg := new(policy_srv.ListPermissionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListPermissionsArgs_Req_DEFAULT *policy_srv.ListPermissionsRequest

func (p *ListPermissionsArgs) GetReq() *policy_srv.ListPermissionsRequest {
	if !p.IsSetReq() {
		return ListPermissionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListPermissionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListPermissionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListPermissionsResult struct {
	Success *policy_srv.ListPermissionsResponse
}

var ListPermissionsResult_Success_DEFAULT *policy_srv.ListPermissionsResponse

func (p *ListPermissionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListPermissionsResult) Unmarshal(in []byte) error {
	msg := new(policy_srv.ListPermissionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListPermissionsResult) GetSuccess() *policy_srv.ListPermissionsResponse {
	if !p.IsSetSuccess() {
		return ListPermissionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListPermissionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*policy_srv.ListPermissionsResponse)
}

func (p *ListPermissionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListPermissionsResult) GetResult() interface{} {
	return p.Success
}

func upsertPolicyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(policy_srv.UpsertPolicyRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(policy_srv.PolicyService).UpsertPolicy(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpsertPolicyArgs:
		success, err := handler.(policy_srv.PolicyService).UpsertPolicy(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpsertPolicyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpsertPolicyArgs() interface{} {
	return &UpsertPolicyArgs{}
}

func newUpsertPolicyResult() interface{} {
	return &UpsertPolicyResult{}
}

type UpsertPolicyArgs struct {
	Req *policy_srv.UpsertPolicyRequest
}

func (p *UpsertPolicyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpsertPolicyArgs) Unmarshal(in []byte) error {
	msg := new(policy_srv.UpsertPolicyRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpsertPolicyArgs_Req_DEFAULT *policy_srv.UpsertPolicyRequest

func (p *UpsertPolicyArgs) GetReq() *policy_srv.UpsertPolicyRequest {
	if !p.IsSetReq() {
		return UpsertPolicyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpsertPolicyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpsertPolicyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpsertPolicyResult struct {
	Success *policy_srv.UpsertPolicyResponse
}

var UpsertPolicyResult_Success_DEFAULT *policy_srv.UpsertPolicyResponse

func (p *UpsertPolicyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpsertPolicyResult) Unmarshal(in []byte) error {
	msg := new(policy_srv.UpsertPolicyResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpsertPolicyResult) GetSuccess() *policy_srv.UpsertPolicyResponse {
	if !p.IsSetSuccess() {
		return UpsertPolicyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpsertPolicyResult) SetSuccess(x interface{}) {
	p.Success = x.(*policy_srv.UpsertPolicyResponse)
}

func (p *UpsertPolicyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpsertPolicyResult) GetResult() interface{} {
	return p.Success
}

func deletePolicyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(policy_srv.DeletePolicyRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(policy_srv.PolicyService).DeletePolicy(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeletePolicyArgs:
		success, err := handler.(policy_srv.PolicyService).DeletePolicy(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeletePolicyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeletePolicyArgs() interface{} {
	return &DeletePolicyArgs{}
}

func newDeletePolicyResult() interface{} {
	return &DeletePolicyResult{}
}

type DeletePolicyArgs struct {
	Req *policy_srv.DeletePolicyRequest
}

func (p *DeletePolicyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeletePolicyArgs) Unmarshal(in []byte) error {
	msg := new(policy_srv.DeletePolicyRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeletePolicyArgs_Req_DEFAULT *policy_srv.DeletePolicyRequest

func (p *DeletePolicyArgs) GetReq() *policy_srv.DeletePolicyRequest {
	if !p.IsSetReq() {
		return DeletePolicyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeletePolicyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeletePolicyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeletePolicyResult struct {
	Success *policy_srv.DeletePolicyResponse
}

var DeletePolicyResult_Success_DEFAULT *policy_srv.DeletePolicyResponse

func (p *DeletePolicyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeletePolicyResult) Unmarshal(in []byte) error {
	msg := new(policy_srv.DeletePolicyResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeletePolicyResult) GetSuccess() *policy_srv.DeletePolicyResponse {
	if !p.IsSetSuccess() {
		return DeletePolicyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeletePolicyResult) SetSuccess(x interface{}) {
	p.Success = x.(*policy_srv.DeletePolicyResponse)
}

func (p *DeletePolicyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeletePolicyResult) GetResult() interface{} {
	return p.Success
}

func reloadPoliciesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(policy_srv.ReloadPoliciesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(policy_srv.PolicyService).ReloadPolicies(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReloadPoliciesArgs:
		success, err := handler.(policy_srv.PolicyService).ReloadPolicies(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReloadPoliciesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReloadPoliciesArgs() interface{} {
	return &ReloadPoliciesArgs{}
}

func newReloadPoliciesResult() interface{} {
	return &ReloadPoliciesResult{}
}

type ReloadPoliciesArgs struct {
	Req *policy_srv.ReloadPoliciesRequest
}

func (p *ReloadPoliciesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReloadPoliciesArgs) Unmarshal(in []byte) error {
	msg := new(policy_srv.ReloadPoliciesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReloadPoliciesArgs_Req_DEFAULT *policy_srv.ReloadPoliciesRequest

func (p *ReloadPoliciesArgs) GetReq() *policy_srv.ReloadPoliciesRequest {
	if !p.IsSetReq() {
		return ReloadPoliciesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReloadPoliciesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReloadPoliciesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReloadPoliciesResult struct {
	Success *policy_srv.ReloadPoliciesResponse
}

var ReloadPoliciesResult_Success_DEFAULT *policy_srv.ReloadPoliciesResponse

func (p *ReloadPoliciesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReloadPoliciesResult) Unmarshal(in []byte) error {
	msg := new(policy_srv.ReloadPoliciesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReloadPoliciesResult) GetSuccess() *policy_srv.ReloadPoliciesResponse {
	if !p.IsSetSuccess() {
		return ReloadPoliciesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReloadPoliciesResult) SetSuccess(x interface{}) {
	p.Success = x.(*policy_srv.ReloadPoliciesResponse)
}

func (p *ReloadPoliciesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReloadPoliciesResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Check(ctx context.Context, Req *policy_srv.CheckRequest) (r *policy_srv.CheckResponse, err error) {
	var _args CheckArgs
	_args.Req = Req
	var _result CheckResult
	if err = p.c.Call(ctx, "Check", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchCheck(ctx context.Context, Req *policy_srv.BatchCheckRequest) (r *policy_srv.BatchCheckResponse, err error) {
	var _args BatchCheckArgs
	_args.Req = Req
	var _result BatchCheckResult
	if err = p.c.Call(ctx, "BatchCheck", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPermissions(ctx context.Context, Req *policy_srv.ListPermissionsRequest) (r *policy_srv.ListPermissionsResponse, err error) {
	var _args ListPermissionsArgs
	_args.Req = Req
	var _result ListPermissionsResult
	if err = p.c.Call(ctx, "ListPermissions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpsertPolicy(ctx context.Context, Req *policy_srv.UpsertPolicyRequest) (r *policy_srv.UpsertPolicyResponse, err error) {
	var _args UpsertPolicyArgs
	_args.Req = Req
	var _result UpsertPolicyResult
	if err = p.c.Call(ctx, "UpsertPolicy", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeletePolicy(ctx context.Context, Req *policy_srv.DeletePolicyRequest) (r *policy_srv.DeletePolicyResponse, err error) {
	var _args DeletePolicyArgs
	_args.Req = Req
	var _result DeletePolicyResult
	if err = p.c.Call(ctx, "DeletePolicy", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReloadPolicies(ctx context.Context, Req *policy_srv.ReloadPoliciesRequest) (r *policy_srv.ReloadPoliciesResponse, err error) {
	var _args ReloadPoliciesArgs
	_args.Req = Req
	var _result ReloadPoliciesResult
	if err = p.c.Call(ctx, "ReloadPolicies", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
