// Code generated by Kitex v0.16.1. DO NOT EDIT.
package policyservice

import (
	server "github.com/cloudwego/kitex/server"
	policy_srv "github.com/masonsxu/cloudwego-microservice-demo/rpc/policy-srv/kitex_gen/policy_srv"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler policy_srv.PolicyService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler policy_srv.PolicyService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
